### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  id: ConsoleApplicationBase
  children:
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  - Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  langs:
  - csharp
  name: ConsoleApplicationBase
  nameWithType: ConsoleApplicationBase
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  type: Class
  summary: "提供屬性、 方法和目前的應用程式的相關事件。"
  remarks: "所公開的屬性`My.Application`物件只與目前的應用程式或 DLL 相關聯的傳回資料。 任何系統層級資訊可以修改為`My.Application`。       `My.Application`物件組成下列類別:-<xref:Microsoft.VisualBasic.ApplicationServices.ApplicationBase>提供適用於所有專案的成員。</xref:Microsoft.VisualBasic.ApplicationServices.ApplicationBase>      -<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase>提供適用於 Windows Form 應用程式的成員。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase>      -ConsoleApplicationBase 提供主控台應用程式中可用的成員。"
  example:
  - "This example uses the `My.Application.CommandLineArgs` property to examine the application's command-line arguments. If an argument is found that starts with `/input=`, the rest of that argument is displayed.  \n  \n [!code-vb[VbVbalrMyApplication#3](~/add/codesnippet/visualbasic/VbVbalrMyApplication/Form1.vb#3)]"
  syntax:
    content: 'public class ConsoleApplicationBase : Microsoft.VisualBasic.ApplicationServices.ApplicationBase'
  inheritance:
  - System.Object
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  implements: []
  inheritedMembers:
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeCulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.ChangeUICulture(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Culture
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.GetEnvironmentVariable(System.String)
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Info
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.Log
  - Microsoft.VisualBasic.ApplicationServices.ApplicationBase.UICulture
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: ConsoleApplicationBase()
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.ConsoleApplicationBase()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase&quot;></xref>類別。"
  syntax:
    content: public ConsoleApplicationBase ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  id: CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "取得集合，包含命令列引數為目前的應用程式的字串。"
  remarks: "`My.Application.CommandLineArgs`屬性提供目前的應用程式不部署 ClickOnce 應用程式的命令列引數的唯讀存取。       單一執行個體應用程式中，`My.Application.CommandLineArgs`屬性會傳回第一個執行個體的應用程式的命令列引數。 若要存取之引數的後續嘗試啟動單一執行個體的應用程式，您必須處理<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>事件，並檢查<xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine%2A>屬性<xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>引數。</xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs> </xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>      > [!NOTE] >`My.Application.CommandLineArgs`屬性會傳回命令列引數。 這是不同的行為<xref:System.Environment.CommandLine%2A>屬性，它會傳回除了引數的應用程式名稱。</xref:System.Environment.CommandLine%2A>      > [!NOTE] > 應用程式的 ClickOnce 部署中，使用<xref:System.Deployment.Application.ApplicationDeployment.ActivationUri%2A>屬性`My.Application.Deployment`取得命令列引數的物件。</xref:System.Deployment.Application.ApplicationDeployment.ActivationUri%2A> 如需詳細資訊，請參閱<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment%2A>.</xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment%2A>       下表列出包含工作的範例`My.Application.CommandLineArgs`屬性。      |||  |-|-|  |若要 |請參閱 |  |檢查後續嘗試啟動單一執行個體的應用程式的命令列引數 |<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>|     # # 可用性專案類型 | | |  |-|-|  |專案類型 |可用 |  |Windows 應用程式 |**Yes**|  |類別庫 |否 |  |主控台應用程式 |**Yes**|  |Windows 控制項程式庫 |否 |  |Web 控制項程式庫 |否 |  |Windows 服務 |**Yes**|  |網站 |否 |</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>"
  example:
  - "This example uses the `My.Application.CommandLineArgs` property to examine the application's command-line arguments. If an argument is found that starts with `/input=`, the rest of that argument is displayed.  \n  \n [!code-vb[VbVbalrMyApplication#3](~/add/codesnippet/visualbasic/VbVbalrMyApplication/Form1.vb#3)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLineArgs { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt;的<xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref>，包含命令列引數為目前的應用程式的字串。"
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  id: Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "取得目前應用程式的 ClickOnce 部署物件，可提供支援以程式設計方式更新目前的部署和支援視需要下載的檔案。"
  remarks: "`My.Application.Deployment`屬性會傳回應用程式的 ClickOnce<xref:System.Deployment.Application.ApplicationDeployment>物件。</xref:System.Deployment.Application.ApplicationDeployment> <xref:System.Deployment.Application.ApplicationDeployment>物件支援以程式設計方式更新目前的部署，以及支援視需要下載的檔案。</xref:System.Deployment.Application.ApplicationDeployment> 如需有關 ClickOnce 應用程式，以及如何將其部署的詳細資訊，請參閱[ClickOnce 安全性和部署](~/add/includes/ajax-current-ext-md.md)和[發行 ClickOnce 應用程式](~/add/includes/ajax-current-ext-md.md)。       確認<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed%2A>屬性是`True`您存取之前`My.Application.Deployment`屬性。</xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed%2A> 否則，如果不使用 ClickOnce 來部署應用程式，讀取`My.Application.Deployment`屬性會導致<xref:System.Deployment.Application.InvalidDeploymentException>例外狀況。</xref:System.Deployment.Application.InvalidDeploymentException> 如需有關部署 ClickOnce 應用程式的詳細資訊，請參閱[如何︰ 發行 ClickOnce 應用程式使用發行精靈](~/add/includes/ajax-current-ext-md.md)。       如需有關使用`My.Application.Deployment`屬性，請參閱[Visual Basic 應用程式模型概觀](~/add/includes/ajax-current-ext-md.md)。      ## 專案類型的可用性 | | |  |-|-|  |專案類型 |可用 |  |Windows Form 應用程式 |**Yes**|  |類別庫 |否 |  |主控台應用程式 |**Yes**|  |Windows Form 控制項程式庫 |否 |  |Web 控制項程式庫 |否 |  |Windows 服務 |**Yes**|  |網站 |否 |"
  example:
  - "This example downloads and installs the update after checking that the application is network-deployed. The <xref:System.Deployment.Application.ApplicationDeployment.Update%2A> method does not update the application unless it is out of date. The application has to restart to use the update.  \n  \n [!code-vb[VbVbalrMyApplication#4](~/add/codesnippet/visualbasic/VbVbalrMyApplication/Form1.vb#4)]  \n  \n Only applications that are ClickOnce deployed can be updated using the `My.Application.Deployment` object. For more information on deploying a ClickOnce application, see [How to: Publish a ClickOnce Application using the Publish Wizard](../Topic/How%20to:%20Publish%20a%20ClickOnce%20Application%20using%20the%20Publish%20Wizard.md)."
  syntax:
    content: public System.Deployment.Application.ApplicationDeployment Deployment { get; }
    return:
      type: System.Deployment.Application.ApplicationDeployment
      description: "傳回<xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;></xref>應用程式的 ClickOnce 部署的物件。"
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment*
  exceptions:
  - type: System.Deployment.Application.InvalidDeploymentException
    commentId: T:System.Deployment.Application.InvalidDeploymentException
    description: "未部署應用程式的 ClickOnce 應用程式。"
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  id: InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "設定要做為目前應用程式的命令列引數的值。"
  remarks: "這個方法可讓您設定內部<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase>類別</xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase>所使用的命令列引數的值 這個屬性會決定<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs%2A>屬性會傳回。</xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs%2A> 如果您未設定這個屬性，或您將此屬性設定為`Nothing`、<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs%2A>屬性會取得命令列引數，從<xref:System.Environment.CommandLine%2A>屬性。</xref:System.Environment.CommandLine%2A> </xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs%2A>"
  syntax:
    content: protected System.Collections.ObjectModel.ReadOnlyCollection<string> InternalCommandLine { set; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt;的<xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref>，包含要做為目前的應用程式的命令列引數的字串。"
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  id: IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  langs:
  - csharp
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "取得<xref uid=&quot;langword_csharp_Boolean&quot; name=&quot;Boolean&quot; href=&quot;&quot;></xref>表示是否已從網路使用 ClickOnce 部署應用程式。"
  remarks: "`My.Application.IsNetworkDeployed`屬性會指出是否已從網路使用 ClickOnce 部署應用程式。 如需有關 ClickOnce 應用程式的詳細資訊，請參閱[ClickOnce 安全性和部署](~/add/includes/ajax-current-ext-md.md)。       這個屬性是，您應該確認`True`您存取之前<xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment%2A>屬性。</xref:Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment%2A> 否則，如果未從網路使用 ClickOnce 部署應用程式，讀取`My.Application.Deployment`屬性會導致<xref:System.Deployment.Application.InvalidDeploymentException>例外狀況。</xref:System.Deployment.Application.InvalidDeploymentException>       如需有關如何設定 ClickOnce 的詳細資訊，請參閱[發行 ClickOnce 應用程式](~/add/includes/ajax-current-ext-md.md)。 如需有關部署 ClickOnce 應用程式的詳細資訊，請參閱[如何︰ 發行 ClickOnce 應用程式使用發行精靈](~/add/includes/ajax-current-ext-md.md)。       如需有關使用`My.Application.IsNetworkDeployed`屬性，請參閱[Visual Basic 應用程式模型概觀](~/add/includes/ajax-current-ext-md.md)。      ## 專案類型的可用性 | | |  |-|-|  |專案類型 |可用 |  |Windows Form 應用程式 |**Yes**|  |類別庫 |否 |  |主控台應用程式 |**Yes**|  |Windows Form 控制項程式庫 |否 |  |Web 控制項程式庫 |否 |  |Windows 服務 |**Yes**|  |網站 |否 |"
  example:
  - "This example downloads and installs the update after checking that the application is deployed from a network. The <xref:System.Deployment.Application.ApplicationDeployment.Update%2A> method does not update the application unless it is out of date. The application has to restart to use the update.  \n  \n [!code-vb[VbVbalrMyApplication#4](~/add/codesnippet/visualbasic/VbVbalrMyApplication/Form1.vb#4)]  \n  \n Only applications that are ClickOnce-deployed can be updated using the `My.Application.Deployment` object. For more information on deploying a ClickOnce application, see [How to: Publish a ClickOnce Application using the Publish Wizard](../Topic/How%20to:%20Publish%20a%20ClickOnce%20Application%20using%20the%20Publish%20Wizard.md)."
  syntax:
    content: public bool IsNetworkDeployed { get; }
    return:
      type: System.Boolean
      description: "A <xref uid=&quot;langword_csharp_Boolean&quot; name=&quot;Boolean&quot; href=&quot;&quot;> </xref>表示是否已從網路部署應用程式。 值是<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>如果目前的應用程式部署從一個網路; 否則，值是<xref uid=&quot;langword_csharp_False&quot; name=&quot;False&quot; href=&quot;&quot;> </xref>。"
  overload: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
  isExternal: false
  name: Microsoft.VisualBasic.ApplicationServices.ApplicationBase
- uid: System.Deployment.Application.InvalidDeploymentException
  parent: System.Deployment.Application
  isExternal: false
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException
  fullName: System.Deployment.Application.InvalidDeploymentException
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: ConsoleApplicationBase()
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase()
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.ConsoleApplicationBase()
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment
- uid: System.Deployment.Application.ApplicationDeployment
  parent: System.Deployment.Application
  isExternal: false
  name: ApplicationDeployment
  nameWithType: ApplicationDeployment
  fullName: System.Deployment.Application.ApplicationDeployment
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
  fullName: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: ConsoleApplicationBase
  nameWithType: ConsoleApplicationBase.ConsoleApplicationBase
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.CommandLineArgs*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: CommandLineArgs
  nameWithType: ConsoleApplicationBase.CommandLineArgs
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.Deployment*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: Deployment
  nameWithType: ConsoleApplicationBase.Deployment
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.InternalCommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: InternalCommandLine
  nameWithType: ConsoleApplicationBase.InternalCommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase.IsNetworkDeployed*
  parent: Microsoft.VisualBasic.ApplicationServices.ConsoleApplicationBase
  isExternal: false
  name: IsNetworkDeployed
  nameWithType: ConsoleApplicationBase.IsNetworkDeployed
