### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  id: ApplicationIdentity
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  langs:
  - csharp
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  type: Class
  summary: "ClickOnce 應用程式提供的唯一識別碼。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIdentity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  id: '#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;></xref>類別。"
  syntax:
    content: public ApplicationIdentity (string url, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity deployManifestIdentity, Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity applicationManifestIdentity);
    parameters:
    - id: url
      type: System.String
      description: "資訊清單 ClickOnce 部署的部署提供者 URL。"
    - id: deployManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "ClickOnce 部署資訊清單組件識別。"
    - id: applicationManifestIdentity
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "ClickOnce 應用程式資訊清單組件識別。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity&quot;></xref>類別。"
  syntax:
    content: public ApplicationIdentity (string url, string deployManifestPath, string applicationManifestPath);
    parameters:
    - id: url
      type: System.String
      description: "資訊清單 ClickOnce 部署的部署提供者 URL。"
    - id: deployManifestPath
      type: System.String
      description: "ClickOnce 部署資訊清單的路徑。 組件識別將取自指定的檔案。"
    - id: applicationManifestPath
      type: System.String
      description: "ClickOnce 應用程式資訊清單的路徑。 組件識別將取自指定的檔案。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  id: ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "傳回完整的 ClickOnce 應用程式識別。"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "字串，包含 ClickOnce 應用程式識別。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity,Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,AssemblyIdentity,AssemblyIdentity)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor(System.String,System.String,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String,String,String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String,String,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ApplicationIdentity(String,String,String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity.ApplicationIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity.ToString*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationIdentity
  isExternal: false
  name: ToString
  nameWithType: ApplicationIdentity.ToString
