### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  id: CompatibleFrameworkCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  langs:
  - csharp
  name: CompatibleFrameworkCollection
  nameWithType: CompatibleFrameworkCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  type: Class
  summary: "代表慣用上執行的應用程式的.NET framework 版本的集合。"
  remarks: "如果應用程式可以執行多個版本的.NET framework 中，版本應該列出按照優先權順序，從最慣用為至少慣用。 如果使用者電腦上安裝 CompatibleFrameworkCollection 類別中所列的.NET framework 版本，應用程式可以安裝並執行。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFrameworkCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  id: Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "新增至架構<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;></xref>類別。"
  syntax:
    content: public void Add (Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework compatibleFramework);
    parameters:
    - id: compatibleFramework
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "若要加入架構。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "清除集合。"
  syntax:
    content: public void Clear ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  id: Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得.NET Framework 版本中所列的數目<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;></xref>集合。"
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: "A<xref:System.Int32>中所列出物件，代表.NET Framework 版本號碼<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection&quot;></xref>集合。</xref:System.Int32>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得集合的列舉值。"
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "A<xref:System.Collections.IEnumerator>可以逐一查看集合的介面。</xref:System.Collections.IEnumerator>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得.NET Framework 上執行的應用程式慣用的版本。"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "檢查使用者電腦上的.NET Framework 版本。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
      description: "A <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;> </xref>物件，代表慣用上執行的應用程式的.NET framework 版本。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add(CompatibleFramework)
  nameWithType: CompatibleFrameworkCollection.Add(CompatibleFramework)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add(CompatibleFramework)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear()
  nameWithType: CompatibleFrameworkCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: CompatibleFrameworkCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: CompatibleFrameworkCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Add*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Add
  nameWithType: CompatibleFrameworkCollection.Add
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Clear*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Clear
  nameWithType: CompatibleFrameworkCollection.Clear
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Count*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Count
  nameWithType: CompatibleFrameworkCollection.Count
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.GetEnumerator*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: CompatibleFrameworkCollection.GetEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection.Item*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFrameworkCollection
  isExternal: false
  name: Item
  nameWithType: CompatibleFrameworkCollection.Item
