### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventHandler
  id: StartupEventHandler
  langs:
  - csharp
  name: StartupEventHandler
  nameWithType: StartupEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventHandler
  type: Delegate
  summary: "代表將處理的方法<xref uid=&quot;langword_csharp_My.Application.Startup&quot; name=&quot;My.Application.Startup&quot; href=&quot;&quot;></xref>事件。"
  remarks: "在 Visual Basic 中，您不需要明確地使用這個委派。 如需詳細資訊，請參閱<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>"
  example:
  - "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup?displayProperty=fullName>  \n  \n [Overview of the Visual Basic Application Model](~/add/includes/ajax-current-ext-md.md)"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void StartupEventHandler(object sender, StartupEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
