### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  id: BuiltInRole
  children:
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  - Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  langs:
  - csharp
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  type: Enum
  summary: "表示要檢查呼叫時角色類型<xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>方法。</xref:Microsoft.VisualBasic.ApplicationServices.User.IsInRole*>"
  remarks: "此列舉會提供類似的功能<xref:System.Security.Principal.WindowsBuiltInRole>列舉型別。</xref:System.Security.Principal.WindowsBuiltInRole>       這些角色代表一般為本機 Windows 群組，大部分的 Windows 安裝。"
  syntax:
    content: >-
      [System.ComponentModel.TypeConverter(typeof(Microsoft.VisualBasic.ApplicationServices.BuiltInRoleConverter))]

      public enum BuiltInRole
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  id: AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "帳戶操作員管理電腦或網域使用者帳戶。"
  syntax:
    content: AccountOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  id: Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "系統管理員具有完整且不受限制存取權的電腦或網域。"
  syntax:
    content: Administrator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  id: BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "備份操作員可以覆寫安全性限制的唯一目的是要備份或還原的檔案。"
  syntax:
    content: BackupOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  id: Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "來賓的限制多於使用者。"
  syntax:
    content: Guest
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  id: PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "進階使用者擁有大多數的系統管理權限，但有一些限制。 因此，進階使用者可以執行舊版的應用程式，除了認證的應用程式。"
  syntax:
    content: PowerUser
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  id: PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "列印運算子只能取用印表機的控制。"
  syntax:
    content: PrintOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  id: Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "複寫器支援在網域中的檔案複寫。"
  syntax:
    content: Replicator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  id: SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "系統操作員管理特定的電腦。"
  syntax:
    content: SystemOperator
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  id: User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  langs:
  - csharp
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  type: Field
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "使用者將無法防止意外或蓄意的全系統的變更。 因此，使用者可以執行通過認證的應用程式，但不是大多數的舊版應用程式。"
  syntax:
    content: User
    return:
      type: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: AccountOperator
  nameWithType: BuiltInRole.AccountOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.AccountOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  parent: Microsoft.VisualBasic.ApplicationServices
  isExternal: false
  name: BuiltInRole
  nameWithType: BuiltInRole
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Administrator
  nameWithType: BuiltInRole.Administrator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Administrator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: BackupOperator
  nameWithType: BuiltInRole.BackupOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.BackupOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Guest
  nameWithType: BuiltInRole.Guest
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Guest
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PowerUser
  nameWithType: BuiltInRole.PowerUser
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PowerUser
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: PrintOperator
  nameWithType: BuiltInRole.PrintOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.PrintOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: Replicator
  nameWithType: BuiltInRole.Replicator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.Replicator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: SystemOperator
  nameWithType: BuiltInRole.SystemOperator
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.SystemOperator
- uid: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
  parent: Microsoft.VisualBasic.ApplicationServices.BuiltInRole
  isExternal: false
  name: User
  nameWithType: BuiltInRole.User
  fullName: Microsoft.VisualBasic.ApplicationServices.BuiltInRole.User
