### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  id: StartupEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  - Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  langs:
  - csharp
  name: StartupEventArgs
  nameWithType: StartupEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  type: Class
  summary: "提供資料給<xref uid=&quot;langword_csharp_My.Application.Startup&quot; name=&quot;My.Application.Startup&quot; href=&quot;&quot;></xref>事件。"
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>事件發生時應用程式啟動時，如果應用程式實作 Visual Basic 應用程式模型。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> 如需詳細資訊，請參閱[Visual Basic 應用程式模型概觀](~/add/includes/ajax-current-ext-md.md)。       StartupEventArgs 包含應用程式的命令列引數，並指出是否應取消應用程式啟動。"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public class StartupEventArgs : System.ComponentModel.CancelEventArgs
  inheritance:
  - System.ComponentModel.CancelEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupEventArgs&quot;></xref>類別。"
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>事件發生時應用程式啟動時，如果應用程式實作 Visual Basic 應用程式模型。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> 如需詳細資訊，請參閱[Visual Basic 應用程式模型概觀](~/add/includes/ajax-current-ext-md.md)。       <xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>包含應用程式的命令列引數，並指出是否應取消應用程式啟動。</xref:Microsoft.VisualBasic.ApplicationServices.StartupEventArgs>"
  syntax:
    content: public StartupEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt;物件，其中包含應用程式的命令列引數。"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "取得應用程式的命令列引數。"
  remarks: "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup>事件發生時應用程式啟動時，如果應用程式實作 Visual Basic 應用程式模型。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Startup> 如需詳細資訊，請參閱[Visual Basic 應用程式模型概觀](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt;物件，其中包含應用程式的命令列引數。"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.CancelEventArgs
  isExternal: false
  name: System.ComponentModel.CancelEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String})
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs(ReadOnlyCollection<String>)
  nameWithType: StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.StartupEventArgs(ReadOnlyCollection<String>)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: StartupEventArgs
  nameWithType: StartupEventArgs.StartupEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupEventArgs.CommandLine
