### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlReaderSettings
  id: XamlXmlReaderSettings
  children:
  - System.Xaml.XamlXmlReaderSettings.#ctor
  - System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  - System.Xaml.XamlXmlReaderSettings.CloseInput
  - System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  - System.Xaml.XamlXmlReaderSettings.XmlLang
  - System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  langs:
  - csharp
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
  type: Class
  summary: "指定處理規則或選項設定<xref href=&quot;System.Xaml.XamlXmlReader&quot;> </xref> XAML 讀取器實作。"
  syntax:
    content: 'public class XamlXmlReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新執行個體<xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;></xref>類別。"
  syntax:
    content: public XamlXmlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  id: '#ctor(System.Xaml.XamlXmlReaderSettings)'
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新執行個體<xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;></xref>複製設定的現有類別<xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;></xref>物件。"
  syntax:
    content: public XamlXmlReaderSettings (System.Xaml.XamlXmlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlXmlReaderSettings
      description: "現有<xref href=&quot;System.Xaml.XamlXmlReaderSettings&quot;></xref>来複製物件。"
  overload: System.Xaml.XamlXmlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得或設定值，指出是否基礎資料流或文字讀取器應該關閉時<xref href=&quot;System.Xaml.XamlXmlReader&quot;></xref>已關閉。"
  syntax:
    content: public bool CloseInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果基礎資料流或讀取器應該關閉時<xref href=&quot;System.Xaml.XamlXmlReader&quot;></xref>已關閉，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Xaml.XamlXmlReaderSettings.CloseInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  id: SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得或設定值，判斷讀取器是否應該從預設值不同<xref href=&quot;System.Xaml.XamlXmlReader&quot;></xref>行為標記相容性內容的處理方式。"
  remarks: "預設的處理行為<xref:System.Xaml.XamlXmlReader>是的<xref:System.Xaml.XamlXmlReader>，提供初始設定，會包裝在建立的內部協助程式類別</xref:System.Xaml.XamlXmlReader></xref:System.Xaml.XamlXmlReader>中的 XML 標記相容性 此協助程式類別分別讀取標記相容性的節點，並輸入標記相容性的結構描述內容為基礎的節點。       建議將 SkipXmlCompatibilityProcessing 設定為 「 狀況`true`是:-您想要保留主要 XAML 資料流中的任何標記相容性內容。      -您已經有處理標記相容性，因為您正在使用讀取器可以處理標記相容性內容內嵌。      -您選擇略過 XAML 讀取器的實作中基於效能的 XML 相容性慣例。"
  syntax:
    content: public bool SkipXmlCompatibilityProcessing { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果直接使用起始讀取器，這表示做為主要資料流的一部分處理相容性的 XML 標記，並不會被視為相容性。 <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>如果使用預設行為，這會處理 XML 相容性分開。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  id: XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得或設定讀取器可能會將升級的值設為寫入的寫入器的語言<xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;></xref>節點中的屬性。"
  remarks: "呼叫端會負責確定您提供的字串適用於`xml:lang`使用量。"
  syntax:
    content: public string XmlLang { get; set; }
    return:
      type: System.String
      description: "若要使用可能的字串<xref uid=&quot;langword_csharp_xml:lang&quot; name=&quot;xml:lang&quot; href=&quot;&quot;></xref>基礎讀取器的輸出。"
  overload: System.Xaml.XamlXmlReaderSettings.XmlLang*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  id: XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  langs:
  - csharp
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "取得或設定值，這個值會決定 XAML 讀取器是否會指示要寫入的任何 XAML 寫入器<xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;></xref>節點中的屬性。 如果想要使用該行為，這項資訊會傳遞共用的 XAML 結構描述內容。"
  remarks: "XML 空白字元概念不強固程度足以成 XAML，套用，且通常會由 XAML 讀取器會忽略。"
  syntax:
    content: public bool XmlSpacePreserve { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果正在處理 XAML 節點資料流的寫入器可以寫入`xml:space=&quot;preserve&quot;`在輸出中。<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>如果<xref uid=&quot;langword_csharp_xml:space&quot; name=&quot;xml:space&quot; href=&quot;&quot;></xref>屬性不能寫入節點中。"
  overload: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.#ctor
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings()
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings()
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings()
- uid: System.Xaml.XamlXmlReaderSettings.#ctor(System.Xaml.XamlXmlReaderSettings)
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings(XamlXmlReaderSettings)
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
  fullName: System.Xaml.XamlXmlReaderSettings.XamlXmlReaderSettings(XamlXmlReaderSettings)
- uid: System.Xaml.XamlXmlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings
  fullName: System.Xaml.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
  fullName: System.Xaml.XamlXmlReaderSettings.CloseInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
  fullName: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
  fullName: System.Xaml.XamlXmlReaderSettings.XmlLang
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
  fullName: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve
- uid: System.Xaml.XamlXmlReaderSettings.#ctor*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XamlXmlReaderSettings
  nameWithType: XamlXmlReaderSettings.XamlXmlReaderSettings
- uid: System.Xaml.XamlXmlReaderSettings.CloseInput*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: CloseInput
  nameWithType: XamlXmlReaderSettings.CloseInput
- uid: System.Xaml.XamlXmlReaderSettings.SkipXmlCompatibilityProcessing*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: SkipXmlCompatibilityProcessing
  nameWithType: XamlXmlReaderSettings.SkipXmlCompatibilityProcessing
- uid: System.Xaml.XamlXmlReaderSettings.XmlLang*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlLang
  nameWithType: XamlXmlReaderSettings.XmlLang
- uid: System.Xaml.XamlXmlReaderSettings.XmlSpacePreserve*
  parent: System.Xaml.XamlXmlReaderSettings
  isExternal: false
  name: XmlSpacePreserve
  nameWithType: XamlXmlReaderSettings.XmlSpacePreserve
