### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.ManagedInstallerClass
  id: ManagedInstallerClass
  children:
  - System.Configuration.Install.ManagedInstallerClass.#ctor
  - System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  - System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  langs:
  - csharp
  name: ManagedInstallerClass
  nameWithType: ManagedInstallerClass
  fullName: System.Configuration.Install.ManagedInstallerClass
  type: Class
  summary: "代表受管理的安裝。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("42EB0342-0393-448f-84AA-D4BEB0283595")]

      public class ManagedInstallerClass : System.Configuration.Install.IManagedInstaller
  inheritance:
  - System.Object
  implements:
  - System.Configuration.Install.IManagedInstaller
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: ManagedInstallerClass()
  nameWithType: ManagedInstallerClass.ManagedInstallerClass()
  fullName: System.Configuration.Install.ManagedInstallerClass.ManagedInstallerClass()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.Install.ManagedInstallerClass&quot;></xref>類別。"
  syntax:
    content: public ManagedInstallerClass ();
    parameters: []
  overload: System.Configuration.Install.ManagedInstallerClass.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  id: InstallHelper(System.String[])
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: InstallHelper(String[])
  nameWithType: ManagedInstallerClass.InstallHelper(String[])
  fullName: System.Configuration.Install.ManagedInstallerClass.InstallHelper(String[])
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "處理的功能[Installutil.exe （安裝程式工具）](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: public static void InstallHelper (string[] args);
    parameters:
    - id: args
      type: System.String[]
      description: "引數傳遞給安裝程式工具。"
  overload: System.Configuration.Install.ManagedInstallerClass.InstallHelper*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  id: System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  isEii: true
  parent: System.Configuration.Install.ManagedInstallerClass
  langs:
  - csharp
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  type: Method
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "如需這個成員的說明，請參閱<xref:System.Configuration.Install.IManagedInstaller.ManagedInstall*>.</xref:System.Configuration.Install.IManagedInstaller.ManagedInstall*>"
  remarks: "這個成員是明確介面成員實作。 它可用時，才<xref:System.Configuration.Install.ManagedInstallerClass>執行個體轉換成<xref:System.Configuration.Install.IManagedInstaller>介面。</xref:System.Configuration.Install.IManagedInstaller> </xref:System.Configuration.Install.ManagedInstallerClass>"
  syntax:
    content: int IManagedInstaller.ManagedInstall (string argString, int hInstall);
    parameters:
    - id: argString
      type: System.String
      description: "若要安裝的命令列。"
    - id: hInstall
      type: System.Int32
      description: "要安裝的控制代碼。"
    return:
      type: System.Int32
      description: "Installutil.exe 傳回碼。 安裝成功則傳回 0。 其他值則表示失敗。"
  overload: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: ManagedInstallerClass()
  nameWithType: ManagedInstallerClass.ManagedInstallerClass()
  fullName: System.Configuration.Install.ManagedInstallerClass.ManagedInstallerClass()
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper(System.String[])
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: InstallHelper(String[])
  nameWithType: ManagedInstallerClass.InstallHelper(String[])
  fullName: System.Configuration.Install.ManagedInstallerClass.InstallHelper(String[])
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall(System.String,System.Int32)
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
  fullName: System.Configuration.Install.ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall(String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.ManagedInstallerClass.#ctor*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: ManagedInstallerClass
  nameWithType: ManagedInstallerClass.ManagedInstallerClass
- uid: System.Configuration.Install.ManagedInstallerClass.InstallHelper*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: InstallHelper
  nameWithType: ManagedInstallerClass.InstallHelper
- uid: System.Configuration.Install.ManagedInstallerClass.System#Configuration#Install#IManagedInstaller#ManagedInstall*
  parent: System.Configuration.Install.ManagedInstallerClass
  isExternal: false
  name: System.Configuration.Install.IManagedInstaller.ManagedInstall
  nameWithType: ManagedInstallerClass.System.Configuration.Install.IManagedInstaller.ManagedInstall
