### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  id: VariableElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  langs:
  - csharp
  name: VariableElement
  nameWithType: VariableElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  type: Class
  summary: "組態項目，指定要從活動上擷取的變數。"
  syntax:
    content: 'public class VariableElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: VariableElement()
  nameWithType: VariableElement.VariableElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.VariableElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.VariableElement&quot;></xref>類別。"
  syntax:
    content: public VariableElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: VariableElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "取得可唯一識別變數查詢的索引鍵。"
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "項目索引鍵。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: Name
  nameWithType: VariableElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "取得或設定要擷取的變數名稱。"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "變數的名稱。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  langs:
  - csharp
  name: Properties
  nameWithType: VariableElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "取得屬性的集合。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "項目的屬性集合。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: VariableElement()
  nameWithType: VariableElement.VariableElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.VariableElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: ElementKey
  nameWithType: VariableElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Name
  nameWithType: VariableElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Properties
  nameWithType: VariableElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: VariableElement
  nameWithType: VariableElement.VariableElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: ElementKey
  nameWithType: VariableElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Name
  nameWithType: VariableElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.VariableElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.VariableElement
  isExternal: false
  name: Properties
  nameWithType: VariableElement.Properties
