### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AdapterDictionary
  id: AdapterDictionary
  children:
  - System.Web.Configuration.AdapterDictionary.#ctor
  - System.Web.Configuration.AdapterDictionary.Item(System.String)
  langs:
  - csharp
  name: AdapterDictionary
  nameWithType: AdapterDictionary
  fullName: System.Web.Configuration.AdapterDictionary
  type: Class
  summary: "在執行階段由組態系統內部使用，以包含用於不同的瀏覽器上呈現伺服器控制項可用的介面卡的名稱。"
  syntax:
    content: 'public class AdapterDictionary : System.Collections.Specialized.OrderedDictionary'
  inheritance:
  - System.Object
  - System.Collections.Specialized.OrderedDictionary
  implements: []
  inheritedMembers:
  - System.Collections.Specialized.OrderedDictionary.Add(System.Object,System.Object)
  - System.Collections.Specialized.OrderedDictionary.AsReadOnly
  - System.Collections.Specialized.OrderedDictionary.Clear
  - System.Collections.Specialized.OrderedDictionary.Contains(System.Object)
  - System.Collections.Specialized.OrderedDictionary.CopyTo(System.Array,System.Int32)
  - System.Collections.Specialized.OrderedDictionary.Count
  - System.Collections.Specialized.OrderedDictionary.GetEnumerator
  - System.Collections.Specialized.OrderedDictionary.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Specialized.OrderedDictionary.Insert(System.Int32,System.Object,System.Object)
  - System.Collections.Specialized.OrderedDictionary.IsReadOnly
  - System.Collections.Specialized.OrderedDictionary.Item(System.Int32)
  - System.Collections.Specialized.OrderedDictionary.Item(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Keys
  - System.Collections.Specialized.OrderedDictionary.OnDeserialization(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Remove(System.Object)
  - System.Collections.Specialized.OrderedDictionary.RemoveAt(System.Int32)
  - System.Collections.Specialized.OrderedDictionary.System#Collections#ICollection#IsSynchronized
  - System.Collections.Specialized.OrderedDictionary.System#Collections#ICollection#SyncRoot
  - System.Collections.Specialized.OrderedDictionary.System#Collections#IDictionary#IsFixedSize
  - System.Collections.Specialized.OrderedDictionary.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Specialized.OrderedDictionary.System#Runtime#Serialization#IDeserializationCallback#OnDeserialization(System.Object)
  - System.Collections.Specialized.OrderedDictionary.Values
  platform:
  - net462
- uid: System.Web.Configuration.AdapterDictionary.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AdapterDictionary
  langs:
  - csharp
  name: AdapterDictionary()
  nameWithType: AdapterDictionary.AdapterDictionary()
  fullName: System.Web.Configuration.AdapterDictionary.AdapterDictionary()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在執行階段由組態系統在內部使用，若要建立這個類別的新執行個體。"
  syntax:
    content: public AdapterDictionary ();
    parameters: []
  overload: System.Web.Configuration.AdapterDictionary.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AdapterDictionary.Item(System.String)
  id: Item(System.String)
  parent: System.Web.Configuration.AdapterDictionary
  langs:
  - csharp
  name: Item(String)
  nameWithType: AdapterDictionary.Item(String)
  fullName: System.Web.Configuration.AdapterDictionary.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在執行階段由組態系統內部使用，取得或設定指定的配接器名稱。"
  syntax:
    content: public string this[string key] { get; set; }
    parameters:
    - id: key
      type: System.String
      description: "指定的配接器的索引鍵。"
    return:
      type: System.String
      description: "指定的配接器的名稱。"
  overload: System.Web.Configuration.AdapterDictionary.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Specialized.OrderedDictionary
  isExternal: false
  name: System.Collections.Specialized.OrderedDictionary
- uid: System.Web.Configuration.AdapterDictionary.#ctor
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: AdapterDictionary()
  nameWithType: AdapterDictionary.AdapterDictionary()
  fullName: System.Web.Configuration.AdapterDictionary.AdapterDictionary()
- uid: System.Web.Configuration.AdapterDictionary.Item(System.String)
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: Item(String)
  nameWithType: AdapterDictionary.Item(String)
  fullName: System.Web.Configuration.AdapterDictionary.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.AdapterDictionary.#ctor*
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: AdapterDictionary
  nameWithType: AdapterDictionary.AdapterDictionary
- uid: System.Web.Configuration.AdapterDictionary.Item*
  parent: System.Web.Configuration.AdapterDictionary
  isExternal: false
  name: Item
  nameWithType: AdapterDictionary.Item
