### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  id: MsmqIntegrationSecurityElement
  children:
  - System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.#ctor
  - System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode
  - System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties
  - System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport
  langs:
  - csharp
  name: MsmqIntegrationSecurityElement
  nameWithType: MsmqIntegrationSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  type: Class
  summary: "封裝訊息佇列 (MSMQ) 整合通道的傳輸安全性設定。"
  remarks: "訊息佇列整合通道允許[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]與現有訊息佇列應用程式通訊的應用程式。"
  syntax:
    content: 'public sealed class MsmqIntegrationSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  langs:
  - csharp
  name: MsmqIntegrationSecurityElement()
  nameWithType: MsmqIntegrationSecurityElement.MsmqIntegrationSecurityElement()
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.MsmqIntegrationSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.MsmqIntegrationSecurityElement&quot;></xref>類別。"
  syntax:
    content: public MsmqIntegrationSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: MsmqIntegrationSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;></xref>與訊息佇列整合通道相關聯。"
  remarks: '<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>是一種列舉，其中包含下列值︰<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>和<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>。</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> </xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode></xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode> 預設值是<xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>.</xref:System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode>'
  syntax:
    content: public System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
      description: "<xref href=&quot;System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode&quot;> </xref>與訊息佇列整合通道相關聯。"
  overload: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: MsmqIntegrationSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: MsmqIntegrationSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>與訊息佇列 (MSMQ) 整合通道相關聯。"
  remarks: "<xref:System.ServiceModel.MsmqTransportSecurity>封裝訊息佇列整合傳輸的安全性設定。</xref:System.ServiceModel.MsmqTransportSecurity> 這些是設定訊息佇列整合和已佇列之傳輸相同。 <xref:System.ServiceModel.MsmqTransportSecurity>可讓您設定驗證模式、 加密演算法、 安全雜湊演算法和保護層級。</xref:System.ServiceModel.MsmqTransportSecurity>"
  syntax:
    content: public System.ServiceModel.Configuration.MsmqTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.MsmqTransportSecurityElement
      description: "<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref>與訊息佇列整合通道相關聯。"
  overload: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: MsmqIntegrationSecurityElement()
  nameWithType: MsmqIntegrationSecurityElement.MsmqIntegrationSecurityElement()
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.MsmqIntegrationSecurityElement()
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode
- uid: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
  parent: System.ServiceModel.MsmqIntegration
  isExternal: false
  name: MsmqIntegrationSecurityMode
  nameWithType: MsmqIntegrationSecurityMode
  fullName: System.ServiceModel.MsmqIntegration.MsmqIntegrationSecurityMode
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Properties
  nameWithType: MsmqIntegrationSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport
- uid: System.ServiceModel.Configuration.MsmqTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MsmqTransportSecurityElement
  nameWithType: MsmqTransportSecurityElement
  fullName: System.ServiceModel.Configuration.MsmqTransportSecurityElement
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: MsmqIntegrationSecurityElement
  nameWithType: MsmqIntegrationSecurityElement.MsmqIntegrationSecurityElement
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Mode
  nameWithType: MsmqIntegrationSecurityElement.Mode
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Properties
  nameWithType: MsmqIntegrationSecurityElement.Properties
- uid: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.MsmqIntegrationSecurityElement
  isExternal: false
  name: Transport
  nameWithType: MsmqIntegrationSecurityElement.Transport
