### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement
  id: CustomBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.#ctor
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey(System.String)
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties
  - System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  langs:
  - csharp
  name: CustomBindingCollectionElement
  nameWithType: CustomBindingCollectionElement
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement
  type: Class
  summary: "代表集合<xref uid=&quot;langword_csharp_customBinding&quot; name=&quot;customBinding&quot; href=&quot;&quot;></xref>提供訊息的完整控制權的組態項目堆疊，讓您的使用者。 這個類別無法被繼承。"
  remarks: "自訂繫結上提供的完整控制權[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]訊息堆疊。 個別繫結定義訊息堆疊的指定組態項目堆疊項目在堆疊出現的順序。 每個項目定義，及設定堆疊的一個項目。 各個自訂繫結必須只有一個傳輸項目。 如果沒有這個項目，訊息堆疊就不完整。       項目堆疊中出現的順序很重要，因為它是作業套用至訊息的順序。 建議的堆疊項目順序如下所示︰ 1。  （選擇性） 2 的交易。  可信賴傳訊 （選擇性） 3。  安全性 （選擇性） 4。  傳輸 5。  編碼器 （選擇性）"
  syntax:
    content: 'public sealed class CustomBindingCollectionElement : System.ServiceModel.Configuration.BindingCollectionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: CustomBindingCollectionElement()
  nameWithType: CustomBindingCollectionElement.CustomBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.CustomBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.CustomBindingCollectionElement&quot;></xref>類別。"
  syntax:
    content: public CustomBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings
  id: Bindings
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: Bindings
  nameWithType: CustomBindingCollectionElement.Bindings
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得此區段中定義的繫結。"
  syntax:
    content: public System.ServiceModel.Configuration.CustomBindingElementCollection Bindings { get; }
    return:
      type: System.ServiceModel.Configuration.CustomBindingElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.CustomBindingElementCollection&quot;> </xref> ，其中包含這個區段中定義的所有繫結。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType
  id: BindingType
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: BindingType
  nameWithType: CustomBindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得這個繫結的型別。"
  syntax:
    content: public override Type BindingType { get; }
    return:
      type: System.Type
      description: "A <xref:System.Type>，其中包含繫結的型別。</xref:System.Type>"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings
  id: ConfiguredBindings
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: ConfiguredBindings
  nameWithType: CustomBindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得這個項目中包含的所有繫結組態項目。"
  syntax:
    content: public override System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement> ConfiguredBindings { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
      description: "此項目中包含的所有繫結組態項目的集合。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey(System.String)
  id: ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: ContainsKey(String)
  nameWithType: CustomBindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey(String)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "判斷特定的繫結是否存在於集合中使用指定的名稱。"
  syntax:
    content: public override bool ContainsKey (string name);
    parameters:
    - id: name
      type: System.String
      description: "要找出繫結的名稱。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果集合包含具有指定的繫結<code> name </code>，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault
  id: GetDefault
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: GetDefault()
  nameWithType: CustomBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.ServiceModel.Channels.Binding GetDefault ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.Binding
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: Properties
  nameWithType: CustomBindingCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  id: TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  langs:
  - csharp
  name: TryAdd(String,Binding,Configuration)
  nameWithType: CustomBindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd(String,Binding,Configuration)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override bool TryAdd (string name, System.ServiceModel.Channels.Binding binding, System.Configuration.Configuration config);
    parameters:
    - id: name
      type: System.String
      description: "即將加入。"
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "即將加入。"
    - id: config
      type: System.Configuration.Configuration
      description: "即將加入。"
    return:
      type: System.Boolean
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BindingCollectionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingCollectionElement
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: CustomBindingCollectionElement()
  nameWithType: CustomBindingCollectionElement.CustomBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.CustomBindingCollectionElement()
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: Bindings
  nameWithType: CustomBindingCollectionElement.Bindings
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings
- uid: System.ServiceModel.Configuration.CustomBindingElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: CustomBindingElementCollection
  nameWithType: CustomBindingElementCollection
  fullName: System.ServiceModel.Configuration.CustomBindingElementCollection
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: CustomBindingCollectionElement.BindingType
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: CustomBindingCollectionElement.ConfiguredBindings
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.ServiceModel.Configuration.IBindingConfigurationElement}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<IBindingConfigurationElement>
  nameWithType: ReadOnlyCollection<IBindingConfigurationElement>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.ServiceModel.Configuration.IBindingConfigurationElement>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Configuration.IBindingConfigurationElement
    name: IBindingConfigurationElement
    nameWithType: IBindingConfigurationElement
    fullName: IBindingConfigurationElement
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey(System.String)
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: ContainsKey(String)
  nameWithType: CustomBindingCollectionElement.ContainsKey(String)
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey(String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: GetDefault()
  nameWithType: CustomBindingCollectionElement.GetDefault()
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault()
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: Properties
  nameWithType: CustomBindingCollectionElement.Properties
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: TryAdd(String,Binding,Configuration)
  nameWithType: CustomBindingCollectionElement.TryAdd(String,Binding,Configuration)
  fullName: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd(String,Binding,Configuration)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: CustomBindingCollectionElement
  nameWithType: CustomBindingCollectionElement.CustomBindingCollectionElement
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Bindings*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: Bindings
  nameWithType: CustomBindingCollectionElement.Bindings
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.BindingType*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: BindingType
  nameWithType: CustomBindingCollectionElement.BindingType
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ConfiguredBindings*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: ConfiguredBindings
  nameWithType: CustomBindingCollectionElement.ConfiguredBindings
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.ContainsKey*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: ContainsKey
  nameWithType: CustomBindingCollectionElement.ContainsKey
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.GetDefault*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: GetDefault
  nameWithType: CustomBindingCollectionElement.GetDefault
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.Properties*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: Properties
  nameWithType: CustomBindingCollectionElement.Properties
- uid: System.ServiceModel.Configuration.CustomBindingCollectionElement.TryAdd*
  parent: System.ServiceModel.Configuration.CustomBindingCollectionElement
  isExternal: false
  name: TryAdd
  nameWithType: CustomBindingCollectionElement.TryAdd
