### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  id: PeerApplicationCollection
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  - System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  langs:
  - csharp
  name: PeerApplicationCollection
  nameWithType: PeerApplicationCollection
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  type: Class
  summary: "代表容器<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>項目。 此類型的執行個體由<xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>靜態方法。</xref:System.Net.PeerToPeer.Collaboration.ContactManager.GetContacts*>"
  remarks: "這個類別會不定義任何公用建構函式。"
  syntax:
    content: 'public class PeerApplicationCollection : System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>'
  inheritance:
  - System.Collections.ObjectModel.Collection`1
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "插入新<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>項目插入<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;></xref>位於指定的索引或索引鍵。"
  remarks: '`Null`不允許的項目。'
  syntax:
    content: protected override void InsertItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "要取代的項目以零為起始的索引"
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "新的值，指定索引處的項目"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  id: SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "取代<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>指定索引處。"
  remarks: '`Null`不允許的項目。'
  syntax:
    content: protected override void SetItem (int index, System.Net.PeerToPeer.Collaboration.PeerApplication item);
    parameters:
    - id: index
      type: System.Int32
      description: "要取代的項目以零為起始的索引。"
    - id: item
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "指定索引處的項目新值。"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  id: ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  langs:
  - csharp
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
  type: Method
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "傳回<xref:System.String>表示目前的值，每個<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>物件，並以逗號分隔。</xref:System.String>"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "A<xref:System.String>表示目前的值，每個<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>中<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplicationCollection&quot;> </xref>、 以逗號分隔。</xref:System.String>"
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ObjectModel.Collection`1
  isExternal: false
  name: System.Collections.ObjectModel.Collection<System.Net.PeerToPeer.Collaboration.PeerApplication>
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.InsertItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem(Int32,PeerApplication)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(System.Int32,System.Net.PeerToPeer.Collaboration.PeerApplication)
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem(Int32,PeerApplication)
  nameWithType: PeerApplicationCollection.SetItem(Int32,PeerApplication)
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem(Int32,PeerApplication)
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString()
  nameWithType: PeerApplicationCollection.ToString()
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.InsertItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: InsertItem
  nameWithType: PeerApplicationCollection.InsertItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.SetItem*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: SetItem
  nameWithType: PeerApplicationCollection.SetItem
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection.ToString*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationCollection
  isExternal: false
  name: ToString
  nameWithType: PeerApplicationCollection.ToString
