### YamlMime:ManagedReference
items:
- uid: System.Configuration.ISettingsProviderService
  id: ISettingsProviderService
  children:
  - System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  langs:
  - csharp
  name: ISettingsProviderService
  nameWithType: ISettingsProviderService
  fullName: System.Configuration.ISettingsProviderService
  type: Interface
  summary: "提供用於定義其他的應用程式設定提供者介面。"
  remarks: "<xref:System.Configuration.IPersistComponentSettings>介面可讓控制項和應用程式保存其應用程式的設定方式大致應用程式中裝載的元件。</xref:System.Configuration.IPersistComponentSettings> 不過，在某些情況下，應用程式或環境可能需要覆寫原生與它自己選擇的其中一個元件所使用的設定提供者。 ISettingsProviderService 介面讓您建立的輕量型通訊之服務的這類替代設定提供者，通常透過擁有<xref:System.ComponentModel.Container>.</xref:System.ComponentModel.Container>提供       ISettingsProviderService 常用的設計階段工具和應用程式設定為提供特殊支援的偵錯工具執行。 順暢地，讓這類的排列方式函式<xref:System.Configuration.ApplicationSettingsBase>類別包含建構函式可取得主控元件的參考。</xref:System.Configuration.ApplicationSettingsBase> 這些建構函式會自動查詢相容性設定提供者。"
  syntax:
    content: public interface ISettingsProviderService
  implements: []
  platform:
  - net462
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  id: GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  langs:
  - csharp
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "設定提供者會傳回與指定的設定屬性。"
  remarks: "GetSettingsProvider 方法可讓<xref:System.Configuration.ISettingsProviderService>提供它自己的序列化服務任何站台的元件。</xref:System.Configuration.ISettingsProviderService> 這個方法會判斷是否相關聯的設定提供者可以保存指定的應用程式設定屬性型別。 如果可以這個方法會傳回參考該設定提供者。否則它會傳回`null`。"
  syntax:
    content: public System.Configuration.SettingsProvider GetSettingsProvider (System.Configuration.SettingsProperty property);
    parameters:
    - id: property
      type: System.Configuration.SettingsProperty
      description: "<xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref>需要序列化。"
    return:
      type: System.Configuration.SettingsProvider
      description: "如果找不到， <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> ，可以保留指定的設定屬性，否則<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider(System.Configuration.SettingsProperty)
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider(SettingsProperty)
  nameWithType: ISettingsProviderService.GetSettingsProvider(SettingsProperty)
  fullName: System.Configuration.ISettingsProviderService.GetSettingsProvider(SettingsProperty)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.ISettingsProviderService.GetSettingsProvider*
  parent: System.Configuration.ISettingsProviderService
  isExternal: false
  name: GetSettingsProvider
  nameWithType: ISettingsProviderService.GetSettingsProvider
