### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  id: X509RecipientCertificateServiceElement
  children:
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.#ctor
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateServiceElement)
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName
  - System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType
  langs:
  - csharp
  name: X509RecipientCertificateServiceElement
  nameWithType: X509RecipientCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  type: Class
  summary: "表示組態項目會指定由服務用來識別本身的憑證。 這個類別無法被繼承。"
  syntax:
    content: 'public sealed class X509RecipientCertificateServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: X509RecipientCertificateServiceElement()
  nameWithType: X509RecipientCertificateServiceElement.X509RecipientCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509RecipientCertificateServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.X509RecipientCertificateServiceElement&quot;></xref>類別。"
  syntax:
    content: public X509RecipientCertificateServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateServiceElement)
  id: Copy(System.ServiceModel.Configuration.X509RecipientCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: Copy(X509RecipientCertificateServiceElement)
  nameWithType: X509RecipientCertificateServiceElement.Copy(X509RecipientCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy(X509RecipientCertificateServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "將指定的組態項目的內容複製到這個組態項目。"
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509RecipientCertificateServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
      description: "要複製的組態元素。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "組態檔為唯讀。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509RecipientCertificateServiceElement.FindValue
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定字串，指定要在 X.509 憑證存放區中搜尋的值。"
  remarks: "這個屬性所包含型別必須滿足指定之需求<xref:System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType%2A>值。</xref:System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType%2A> 預設為空字串。"
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "要在 X.509 憑證存放區中搜尋的值。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509RecipientCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509RecipientCertificateServiceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定值，這個值會指定用戶端憑證存放區的位置可用來驗證伺服器的憑證。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>可指定用戶端可用來驗證伺服器憑證之憑證存放區的位置。 預設值是<xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509RecipientCertificateServiceElement.StoreName
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定要開啟的 X.509 憑證存放區的名稱。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> ，其中包含要開啟的 X.509 憑證存放區的名稱。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509RecipientCertificateServiceElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定要執行 X.509 搜尋的型別。"
  remarks: "中包含的型別<xref:System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue%2A>必須滿足這個屬性的需求。</xref:System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> ，指定要執行 X.509 搜尋類型。"
  overload: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.#ctor
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: X509RecipientCertificateServiceElement()
  nameWithType: X509RecipientCertificateServiceElement.X509RecipientCertificateServiceElement()
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509RecipientCertificateServiceElement()
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy(System.ServiceModel.Configuration.X509RecipientCertificateServiceElement)
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: Copy(X509RecipientCertificateServiceElement)
  nameWithType: X509RecipientCertificateServiceElement.Copy(X509RecipientCertificateServiceElement)
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy(X509RecipientCertificateServiceElement)
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509RecipientCertificateServiceElement
  nameWithType: X509RecipientCertificateServiceElement
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: FindValue
  nameWithType: X509RecipientCertificateServiceElement.FindValue
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509RecipientCertificateServiceElement.Properties
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509RecipientCertificateServiceElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: StoreName
  nameWithType: X509RecipientCertificateServiceElement.StoreName
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: X509FindType
  nameWithType: X509RecipientCertificateServiceElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: X509RecipientCertificateServiceElement
  nameWithType: X509RecipientCertificateServiceElement.X509RecipientCertificateServiceElement
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Copy*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: Copy
  nameWithType: X509RecipientCertificateServiceElement.Copy
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.FindValue*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: FindValue
  nameWithType: X509RecipientCertificateServiceElement.FindValue
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.Properties*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: Properties
  nameWithType: X509RecipientCertificateServiceElement.Properties
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509RecipientCertificateServiceElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.StoreName*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: StoreName
  nameWithType: X509RecipientCertificateServiceElement.StoreName
- uid: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509RecipientCertificateServiceElement
  isExternal: false
  name: X509FindType
  nameWithType: X509RecipientCertificateServiceElement.X509FindType
