### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  id: ScriptingJsonSerializationSection
  children:
  - System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  - System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  - System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  - System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  - System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  langs:
  - csharp
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
  type: Class
  summary: "代表<xref uid=&quot;langword_csharp_jsonSerialization&quot; name=&quot;jsonSerialization&quot; href=&quot;&quot;></xref>組態區段中的<xref uid=&quot;langword_csharp_scripting&quot; name=&quot;scripting&quot; href=&quot;&quot;></xref>組態檔元素。 這個類別無法被繼承。"
  remarks: "ScriptingJsonSerializationSection 類別可讓您以程式設計方式存取和修改`jsonSerialization`在 ASP.NET 中使用 AJAX 功能的組態區段的項目。       您可以使用此類型來設定序列化和還原序列化的 AJAX 功能的應用程式設定值。"
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the ScriptingJsonSerializationSection class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization maxJsonLength=\"1000\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access ScriptingJsonSerializationSection programmatically.  \n  \n [!code-cs[System.Web.Configuration#3](~/add/codesnippet/csharp/t-system.web.configurati_75_1.cs)]\n [!code-vb[System.Web.Configuration#3](~/add/codesnippet/visualbasic/t-system.web.configurati_75_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingJsonSerializationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.ScriptingJsonSerializationSection&quot;></xref>類別。"
  syntax:
    content: public ScriptingJsonSerializationSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  id: Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得<xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;></xref>物件，其中包含的集合<xref href=&quot;System.Web.Configuration.Converter&quot;></xref>物件。"
  syntax:
    content: public System.Web.Configuration.ConvertersCollection Converters { get; }
    return:
      type: System.Web.Configuration.ConvertersCollection
      description: "A <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  id: MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得或設定可接受的最大長度<xref href=&quot;System.Web.Script.Serialization.JavaScriptSerializer&quot;> </xref> JavaScript Object Notation (JSON) 字串的物件。"
  remarks: "MaxJsonLength 屬性的值只適用於內部<xref:System.Web.Script.Serialization.JavaScriptSerializer>執行個體的非同步通訊層用來叫用 Web 服務方法。</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int MaxJsonLength { get; set; }
    return:
      type: System.Int32
      description: "整數，代表 JSON 字串的最大長度。 預設值為 102400 個字元。"
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  id: RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得或設定要處理的物件層級數目的限制。"
  remarks: "RecursionLimit 屬性參考到物件階層的最大層級的<xref:System.Web.Script.Serialization.JavaScriptSerializer>或將物件序列化為 JavaScript 物件標記法 (JSON) 字串還原序列化時將會處理。</xref:System.Web.Script.Serialization.JavaScriptSerializer>       RecursionLimit 值只適用於內部<xref:System.Web.Script.Serialization.JavaScriptSerializer>執行個體的非同步通訊層用來叫用 Web 服務方法。</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int RecursionLimit { get; set; }
    return:
      type: System.Int32
      description: "物件層級數目。 預設值為 100。"
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "屬性是設定為小於&1; 的值。"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ConvertersCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ConvertersCollection
  nameWithType: ConvertersCollection
  fullName: System.Web.Configuration.ConvertersCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
