### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerSecurityElement
  id: PeerSecurityElement
  children:
  - System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  - System.ServiceModel.Configuration.PeerSecurityElement.Mode
  - System.ServiceModel.Configuration.PeerSecurityElement.Properties
  - System.ServiceModel.Configuration.PeerSecurityElement.Transport
  langs:
  - csharp
  name: PeerSecurityElement
  nameWithType: PeerSecurityElement
  fullName: System.ServiceModel.Configuration.PeerSecurityElement
  type: Class
  summary: "定義對等電腦的安全性設定的組態項目。"
  syntax:
    content: 'public sealed class PeerSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: PeerSecurityElement()
  nameWithType: PeerSecurityElement.PeerSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.PeerSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化新的預設執行個體的<xref href=&quot;System.ServiceModel.Configuration.PeerSecurityElement&quot;></xref>類別。"
  syntax:
    content: public PeerSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: PeerSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得並設定與這個項目設定之對等所使用的安全性類型。"
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: "<xref:System.ServiceModel.SecurityMode>列舉值，指定與這個項目設定之對等所使用的安全性類型。</xref:System.ServiceModel.SecurityMode>"
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: PeerSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得與這個項目設定之對等所傳送安全訊息的傳輸類型。"
  syntax:
    content: public System.ServiceModel.Configuration.PeerTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.PeerTransportSecurityElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.PeerTransportSecurityElement&quot;></xref>指定以這個項目設定之對等所傳送安全訊息的傳輸類型。"
  overload: System.ServiceModel.Configuration.PeerSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: PeerSecurityElement()
  nameWithType: PeerSecurityElement.PeerSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.PeerSecurityElement()
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Mode
  nameWithType: PeerSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Transport
  nameWithType: PeerSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.PeerSecurityElement.Transport
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement
- uid: System.ServiceModel.Configuration.PeerSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: PeerSecurityElement
  nameWithType: PeerSecurityElement.PeerSecurityElement
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Mode
  nameWithType: PeerSecurityElement.Mode
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerSecurityElement.Properties
- uid: System.ServiceModel.Configuration.PeerSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.PeerSecurityElement
  isExternal: false
  name: Transport
  nameWithType: PeerSecurityElement.Transport
