### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.DeploymentSection
  id: DeploymentSection
  children:
  - System.Web.Configuration.DeploymentSection.#ctor
  - System.Web.Configuration.DeploymentSection.Properties
  - System.Web.Configuration.DeploymentSection.Retail
  langs:
  - csharp
  name: DeploymentSection
  nameWithType: DeploymentSection
  fullName: System.Web.Configuration.DeploymentSection
  type: Class
  summary: "定義通常用於實際執行伺服器覆寫適合只在開發電腦的應用程式層級設定的組態設定。"
  syntax:
    content: 'public sealed class DeploymentSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.DeploymentSection&quot;></xref>類別。"
  remarks: "ASP.NET 組態系統會呼叫這個建構函式。 取得執行個體<xref:System.Web.Configuration.DeploymentSection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.DeploymentSection>"
  syntax:
    content: public DeploymentSection ();
    parameters: []
  overload: System.Web.Configuration.DeploymentSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.Properties
  id: Properties
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.DeploymentSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.DeploymentSection.Retail
  id: Retail
  parent: System.Web.Configuration.DeploymentSection
  langs:
  - csharp
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指定是否在電腦上的 Web 應用程式會部署在<xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;></xref>模式。"
  remarks: "零售時`true`，ASP.NET 會停用追蹤輸出，停用偵錯功能，並停用詳細遠端使用者的系統產生的錯誤訊息。 應用程式的`customErrors`應用程式 Web.config 檔中的項目`mode`屬性強制`On`。 這些設定會覆寫應用程式 Web.config 檔案中所做的任何設定。      > [!NOTE] > 當您使用`retail`設定，您應該繼續設定`debug`屬性`false`應用程式部署到伺服器的 Web.config 檔中。 `debug`設定停用要求執行逾時，並不覆寫由`retail`設定。 如需詳細資訊，請參閱 [大部分的一般 ASP.NET 支援問題-從深層內支援的 Microsoft 開發人員報告](http://www.hanselman.com/blog/MostCommonASPNETSupportIssuesReportingFromDeepInsideMicrosoftDeveloperSupport.aspx)Scott Hanselman 部落格上。"
  example:
  - "The following configuration file example shows how to set this property to `true` in the machine.config file. The machine.config file is located in this folder:  \n  \n `%windir%\\Microsoft.NET\\Framework\\<frameworkversion>\\Config`  \n  \n```  \n<system.web>  \n  <deployment   \n    retail=\"true\" />  \n</system.web>  \n```"
  syntax:
    content: public bool Retail { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果 Web 應用程式部署在<xref uid=&quot;langword_csharp_retail&quot; name=&quot;retail&quot; href=&quot;&quot;></xref>模式，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.DeploymentSection.Retail*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.DeploymentSection.#ctor
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection()
  nameWithType: DeploymentSection.DeploymentSection()
  fullName: System.Web.Configuration.DeploymentSection.DeploymentSection()
- uid: System.Web.Configuration.DeploymentSection.Properties
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
  fullName: System.Web.Configuration.DeploymentSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.DeploymentSection.Retail
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
  fullName: System.Web.Configuration.DeploymentSection.Retail
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.DeploymentSection.#ctor*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: DeploymentSection
  nameWithType: DeploymentSection.DeploymentSection
- uid: System.Web.Configuration.DeploymentSection.Properties*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Properties
  nameWithType: DeploymentSection.Properties
- uid: System.Web.Configuration.DeploymentSection.Retail*
  parent: System.Web.Configuration.DeploymentSection
  isExternal: false
  name: Retail
  nameWithType: DeploymentSection.Retail
