### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  id: WSHttpTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType
  - System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm
  langs:
  - csharp
  name: WSHttpTransportSecurityElement
  nameWithType: WSHttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  type: Class
  summary: "表示定義 HTTP 傳輸的驗證設定的組態項目。 這個類別無法被繼承。"
  syntax:
    content: 'public sealed class WSHttpTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: WSHttpTransportSecurityElement()
  nameWithType: WSHttpTransportSecurityElement.WSHttpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.WSHttpTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.WSHttpTransportSecurityElement&quot;></xref>類別。"
  syntax:
    content: public WSHttpTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: WSHttpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定用來驗證服務的用戶端的認證。"
  syntax:
    content: public System.ServiceModel.HttpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.HttpClientCredentialType
      description: "有效<xref:System.ServiceModel.HttpClientCredentialType>值，指定用來驗證服務的用戶端的認證。</xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得<xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></xref>執行個體，包含要使用的組態設定擴充保護的工作階段。"
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement ExtendedProtectionPolicy { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
      description: "Returns <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></xref>."
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WSHttpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType
  id: ProxyCredentialType
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: ProxyCredentialType
  nameWithType: WSHttpTransportSecurityElement.ProxyCredentialType
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定用來對網域 proxy 用戶端進行驗證的認證。"
  syntax:
    content: public System.ServiceModel.HttpProxyCredentialType ProxyCredentialType { get; set; }
    return:
      type: System.ServiceModel.HttpProxyCredentialType
      description: "有效<xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;></xref>值，指定用來對網域 proxy 用戶端進行驗證的認證。"
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm
  id: Realm
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  langs:
  - csharp
  name: Realm
  nameWithType: WSHttpTransportSecurityElement.Realm
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定字串，指定摘要式驗證或基本驗證的驗證領域。"
  remarks: "驗證領域至少會指定執行驗證的主機名稱。 它也可以指定具有存取權的使用者集合。 使用者可以查詢驗證領域，以了解可以使用其中的幾個可能的使用者名稱和密碼。"
  syntax:
    content: public string Realm { get; set; }
    return:
      type: System.String
      description: "字串，指定摘要式驗證或基本驗證之驗證領域。 預設為空字串。"
  overload: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: WSHttpTransportSecurityElement()
  nameWithType: WSHttpTransportSecurityElement.WSHttpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.WSHttpTransportSecurityElement()
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: WSHttpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.HttpClientCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: HttpClientCredentialType
  nameWithType: HttpClientCredentialType
  fullName: System.ServiceModel.HttpClientCredentialType
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: WSHttpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSHttpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ProxyCredentialType
  nameWithType: WSHttpTransportSecurityElement.ProxyCredentialType
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType
- uid: System.ServiceModel.HttpProxyCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: HttpProxyCredentialType
  nameWithType: HttpProxyCredentialType
  fullName: System.ServiceModel.HttpProxyCredentialType
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: Realm
  nameWithType: WSHttpTransportSecurityElement.Realm
  fullName: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: WSHttpTransportSecurityElement
  nameWithType: WSHttpTransportSecurityElement.WSHttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: WSHttpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ExtendedProtectionPolicy*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: WSHttpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WSHttpTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.ProxyCredentialType*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: ProxyCredentialType
  nameWithType: WSHttpTransportSecurityElement.ProxyCredentialType
- uid: System.ServiceModel.Configuration.WSHttpTransportSecurityElement.Realm*
  parent: System.ServiceModel.Configuration.WSHttpTransportSecurityElement
  isExternal: false
  name: Realm
  nameWithType: WSHttpTransportSecurityElement.Realm
