### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "提供評估和編輯組態檔中的應用程式設定運算式，在設計階段屬性和方法。"
  remarks: "AppSettingsExpressionEditor 類別衍生自<xref:System.Web.UI.Design.ExpressionEditor>類別，並提供用於評估和關聯的控制項屬性中的應用程式設定參考，在設計階段實作。</xref:System.Web.UI.Design.ExpressionEditor> 例如，將控制項屬性的值繫結至應用程式設定運算式`AppSettings:mySettingKeyName`，表示控制項屬性值已設定使用`mySettingKeyName`值`appSettings`Web 組態檔區段。       視覺化設計工具裝載，例如[!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)]，選取從應用程式設定使用 AppSettingsExpressionEditor 類別`appSettings`組態區段，然後判斷設計階段呈現選取的運算式。       當您瀏覽至<xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>屬性在設計階段屬性方格控制項的視覺化設計工具會顯示一個對話方塊來提供執行階段值的控制項屬性的集合運算式。</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> 您可以選取清單運算式前置字元為基礎的運算式型別。 當您選取**AppSettings**運算式前置字元，從清單中，視覺化設計工具主應用程式會使用相關聯<xref:System.Web.UI.Design.ExpressionEditorSheet>物件來提供設計階段編輯功能`appSettings`評估，並將轉換的運算式字串的運算式，並使用 AppSettingsExpressionEditor 方法為基礎的應用程式設定運算式的語法。</xref:System.Web.UI.Design.ExpressionEditorSheet> 視覺化設計工具主應用程式可用於評估的運算式結果指派控制項的設計介面上所呈現的屬性值。       <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>AppSettingsExpressionEditor 物件的屬性會傳回字串`AppSettings`。</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> <xref:System.Web.Compilation.AppSettingsExpressionBuilder>類別是運算式前置詞相關聯`AppSettings`和 AppSettingsExpressionEditor 實作。</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>方法評估輸入應用程式設定運算式字串。</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>方法會傳回<xref:System.Web.UI.Design.ExpressionEditorSheet>用來輸入及編輯應用程式設定運算式的實作。</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "初始化的新執行個體<xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;></xref>類別。"
  remarks: "執行個體<xref:System.Web.UI.Design.AppSettingsExpressionEditor>類別基底類別，連同設定<xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>屬性設定為`AppSettings`。</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "評估應用程式設定運算式字串並提供設計階段值的控制項屬性。"
  remarks: "EvaluateExpression 方法查閱所指定的應用程式設定`expression`，然後傳回應用程式設定的值。       視覺化設計工具會使用 EvaluateExpression 方法來評估應用程式設定運算式，並提供設計階段相關聯的控制項屬性值。 視覺化設計工具會呼叫 EvaluateExpression 方法運算式的字串，並指派控制項的設計介面上所呈現的屬性值時，用於評估的運算式結果。       在執行階段，頁面剖析器會使用<xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>和<xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>方法對應<xref:System.Web.Compilation.AppSettingsExpressionBuilder>實作，以評估運算式，並提供執行階段相關聯的控制項屬性值。</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "要評估的應用程式設定運算式字串。 `expression`不包含<xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;></xref>運算式前置字元。"
    - id: parseTimeData
      type: System.Object
      description: "物件，其中包含其他剖析的資訊來評估`expression`。"
    - id: propertyType
      type: System.Type
      description: "控制項的屬性型別。"
    - id: serviceProvider
      type: System.IServiceProvider
      description: "用來取得額外的設計階段服務設計工具主應用程式所提供的服務提供者實作。"
    return:
      type: System.Object
      description: "所參考的物件<code> expression </code>，如果運算式評估成功，否則<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "傳回應用程式設定運算式的運算式編輯器工作表。"
  remarks: "GetExpressionEditorSheet 方法會傳回簡單的編輯器工作表的實作，其使用單一的輸入的字串的運算式。"
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "設定用來初始化運算式編輯器工作表的控制項屬性的運算式字串。 `expression`不包含<xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;></xref>運算式前置字元。"
    - id: serviceProvider
      type: System.IServiceProvider
      description: "用來取得額外的設計階段服務設計工具主應用程式所提供的服務提供者實作。"
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "<xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref>定義應用程式設定運算式屬性的實作。"
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
