### YamlMime:ManagedReference
items:
- uid: System.Web.UnvalidatedRequestValuesBase
  id: UnvalidatedRequestValuesBase
  children:
  - System.Web.UnvalidatedRequestValuesBase.#ctor
  - System.Web.UnvalidatedRequestValuesBase.Cookies
  - System.Web.UnvalidatedRequestValuesBase.Files
  - System.Web.UnvalidatedRequestValuesBase.Form
  - System.Web.UnvalidatedRequestValuesBase.Headers
  - System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  - System.Web.UnvalidatedRequestValuesBase.Path
  - System.Web.UnvalidatedRequestValuesBase.PathInfo
  - System.Web.UnvalidatedRequestValuesBase.QueryString
  - System.Web.UnvalidatedRequestValuesBase.RawUrl
  - System.Web.UnvalidatedRequestValuesBase.Url
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase
  nameWithType: UnvalidatedRequestValuesBase
  fullName: System.Web.UnvalidatedRequestValuesBase
  type: Class
  summary: "可做為提供對 HTTP 要求值的存取，而不觸發 ASP.NET 要求驗證的類別的基底類別。"
  remarks: "如需要求驗證資訊，請參閱<xref:System.Web.UnvalidatedRequestValues>.</xref:System.Web.UnvalidatedRequestValues>"
  syntax:
    content: public abstract class UnvalidatedRequestValuesBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  id: '#ctor'
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "從衍生類別中建構函式呼叫，以便初始化<xref href=&quot;System.Web.UnvalidatedRequestValuesBase&quot;></xref>類別。"
  syntax:
    content: protected UnvalidatedRequestValuesBase ();
    parameters: []
  overload: System.Web.UnvalidatedRequestValuesBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  id: Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得用戶端送出，而不觸發 ASP.NET 要求驗證的 cookie 集合。"
  syntax:
    content: public virtual System.Web.HttpCookieCollection Cookies { get; }
    return:
      type: System.Web.HttpCookieCollection
      description: "HTTP 要求的 cookie。"
  overload: System.Web.UnvalidatedRequestValuesBase.Cookies*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  id: Files
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得用戶端上傳，而不觸發 ASP.NET 要求驗證的檔案的集合。"
  syntax:
    content: public virtual System.Web.HttpFileCollectionBase Files { get; }
    return:
      type: System.Web.HttpFileCollectionBase
      description: "HTTP 要求中的檔案。"
  overload: System.Web.UnvalidatedRequestValuesBase.Files*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  id: Form
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得用戶端送出，而不觸發 ASP.NET 要求驗證的表單變數集合。"
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Form { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "從 HTTP 要求的表單變數。"
  overload: System.Web.UnvalidatedRequestValuesBase.Form*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  id: Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得用戶端傳送，而不觸發 ASP.NET 要求驗證的 HTTP 標頭的集合。"
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection Headers { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "從 HTTP 要求標頭。"
  overload: System.Web.UnvalidatedRequestValuesBase.Headers*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得指定的物件從<> *>， <> </> *>， <> </> *>，或<> *> 集合，而不觸發 ASP.NET 要求驗證。"
  syntax:
    content: public virtual string this[string field] { get; }
    parameters:
    - id: field
      type: System.String
      description: "要擷取之物件的索引鍵。"
    return:
      type: System.String
      description: "所指定的物件<code> field </code>參數。"
  overload: System.Web.UnvalidatedRequestValuesBase.Item*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  id: Path
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得要求之資源的虛擬路徑，而不觸發 ASP.NET 要求驗證。"
  syntax:
    content: public virtual string Path { get; }
    return:
      type: System.String
      description: "虛擬路徑。"
  overload: System.Web.UnvalidatedRequestValuesBase.Path*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  id: PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得具有 URL 副檔名，而不觸發 ASP.NET 要求的驗證資源的額外路徑資訊。"
  syntax:
    content: public virtual string PathInfo { get; }
    return:
      type: System.String
      description: "字串，包含資源的額外路徑資訊。"
  overload: System.Web.UnvalidatedRequestValuesBase.PathInfo*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  id: QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得 HTTP 查詢的集合用戶端送出，而不觸發 ASP.NET 要求驗證的字串變數。"
  syntax:
    content: public virtual System.Collections.Specialized.NameValueCollection QueryString { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "用戶端傳送的查詢字串變數的集合。"
  overload: System.Web.UnvalidatedRequestValuesBase.QueryString*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  id: RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "當在衍生類別中覆寫時，取得要求的 URL 所示的網站名稱，而不觸發 ASP.NET 要求驗證的部分。"
  remarks: "如果完成的要求 URL `http://www.contoso.com/default.aspx?id=44`，RawUrl 的值是`/default.aspx?id=44`。"
  syntax:
    content: public virtual string RawUrl { get; }
    return:
      type: System.String
      description: "網站名稱後面 URL 的一部分。"
  overload: System.Web.UnvalidatedRequestValuesBase.RawUrl*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  id: Url
  parent: System.Web.UnvalidatedRequestValuesBase
  langs:
  - csharp
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "在衍生類別中覆寫時，取得要求的 URL 資料而不觸發要求驗證。"
  remarks: "您可以擷取 URL 的資料，例如連接埠號碼、 主機名稱、 路徑資訊和資料從使用者的相關<xref:System.Uri>這個屬性會傳回的物件。</xref:System.Uri>"
  syntax:
    content: public virtual Uri Url { get; }
    return:
      type: System.Uri
      description: "包含要求的 URL 資料的物件。"
  overload: System.Web.UnvalidatedRequestValuesBase.Url*
  exceptions:
  - type: System.NotImplementedException
    commentId: T:System.NotImplementedException
    description: "未實作的屬性。"
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.NotImplementedException
  isExternal: true
  name: System.NotImplementedException
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: UnvalidatedRequestValuesBase()
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
  fullName: System.Web.UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase()
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
  fullName: System.Web.UnvalidatedRequestValuesBase.Cookies
- uid: System.Web.HttpCookieCollection
  parent: System.Web
  isExternal: false
  name: HttpCookieCollection
  nameWithType: HttpCookieCollection
  fullName: System.Web.HttpCookieCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Files
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
  fullName: System.Web.UnvalidatedRequestValuesBase.Files
- uid: System.Web.HttpFileCollectionBase
  parent: System.Web
  isExternal: true
  name: HttpFileCollectionBase
  nameWithType: HttpFileCollectionBase
  fullName: System.Web.HttpFileCollectionBase
- uid: System.Web.UnvalidatedRequestValuesBase.Form
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
  fullName: System.Web.UnvalidatedRequestValuesBase.Form
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValuesBase.Headers
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
  fullName: System.Web.UnvalidatedRequestValuesBase.Headers
- uid: System.Web.UnvalidatedRequestValuesBase.Item(System.String)
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Item(String)
  nameWithType: UnvalidatedRequestValuesBase.Item(String)
  fullName: System.Web.UnvalidatedRequestValuesBase.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValuesBase.Path
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
  fullName: System.Web.UnvalidatedRequestValuesBase.Path
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
  fullName: System.Web.UnvalidatedRequestValuesBase.PathInfo
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
  fullName: System.Web.UnvalidatedRequestValuesBase.QueryString
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
  fullName: System.Web.UnvalidatedRequestValuesBase.RawUrl
- uid: System.Web.UnvalidatedRequestValuesBase.Url
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
  fullName: System.Web.UnvalidatedRequestValuesBase.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Web.UnvalidatedRequestValuesBase.#ctor*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: UnvalidatedRequestValuesBase
  nameWithType: UnvalidatedRequestValuesBase.UnvalidatedRequestValuesBase
- uid: System.Web.UnvalidatedRequestValuesBase.Cookies*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValuesBase.Cookies
- uid: System.Web.UnvalidatedRequestValuesBase.Files*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValuesBase.Files
- uid: System.Web.UnvalidatedRequestValuesBase.Form*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValuesBase.Form
- uid: System.Web.UnvalidatedRequestValuesBase.Headers*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValuesBase.Headers
- uid: System.Web.UnvalidatedRequestValuesBase.Item*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Item
  nameWithType: UnvalidatedRequestValuesBase.Item
- uid: System.Web.UnvalidatedRequestValuesBase.Path*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValuesBase.Path
- uid: System.Web.UnvalidatedRequestValuesBase.PathInfo*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValuesBase.PathInfo
- uid: System.Web.UnvalidatedRequestValuesBase.QueryString*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValuesBase.QueryString
- uid: System.Web.UnvalidatedRequestValuesBase.RawUrl*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValuesBase.RawUrl
- uid: System.Web.UnvalidatedRequestValuesBase.Url*
  parent: System.Web.UnvalidatedRequestValuesBase
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValuesBase.Url
