### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TraceDisplayMode
  id: TraceDisplayMode
  children:
  - System.Web.Configuration.TraceDisplayMode.SortByCategory
  - System.Web.Configuration.TraceDisplayMode.SortByTime
  langs:
  - csharp
  name: TraceDisplayMode
  nameWithType: TraceDisplayMode
  fullName: System.Web.Configuration.TraceDisplayMode
  type: Enum
  summary: "指定追蹤訊息顯示的順序。"
  remarks: "這個列舉型別定義的值時，您可以使用<xref:System.Web.Configuration.TraceSection.TraceMode%2A>屬性。</xref:System.Web.Configuration.TraceSection.TraceMode%2A>"
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.TraceSection.TraceMode%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TraceSection> class.  \n  \n [!code-vb[System.Web.Configuration.TraceSection2#8](~/add/codesnippet/visualbasic/t-system.web.configurati_60_1.vb)]\n [!code-cs[System.Web.Configuration.TraceSection2#8](~/add/codesnippet/csharp/t-system.web.configurati_60_1.cs)]"
  syntax:
    content: public enum TraceDisplayMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TraceDisplayMode.SortByCategory
  id: SortByCategory
  parent: System.Web.Configuration.TraceDisplayMode
  langs:
  - csharp
  name: SortByCategory
  nameWithType: TraceDisplayMode.SortByCategory
  fullName: System.Web.Configuration.TraceDisplayMode.SortByCategory
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "依類別目錄依字母順序發出的追蹤訊息。"
  syntax:
    content: SortByCategory
    return:
      type: System.Web.Configuration.TraceDisplayMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TraceDisplayMode.SortByTime
  id: SortByTime
  parent: System.Web.Configuration.TraceDisplayMode
  langs:
  - csharp
  name: SortByTime
  nameWithType: TraceDisplayMode.SortByTime
  fullName: System.Web.Configuration.TraceDisplayMode.SortByTime
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "發出追蹤它們的處理順序的訊息。"
  syntax:
    content: SortByTime
    return:
      type: System.Web.Configuration.TraceDisplayMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TraceDisplayMode.SortByCategory
  parent: System.Web.Configuration.TraceDisplayMode
  isExternal: false
  name: SortByCategory
  nameWithType: TraceDisplayMode.SortByCategory
  fullName: System.Web.Configuration.TraceDisplayMode.SortByCategory
- uid: System.Web.Configuration.TraceDisplayMode
  parent: System.Web.Configuration
  isExternal: false
  name: TraceDisplayMode
  nameWithType: TraceDisplayMode
  fullName: System.Web.Configuration.TraceDisplayMode
- uid: System.Web.Configuration.TraceDisplayMode.SortByTime
  parent: System.Web.Configuration.TraceDisplayMode
  isExternal: false
  name: SortByTime
  nameWithType: TraceDisplayMode.SortByTime
  fullName: System.Web.Configuration.TraceDisplayMode.SortByTime
