### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupNameAttribute
  id: SettingsGroupNameAttribute
  children:
  - System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupNameAttribute.GroupName
  langs:
  - csharp
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute
  fullName: System.Configuration.SettingsGroupNameAttribute
  type: Class
  summary: "指定應用程式設定屬性群組的名稱。 這個類別無法被繼承。"
  remarks: "應用程式設定類別，衍生自<xref:System.Configuration.ApplicationSettingsBase>，定義一個或多個屬於相同的應用程式設定屬性群組的內容。</xref:System.Configuration.ApplicationSettingsBase> 根據預設，群組指派設定類別的名稱。 不過，SettingsGroupNameAttribute 可以用來明確指定屬性群組的名稱。 此名稱可能很有幫助組織的內容，以取得協助在設計階段開發工具和執行階段系統管理工具 中的大型集等等。 相關聯的設定提供者可能甚至會使用此名稱在資料存放區中組織設定。       SettingsGroupNameAttribute 只能套用在類別層級。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.SettingsGroupNameAttribute&quot;></xref>類別。"
  remarks: "雖然理論上的最大長度`groupName`參數受到的上限<xref:System.Int32>，實際限制，取決於可用性和設定提供者，所加諸的配額限制會小很多。</xref:System.Int32>      > [!NOTE] > 設定群組名稱不需要是唯一的。"
  syntax:
    content: public SettingsGroupNameAttribute (string groupName);
    parameters:
    - id: groupName
      type: System.String
      description: "A<xref:System.String>包含應用程式設定屬性群組的名稱。</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  id: GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  langs:
  - csharp
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得應用程式設定屬性群組的名稱。"
  remarks: "群組名稱屬性值由設定<xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>建構函式。</xref:System.Configuration.SettingsGroupNameAttribute.%23ctor%2A>"
  syntax:
    content: public string GroupName { get; }
    return:
      type: System.String
      description: "A<xref:System.String>包含應用程式設定屬性群組的名稱。</xref:System.String>"
  overload: System.Configuration.SettingsGroupNameAttribute.GroupName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute(String)
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
  fullName: System.Configuration.SettingsGroupNameAttribute.SettingsGroupNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
  fullName: System.Configuration.SettingsGroupNameAttribute.GroupName
- uid: System.Configuration.SettingsGroupNameAttribute.#ctor*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: SettingsGroupNameAttribute
  nameWithType: SettingsGroupNameAttribute.SettingsGroupNameAttribute
- uid: System.Configuration.SettingsGroupNameAttribute.GroupName*
  parent: System.Configuration.SettingsGroupNameAttribute
  isExternal: false
  name: GroupName
  nameWithType: SettingsGroupNameAttribute.GroupName
