### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationFileMap
  id: ConfigurationFileMap
  children:
  - System.Configuration.ConfigurationFileMap.#ctor
  - System.Configuration.ConfigurationFileMap.#ctor(System.String)
  - System.Configuration.ConfigurationFileMap.Clone
  - System.Configuration.ConfigurationFileMap.MachineConfigFilename
  langs:
  - csharp
  name: ConfigurationFileMap
  nameWithType: ConfigurationFileMap
  fullName: System.Configuration.ConfigurationFileMap
  type: Class
  summary: "定義電腦組態檔的設定檔對應。"
  remarks: "ConfigurationFileMap 類別用來指定電腦組態檔，通常名為 Machine.config 的路徑。"
  syntax:
    content: 'public class ConfigurationFileMap : ICloneable'
  inheritance:
  - System.Object
  implements:
  - System.ICloneable
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationFileMap.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: ConfigurationFileMap()
  nameWithType: ConfigurationFileMap.ConfigurationFileMap()
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.ConfigurationFileMap&quot;></xref>類別。"
  syntax:
    content: public ConfigurationFileMap ();
    parameters: []
  overload: System.Configuration.ConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationFileMap.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: ConfigurationFileMap(String)
  nameWithType: ConfigurationFileMap.ConfigurationFileMap(String)
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.ConfigurationFileMap&quot;></xref>類別，根據所提供的參數。"
  syntax:
    content: public ConfigurationFileMap (string machineConfigFilename);
    parameters:
    - id: machineConfigFilename
      type: System.String
      description: "電腦組態檔的名稱。"
  overload: System.Configuration.ConfigurationFileMap.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationFileMap.Clone
  id: Clone
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: Clone()
  nameWithType: ConfigurationFileMap.Clone()
  fullName: System.Configuration.ConfigurationFileMap.Clone()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "建立的現有複本<xref href=&quot;System.Configuration.ConfigurationFileMap&quot;></xref>物件。"
  syntax:
    content: public virtual object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "A <xref href=&quot;System.Configuration.ConfigurationFileMap&quot;></xref> object."
  overload: System.Configuration.ConfigurationFileMap.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  id: MachineConfigFilename
  parent: System.Configuration.ConfigurationFileMap
  langs:
  - csharp
  name: MachineConfigFilename
  nameWithType: ConfigurationFileMap.MachineConfigFilename
  fullName: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得或設定機器組態檔名稱的名稱。"
  remarks: "電腦組態檔名稱通常會設定為 Machine.config 中。"
  syntax:
    content: public string MachineConfigFilename { get; set; }
    return:
      type: System.String
      description: "電腦組態檔名稱。"
  overload: System.Configuration.ConfigurationFileMap.MachineConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationFileMap.#ctor
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: ConfigurationFileMap()
  nameWithType: ConfigurationFileMap.ConfigurationFileMap()
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap()
- uid: System.Configuration.ConfigurationFileMap.#ctor(System.String)
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: ConfigurationFileMap(String)
  nameWithType: ConfigurationFileMap.ConfigurationFileMap(String)
  fullName: System.Configuration.ConfigurationFileMap.ConfigurationFileMap(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationFileMap.Clone
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: Clone()
  nameWithType: ConfigurationFileMap.Clone()
  fullName: System.Configuration.ConfigurationFileMap.Clone()
- uid: System.Configuration.ConfigurationFileMap.MachineConfigFilename
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: MachineConfigFilename
  nameWithType: ConfigurationFileMap.MachineConfigFilename
  fullName: System.Configuration.ConfigurationFileMap.MachineConfigFilename
- uid: System.Configuration.ConfigurationFileMap.#ctor*
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: ConfigurationFileMap
  nameWithType: ConfigurationFileMap.ConfigurationFileMap
- uid: System.Configuration.ConfigurationFileMap.Clone*
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: Clone
  nameWithType: ConfigurationFileMap.Clone
- uid: System.Configuration.ConfigurationFileMap.MachineConfigFilename*
  parent: System.Configuration.ConfigurationFileMap
  isExternal: false
  name: MachineConfigFilename
  nameWithType: ConfigurationFileMap.MachineConfigFilename
