### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationPermission
  id: ConfigurationPermission
  children:
  - System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  - System.Configuration.ConfigurationPermission.Copy
  - System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  - System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  - System.Configuration.ConfigurationPermission.IsUnrestricted
  - System.Configuration.ConfigurationPermission.ToXml
  - System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  langs:
  - csharp
  name: ConfigurationPermission
  nameWithType: ConfigurationPermission
  fullName: System.Configuration.ConfigurationPermission
  type: Class
  summary: "提供可讓方法或類別，以存取組態檔的權限結構。"
  remarks: "ConfigurationPermission 類別會提供可讓方法或類別，以存取組態檔的權限結構。 此外，ConfigurationPermission 提供方法來解決之類的方法<xref:System.Configuration.ConfigurationPermission.Union%2A>和<xref:System.Configuration.ConfigurationPermission.Intersect%2A>。</xref:System.Configuration.ConfigurationPermission.Intersect%2A></xref:System.Configuration.ConfigurationPermission.Union%2A>透過多個權限的值"
  syntax:
    content: 'public sealed class ConfigurationPermission : System.Security.CodeAccessPermission, System.Security.Permissions.IUnrestrictedPermission'
  inheritance:
  - System.Object
  - System.Security.CodeAccessPermission
  implements:
  - System.Security.Permissions.IUnrestrictedPermission
  inheritedMembers:
  - System.Security.CodeAccessPermission.Assert
  - System.Security.CodeAccessPermission.Demand
  - System.Security.CodeAccessPermission.Deny
  - System.Security.CodeAccessPermission.Equals(System.Object)
  - System.Security.CodeAccessPermission.GetHashCode
  - System.Security.CodeAccessPermission.PermitOnly
  - System.Security.CodeAccessPermission.RevertAll
  - System.Security.CodeAccessPermission.RevertAssert
  - System.Security.CodeAccessPermission.RevertDeny
  - System.Security.CodeAccessPermission.RevertPermitOnly
  - System.Security.CodeAccessPermission.ToString
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  id: '#ctor(System.Security.Permissions.PermissionState)'
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: ConfigurationPermission(PermissionState)
  nameWithType: ConfigurationPermission.ConfigurationPermission(PermissionState)
  fullName: System.Configuration.ConfigurationPermission.ConfigurationPermission(PermissionState)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>類別。"
  syntax:
    content: public ConfigurationPermission (System.Security.Permissions.PermissionState state);
    parameters:
    - id: state
      type: System.Security.Permissions.PermissionState
      description: "若要授與權限層級。"
  overload: System.Configuration.ConfigurationPermission.#ctor*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The value of <code>state</code> is neither <xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref> nor <xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.Copy
  id: Copy
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Copy()
  nameWithType: ConfigurationPermission.Copy()
  fullName: System.Configuration.ConfigurationPermission.Copy()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "傳回新<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>擁有相同的權限的物件。"
  syntax:
    content: public override System.Security.IPermission Copy ();
    parameters: []
    return:
      type: System.Security.IPermission
      description: "新<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>擁有相同的權限。"
  overload: System.Configuration.ConfigurationPermission.Copy*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  id: FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: FromXml(SecurityElement)
  nameWithType: ConfigurationPermission.FromXml(SecurityElement)
  fullName: System.Configuration.ConfigurationPermission.FromXml(SecurityElement)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "從 XML 讀取權限狀態的值。"
  syntax:
    content: public override void FromXml (System.Security.SecurityElement securityElement);
    parameters:
    - id: securityElement
      type: System.Security.SecurityElement
      description: "要從中讀取的權限狀態的組態項目。"
  overload: System.Configuration.ConfigurationPermission.FromXml*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>securityElement</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The <xref uid=&quot;langword_csharp_unrestricted&quot; name=&quot;unrestricted&quot; href=&quot;&quot;></xref> attribute for the given <code>securityElement</code> is neither <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref> nor <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  id: Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Intersect(IPermission)
  nameWithType: ConfigurationPermission.Intersect(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Intersect(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "傳回邏輯交集<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>物件和指定的物件實作<xref href=&quot;System.Security.IPermission&quot;></xref>介面。"
  remarks: "雖然方法簽章接受實作任何物件<xref:System.Security.IPermission>介面<xref:System.ArgumentException>會擲回例外狀況，如果呼叫<xref:System.Object.GetType%2A>所參考的物件上方法`target`參數不會傳回<xref:System.Configuration.ConfigurationPermission?displayProperty=fullName>.</xref:System.Configuration.ConfigurationPermission?displayProperty=fullName> </xref:System.Object.GetType%2A> </xref:System.ArgumentException> </xref:System.Security.IPermission>"
  syntax:
    content: public override System.Security.IPermission Intersect (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: "包含執行交集的權限的物件。"
    return:
      type: System.Security.IPermission
      description: "之間的邏輯交集<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>和指定的物件實作<xref href=&quot;System.Security.IPermission&quot;> </xref>。"
  overload: System.Configuration.ConfigurationPermission.Intersect*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>target</code>未當做輸入<xref href=&quot;System.Configuration.ConfigurationPermission&quot;> </xref>。"
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  id: IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: IsSubsetOf(IPermission)
  nameWithType: ConfigurationPermission.IsSubsetOf(IPermission)
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "比較<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>物件實作<xref href=&quot;System.Security.IPermission&quot;></xref>介面。"
  remarks: "雖然方法簽章接受實作任何物件<xref:System.Security.IPermission>介面<xref:System.ArgumentException>會擲回例外狀況，如果呼叫<xref:System.Object.GetType%2A>所參考的物件上方法`target`參數不會傳回<xref:System.Configuration.ConfigurationPermission?displayProperty=fullName>.</xref:System.Configuration.ConfigurationPermission?displayProperty=fullName> </xref:System.Object.GetType%2A> </xref:System.ArgumentException> </xref:System.Security.IPermission>       如果所參考的物件`target`參數是`null`，之間的權限狀態進行比較<xref:System.Configuration.ConfigurationPermission>物件和<xref:System.Security.Permissions.PermissionState>值<xref:System.Security.Permissions.PermissionState>列舉型別。</xref:System.Security.Permissions.PermissionState> </xref:System.Security.Permissions.PermissionState> </xref:System.Configuration.ConfigurationPermission>"
  syntax:
    content: public override bool IsSubsetOf (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: "要比較的物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>權限狀態是否相等。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.ConfigurationPermission.IsSubsetOf*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>target</code>未當做輸入<xref href=&quot;System.Configuration.ConfigurationPermission&quot;> </xref>。"
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  id: IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: IsUnrestricted()
  nameWithType: ConfigurationPermission.IsUnrestricted()
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "指出是否的權限狀態<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>物件是<xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref>值<xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref>列舉型別。"
  syntax:
    content: public bool IsUnrestricted ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果權限狀態，如<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>是<xref href=&quot;System.Security.Permissions.PermissionState&quot;></xref>值<xref href=&quot;System.Security.Permissions.PermissionState&quot;> </xref>，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.ConfigurationPermission.IsUnrestricted*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.ToXml
  id: ToXml
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: ToXml()
  nameWithType: ConfigurationPermission.ToXml()
  fullName: System.Configuration.ConfigurationPermission.ToXml()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "傳回<xref href=&quot;System.Security.SecurityElement&quot;></xref>物件具有屬性值會根據目前<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>物件。"
  syntax:
    content: public override System.Security.SecurityElement ToXml ();
    parameters: []
    return:
      type: System.Security.SecurityElement
      description: "A <xref href=&quot;System.Security.SecurityElement&quot;> </xref>根據目前的屬性值<xref href=&quot;System.Configuration.ConfigurationPermission&quot;> </xref>。"
  overload: System.Configuration.ConfigurationPermission.ToXml*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  id: Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  langs:
  - csharp
  name: Union(IPermission)
  nameWithType: ConfigurationPermission.Union(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Union(IPermission)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "傳回的邏輯聯集<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>物件和物件，用於實作<xref href=&quot;System.Security.IPermission&quot;></xref>介面。"
  syntax:
    content: public override System.Security.IPermission Union (System.Security.IPermission target);
    parameters:
    - id: target
      type: System.Security.IPermission
      description: "要執行聯的物件。"
    return:
      type: System.Security.IPermission
      description: "邏輯聯集<xref href=&quot;System.Configuration.ConfigurationPermission&quot;></xref>和實作的物件<xref href=&quot;System.Security.IPermission&quot;> </xref>。"
  overload: System.Configuration.ConfigurationPermission.Union*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>target</code>未當做輸入<xref href=&quot;System.Configuration.ConfigurationPermission&quot;> </xref>。"
  platform:
  - net462
references:
- uid: System.Security.CodeAccessPermission
  isExternal: false
  name: System.Security.CodeAccessPermission
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationPermission.#ctor(System.Security.Permissions.PermissionState)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ConfigurationPermission(PermissionState)
  nameWithType: ConfigurationPermission.ConfigurationPermission(PermissionState)
  fullName: System.Configuration.ConfigurationPermission.ConfigurationPermission(PermissionState)
- uid: System.Security.Permissions.PermissionState
  parent: System.Security.Permissions
  isExternal: false
  name: PermissionState
  nameWithType: PermissionState
  fullName: System.Security.Permissions.PermissionState
- uid: System.Configuration.ConfigurationPermission.Copy
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Copy()
  nameWithType: ConfigurationPermission.Copy()
  fullName: System.Configuration.ConfigurationPermission.Copy()
- uid: System.Security.IPermission
  parent: System.Security
  isExternal: false
  name: IPermission
  nameWithType: IPermission
  fullName: System.Security.IPermission
- uid: System.Configuration.ConfigurationPermission.FromXml(System.Security.SecurityElement)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: FromXml(SecurityElement)
  nameWithType: ConfigurationPermission.FromXml(SecurityElement)
  fullName: System.Configuration.ConfigurationPermission.FromXml(SecurityElement)
- uid: System.Security.SecurityElement
  parent: System.Security
  isExternal: false
  name: SecurityElement
  nameWithType: SecurityElement
  fullName: System.Security.SecurityElement
- uid: System.Configuration.ConfigurationPermission.Intersect(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Intersect(IPermission)
  nameWithType: ConfigurationPermission.Intersect(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Intersect(IPermission)
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsSubsetOf(IPermission)
  nameWithType: ConfigurationPermission.IsSubsetOf(IPermission)
  fullName: System.Configuration.ConfigurationPermission.IsSubsetOf(IPermission)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsUnrestricted()
  nameWithType: ConfigurationPermission.IsUnrestricted()
  fullName: System.Configuration.ConfigurationPermission.IsUnrestricted()
- uid: System.Configuration.ConfigurationPermission.ToXml
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ToXml()
  nameWithType: ConfigurationPermission.ToXml()
  fullName: System.Configuration.ConfigurationPermission.ToXml()
- uid: System.Configuration.ConfigurationPermission.Union(System.Security.IPermission)
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Union(IPermission)
  nameWithType: ConfigurationPermission.Union(IPermission)
  fullName: System.Configuration.ConfigurationPermission.Union(IPermission)
- uid: System.Configuration.ConfigurationPermission.#ctor*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ConfigurationPermission
  nameWithType: ConfigurationPermission.ConfigurationPermission
- uid: System.Configuration.ConfigurationPermission.Copy*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Copy
  nameWithType: ConfigurationPermission.Copy
- uid: System.Configuration.ConfigurationPermission.FromXml*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: FromXml
  nameWithType: ConfigurationPermission.FromXml
- uid: System.Configuration.ConfigurationPermission.Intersect*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Intersect
  nameWithType: ConfigurationPermission.Intersect
- uid: System.Configuration.ConfigurationPermission.IsSubsetOf*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsSubsetOf
  nameWithType: ConfigurationPermission.IsSubsetOf
- uid: System.Configuration.ConfigurationPermission.IsUnrestricted*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: IsUnrestricted
  nameWithType: ConfigurationPermission.IsUnrestricted
- uid: System.Configuration.ConfigurationPermission.ToXml*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: ToXml
  nameWithType: ConfigurationPermission.ToXml
- uid: System.Configuration.ConfigurationPermission.Union*
  parent: System.Configuration.ConfigurationPermission
  isExternal: false
  name: Union
  nameWithType: ConfigurationPermission.Union
