### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.MouseActionValueSerializer
  id: MouseActionValueSerializer
  children:
  - System.Windows.Input.MouseActionValueSerializer.#ctor
  - System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: MouseActionValueSerializer
  nameWithType: MouseActionValueSerializer
  fullName: System.Windows.Input.MouseActionValueSerializer
  type: Class
  summary: "將轉換的執行個體<xref:System.String>的執行個體，以及<xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>。</xref:System.String>"
  remarks: "這個類別通常只能使用<xref:System.Windows.Markup.Primitives.MarkupWriter>進行序列化。</xref:System.Windows.Markup.Primitives.MarkupWriter>      <a name=&quot;xamlTextUsage_MouseActionValueSerializer&quot;></a># # XAML 文字用法"
  syntax:
    content: 'public class MouseActionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "初始化的新執行個體<xref href=&quot;System.Windows.Input.MouseActionValueSerializer&quot;></xref>類別。"
  syntax:
    content: public MouseActionValueSerializer ();
    parameters: []
  overload: System.Windows.Input.MouseActionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "判斷指定<xref:System.String>可以轉換為執行個體<xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>。</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "要評估以進行轉換的字串。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Boolean
      description: "一律傳回<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "判斷指定<xref href=&quot;System.Windows.Input.MouseAction&quot;></xref>可以轉換成<xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "若要評估以進行轉換的輔助按鍵。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<code> value </code>可以轉換成<xref:System.String>，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。</xref:System.String>"
  overload: System.Windows.Input.MouseActionValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "將轉換<xref:System.String>到<xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>。</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "要轉換的字串<xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Object
      description: "新執行個體<xref href=&quot;System.Windows.Input.MouseAction&quot;></xref>根據所提供<code> value </code>。"
  overload: System.Windows.Input.MouseActionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "將轉換的執行個體<xref href=&quot;System.Windows.Input.MouseAction&quot;></xref>至<xref:System.String>。</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "要轉換為字串的索引鍵。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.String
      description: "指定的非變異字串表示法<xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>。"
  overload: System.Windows.Input.MouseActionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: MouseActionValueSerializer
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: MouseActionValueSerializer.CanConvertFromString
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: MouseActionValueSerializer.CanConvertToString
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: MouseActionValueSerializer.ConvertFromString
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: MouseActionValueSerializer.ConvertToString
