### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.VirtualDirectoryMapping
  id: VirtualDirectoryMapping
  children:
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  - System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  - System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  - System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  - System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  - System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  langs:
  - csharp
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping
  fullName: System.Web.Configuration.VirtualDirectoryMapping
  type: Class
  summary: "指定 Web 應用程式的自訂虛擬目錄階層。 這個類別無法被繼承。"
  syntax:
    content: public sealed class VirtualDirectoryMapping
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  id: '#ctor(System.String,System.Boolean)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;></xref>類別，根據提供的參數。"
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "字串值，指定的實體目錄的絕對路徑。"
    - id: isAppRoot
      type: System.Boolean
      description: "布林值，指出虛擬目錄是 Web 應用程式的應用程式根目錄。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  id: '#ctor(System.String,System.Boolean,System.String)'
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.Web.Configuration.VirtualDirectoryMapping&quot;></xref>類別，根據提供的參數。"
  syntax:
    content: public VirtualDirectoryMapping (string physicalDirectory, bool isAppRoot, string configFileBaseName);
    parameters:
    - id: physicalDirectory
      type: System.String
      description: "字串值，指定的實體目錄的絕對路徑。"
    - id: isAppRoot
      type: System.Boolean
      description: "布林值，指出虛擬目錄是 Web 應用程式的應用程式根目錄。"
    - id: configFileBaseName
      type: System.String
      description: "組態檔的名稱。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  id: ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定組態檔的名稱。"
  remarks: "如果未指定組態檔的名稱，則會使用 Web.config。"
  syntax:
    content: public string ConfigFileBaseName { get; set; }
    return:
      type: System.String
      description: "值，指出組態檔的名稱。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "選取的值是 null 或空字串 (&quot;&quot;)。"
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  id: IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指出虛擬目錄是否應視為應用程式根目錄。"
  syntax:
    content: public bool IsAppRoot { get; set; }
    return:
      type: System.Boolean
      description: "值，指出虛擬目錄是否應視為應用程式根目錄。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  id: PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，這個值，指定 Web 應用程式的完整伺服器路徑。"
  syntax:
    content: public string PhysicalDirectory { get; set; }
    return:
      type: System.String
      description: "指出 Web 應用程式的完整伺服器路徑的值。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "選取的值無效，或內部安全性驗證失敗。"
  platform:
  - net462
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  id: VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  langs:
  - csharp
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得值，指定相對於網站根目錄的虛擬目錄。"
  syntax:
    content: public string VirtualDirectory { get; }
    return:
      type: System.String
      description: "值，指出相對的 Web 應用程式目錄。"
  overload: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor(System.String,System.Boolean,System.String)
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping(String,Boolean,String)
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectoryMapping(String,Boolean,String)
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
  fullName: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
  fullName: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
  fullName: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.#ctor*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectoryMapping
  nameWithType: VirtualDirectoryMapping.VirtualDirectoryMapping
- uid: System.Web.Configuration.VirtualDirectoryMapping.ConfigFileBaseName*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: ConfigFileBaseName
  nameWithType: VirtualDirectoryMapping.ConfigFileBaseName
- uid: System.Web.Configuration.VirtualDirectoryMapping.IsAppRoot*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: IsAppRoot
  nameWithType: VirtualDirectoryMapping.IsAppRoot
- uid: System.Web.Configuration.VirtualDirectoryMapping.PhysicalDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: PhysicalDirectory
  nameWithType: VirtualDirectoryMapping.PhysicalDirectory
- uid: System.Web.Configuration.VirtualDirectoryMapping.VirtualDirectory*
  parent: System.Web.Configuration.VirtualDirectoryMapping
  isExternal: false
  name: VirtualDirectory
  nameWithType: VirtualDirectoryMapping.VirtualDirectory
