### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpHandlersSection
  id: HttpHandlersSection
  children:
  - System.Web.Configuration.HttpHandlersSection.#ctor
  - System.Web.Configuration.HttpHandlersSection.Handlers
  - System.Web.Configuration.HttpHandlersSection.Properties
  langs:
  - csharp
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection
  fullName: System.Web.Configuration.HttpHandlersSection
  type: Class
  summary: "設定 Web 應用程式的 HTTP 處理常式。 這個類別無法被繼承。"
  remarks: "HttpHandlersSection 類別可用來以程式設計方式存取和修改`httpHandlers`組態檔區段。 此類型屬於的群組，其中包含<xref:System.Web.Configuration.HttpHandlerAction>和<xref:System.Web.Configuration.HttpHandlerActionCollection>型別。</xref:System.Web.Configuration.HttpHandlerActionCollection> </xref:System.Web.Configuration.HttpHandlerAction>      > [!NOTE] > HttpHandlersSection 可以讀取和寫入資訊的相關區段的<xref:System.Configuration.SectionInformation.AllowDefinition%2A>區段屬性，其值為<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>根據組態檔"
  example:
  - "The following code example shows how to use the HttpHandlersSection class to access the `httpHandlers` section of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#1](~/add/codesnippet/csharp/t-system.web.configurati_16_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#1](~/add/codesnippet/visualbasic/t-system.web.configurati_16_1.vb)]  \n  \n The following configuration excerpt shows how to specify values declaratively for the `httpHandlers` section.  \n  \n```  \n<httpHandlers>  \n  <add path=\"Calculator.custom\"  \n    type=\"Samples.Aspnet.SystemWebConfiguration.Calculator, CalculatorHandler\"  \n    verb=\"GET\" validate=\"false\" />  \n</httpHandlers>   \n```"
  syntax:
    content: 'public sealed class HttpHandlersSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.HttpHandlersSection&quot;></xref>類別。"
  remarks: "HttpHandlersSection 建構函式不是直接從您的程式碼使用。 它會呼叫 ASP.NET 組態系統。 取得執行個體<xref:System.Web.Configuration.HttpHandlersSection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.HttpHandlersSection>"
  syntax:
    content: public HttpHandlersSection ();
    parameters: []
  overload: System.Web.Configuration.HttpHandlersSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  id: Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得<xref href=&quot;System.Web.Configuration.HttpHandlerActionCollection&quot;></xref>集合<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>所包含之物件<xref href=&quot;System.Web.Configuration.HttpHandlersSection&quot;></xref>物件。"
  remarks: "這個方法所傳回的處理常式屬性集合不是指任何基礎的組態檔中的實際項目。 它是<xref:System.Web.Configuration>建構，可讓您輕鬆存取它所包含的處理常式。</xref:System.Web.Configuration> 這是常見的模式來處理組態檔的項目。"
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.HttpHandlerAction> handlers.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#4](~/add/codesnippet/csharp/p-system.web.configurati_121_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#4](~/add/codesnippet/visualbasic/p-system.web.configurati_121_1.vb)]"
  syntax:
    content: public System.Web.Configuration.HttpHandlerActionCollection Handlers { get; }
    return:
      type: System.Web.Configuration.HttpHandlerActionCollection
      description: "<xref href=&quot;System.Web.Configuration.HttpHandlerActionCollection&quot;> </xref>包含<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>物件或處理常式。"
  overload: System.Web.Configuration.HttpHandlersSection.Handlers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  id: Properties
  parent: System.Web.Configuration.HttpHandlersSection
  langs:
  - csharp
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.HttpHandlersSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection()
  nameWithType: HttpHandlersSection.HttpHandlersSection()
  fullName: System.Web.Configuration.HttpHandlersSection.HttpHandlersSection()
- uid: System.Web.Configuration.HttpHandlersSection.Handlers
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
  fullName: System.Web.Configuration.HttpHandlersSection.Handlers
- uid: System.Web.Configuration.HttpHandlerActionCollection
  parent: System.Web.Configuration
  isExternal: false
  name: HttpHandlerActionCollection
  nameWithType: HttpHandlerActionCollection
  fullName: System.Web.Configuration.HttpHandlerActionCollection
- uid: System.Web.Configuration.HttpHandlersSection.Properties
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
  fullName: System.Web.Configuration.HttpHandlersSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpHandlersSection.#ctor*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: HttpHandlersSection
  nameWithType: HttpHandlersSection.HttpHandlersSection
- uid: System.Web.Configuration.HttpHandlersSection.Handlers*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Handlers
  nameWithType: HttpHandlersSection.Handlers
- uid: System.Web.Configuration.HttpHandlersSection.Properties*
  parent: System.Web.Configuration.HttpHandlersSection
  isExternal: false
  name: Properties
  nameWithType: HttpHandlersSection.Properties
