### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementProperty
  id: ConfigurationElementProperty
  children:
  - System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  - System.Configuration.ConfigurationElementProperty.Validator
  langs:
  - csharp
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
  type: Class
  summary: "指定之組態項目的屬性。 這個類別無法被繼承。"
  remarks: "這個類別可以用來驗證組態項目屬性。 此外，使用這個類別搭配<xref:System.Configuration.ConfigurationElement>類別。</xref:System.Configuration.ConfigurationElement>"
  syntax:
    content: public sealed class ConfigurationElementProperty
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  id: '#ctor(System.Configuration.ConfigurationValidatorBase)'
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.ConfigurationElementProperty&quot;></xref>類別，根據提供的參數。"
  syntax:
    content: public ConfigurationElementProperty (System.Configuration.ConfigurationValidatorBase validator);
    parameters:
    - id: validator
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref> object."
  overload: System.Configuration.ConfigurationElementProperty.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>validator</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementProperty.Validator
  id: Validator
  parent: System.Configuration.ConfigurationElementProperty
  langs:
  - csharp
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "取得<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref>用來驗證物件<xref href=&quot;System.Configuration.ConfigurationElementProperty&quot;></xref>物件。"
  syntax:
    content: public System.Configuration.ConfigurationValidatorBase Validator { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref> object."
  overload: System.Configuration.ConfigurationElementProperty.Validator*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationElementProperty.#ctor(System.Configuration.ConfigurationValidatorBase)
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: ConfigurationElementProperty(ConfigurationValidatorBase)
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
  fullName: System.Configuration.ConfigurationElementProperty.ConfigurationElementProperty(ConfigurationValidatorBase)
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationElementProperty.Validator
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
  fullName: System.Configuration.ConfigurationElementProperty.Validator
- uid: System.Configuration.ConfigurationElementProperty.#ctor*
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty.ConfigurationElementProperty
- uid: System.Configuration.ConfigurationElementProperty.Validator*
  parent: System.Configuration.ConfigurationElementProperty
  isExternal: false
  name: Validator
  nameWithType: ConfigurationElementProperty.Validator
