### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.AudienceUriElement
  id: AudienceUriElement
  children:
  - System.IdentityModel.Configuration.AudienceUriElement.#ctor
  - System.IdentityModel.Configuration.AudienceUriElement.Properties
  - System.IdentityModel.Configuration.AudienceUriElement.Value
  langs:
  - csharp
  name: AudienceUriElement
  nameWithType: AudienceUriElement
  fullName: System.IdentityModel.Configuration.AudienceUriElement
  type: Class
  summary: "代表對象 URI 值設定之下<xref uid=&quot;langword_csharp_&lt;audienceUris&gt;&quot; name=&quot;&lt;audienceUris&gt;&quot; href=&quot;&quot;></xref>項目。"
  remarks: "`<audienceUris>`項目由<xref:System.IdentityModel.Configuration.AudienceUriElementCollection>類別，它會指定識別的信賴憑證者的合作對象的 uri 集合。</xref:System.IdentityModel.Configuration.AudienceUriElementCollection> 除非它們適用其中一個允許的 audience Uri，將不會接受權杖。       AudienceUriElement 類別代表單一的對象已加入至集合的 URI 值。"
  syntax:
    content: 'public sealed class AudienceUriElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: AudienceUriElement()
  nameWithType: AudienceUriElement.AudienceUriElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElement.AudienceUriElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.IdentityModel.Configuration.AudienceUriElement&quot;></xref>類別。"
  syntax:
    content: public AudienceUriElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.AudienceUriElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: Properties
  nameWithType: AudienceUriElement.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.IdentityModel.Configuration.AudienceUriElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value
  id: Value
  parent: System.IdentityModel.Configuration.AudienceUriElement
  langs:
  - csharp
  name: Value
  nameWithType: AudienceUriElement.Value
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Value
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "取得或設定對象的 URI。"
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "適用對象的 URI。"
  overload: System.IdentityModel.Configuration.AudienceUriElement.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: AudienceUriElement()
  nameWithType: AudienceUriElement.AudienceUriElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElement.AudienceUriElement()
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElement.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Value
  nameWithType: AudienceUriElement.Value
  fullName: System.IdentityModel.Configuration.AudienceUriElement.Value
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.AudienceUriElement.#ctor*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: AudienceUriElement
  nameWithType: AudienceUriElement.AudienceUriElement
- uid: System.IdentityModel.Configuration.AudienceUriElement.Properties*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElement.Properties
- uid: System.IdentityModel.Configuration.AudienceUriElement.Value*
  parent: System.IdentityModel.Configuration.AudienceUriElement
  isExternal: false
  name: Value
  nameWithType: AudienceUriElement.Value
