### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PassportAuthentication
  id: PassportAuthentication
  children:
  - System.Web.Configuration.PassportAuthentication.#ctor
  - System.Web.Configuration.PassportAuthentication.ElementProperty
  - System.Web.Configuration.PassportAuthentication.Properties
  - System.Web.Configuration.PassportAuthentication.RedirectUrl
  langs:
  - csharp
  name: PassportAuthentication
  nameWithType: PassportAuthentication
  fullName: System.Web.Configuration.PassportAuthentication
  type: Class
  summary: "在 ASP.NET 應用程式設定 Passport 驗證。"
  remarks: "PassportAuthentication 類別可讓您存取，並由 Machine.config 或 Web.config 組態檔中設定節點`passport`標記。       此類型屬於的群組，其中包含<xref:System.Web.Configuration.AuthenticationSection>， <xref:System.Web.Configuration.FormsAuthenticationConfiguration>，和<xref:System.Web.Configuration.AuthenticationMode>型別。</xref:System.Web.Configuration.AuthenticationMode> </xref:System.Web.Configuration.FormsAuthenticationConfiguration> </xref:System.Web.Configuration.AuthenticationSection>      > [!NOTE] > PassportAuthentication 類別可將資訊寫入至位於機器、 網站或應用程式層級的組態檔的相關區段。 任何嘗試寫入階層中不同層級的組態檔中將會導致由剖析器產生的錯誤訊息。 這個類別可用來讀取階層架構中的任何層級的組態資訊。"
  example:
  - "The following code example shows how to obtain the PassportAuthentication object from the configuration file of an existing Web application. Also shown is a configuration example.  \n  \n```  \n<authentication>  \n  <passport redirectUrl=\"Login.aspx\"/>  \n</authentication>  \n```  \n  \n [!code-cs[System.Web.Configuration.PassportAuthentication#1](~/add/codesnippet/csharp/t-system.web.configurati_49_1.cs)]\n [!code-vb[System.Web.Configuration.PassportAuthentication#1](~/add/codesnippet/visualbasic/t-system.web.configurati_49_1.vb)]"
  syntax:
    content: >-
      [System.Obsolete("This type is obsolete. The Passport authentication product is no longer supported and has been superseded by Live ID.")]

      public sealed class PassportAuthentication : System.Configuration.ConfigurationElement
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.PassportAuthentication.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.PassportAuthentication
  langs:
  - csharp
  name: PassportAuthentication()
  nameWithType: PassportAuthentication.PassportAuthentication()
  fullName: System.Web.Configuration.PassportAuthentication.PassportAuthentication()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.PassportAuthentication&quot;></xref>類別。"
  remarks: ''
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.PassportAuthentication> object.  \n  \n [!code-cs[System.Web.Configuration.PassportAuthentication#2](~/add/codesnippet/csharp/m-system.web.configurati_42_1.cs)]\n [!code-vb[System.Web.Configuration.PassportAuthentication#2](~/add/codesnippet/visualbasic/m-system.web.configurati_42_1.vb)]"
  syntax:
    content: public PassportAuthentication ();
    parameters: []
  overload: System.Web.Configuration.PassportAuthentication.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PassportAuthentication.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.PassportAuthentication
  langs:
  - csharp
  name: ElementProperty
  nameWithType: PassportAuthentication.ElementProperty
  fullName: System.Web.Configuration.PassportAuthentication.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: "即將加入。"
  overload: System.Web.Configuration.PassportAuthentication.ElementProperty*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PassportAuthentication.Properties
  id: Properties
  parent: System.Web.Configuration.PassportAuthentication
  langs:
  - csharp
  name: Properties
  nameWithType: PassportAuthentication.Properties
  fullName: System.Web.Configuration.PassportAuthentication.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.PassportAuthentication.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PassportAuthentication.RedirectUrl
  id: RedirectUrl
  parent: System.Web.Configuration.PassportAuthentication
  langs:
  - csharp
  name: RedirectUrl
  nameWithType: PassportAuthentication.RedirectUrl
  fullName: System.Web.Configuration.PassportAuthentication.RedirectUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定將要求重新導向的 URL。"
  remarks: "RedirectUrl 指定的要求必須重新導向如果 Passport 驗證需要，而使用者未登使用 Passport 驗證頁面的 URL。"
  example:
  - "The following code example shows how to use the RedirectUrl property.  \n  \n [!code-cs[System.Web.Configuration.PassportAuthentication#3](~/add/codesnippet/csharp/p-system.web.configurati_279_1.cs)]\n [!code-vb[System.Web.Configuration.PassportAuthentication#3](~/add/codesnippet/visualbasic/p-system.web.configurati_279_1.vb)]"
  syntax:
    content: public string RedirectUrl { get; set; }
    return:
      type: System.String
      description: "將要求重新導向網頁的 URL。"
  overload: System.Web.Configuration.PassportAuthentication.RedirectUrl*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.PassportAuthentication.#ctor
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: PassportAuthentication()
  nameWithType: PassportAuthentication.PassportAuthentication()
  fullName: System.Web.Configuration.PassportAuthentication.PassportAuthentication()
- uid: System.Web.Configuration.PassportAuthentication.ElementProperty
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: ElementProperty
  nameWithType: PassportAuthentication.ElementProperty
  fullName: System.Web.Configuration.PassportAuthentication.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.PassportAuthentication.Properties
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: Properties
  nameWithType: PassportAuthentication.Properties
  fullName: System.Web.Configuration.PassportAuthentication.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PassportAuthentication.RedirectUrl
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: RedirectUrl
  nameWithType: PassportAuthentication.RedirectUrl
  fullName: System.Web.Configuration.PassportAuthentication.RedirectUrl
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.PassportAuthentication.#ctor*
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: PassportAuthentication
  nameWithType: PassportAuthentication.PassportAuthentication
- uid: System.Web.Configuration.PassportAuthentication.ElementProperty*
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: ElementProperty
  nameWithType: PassportAuthentication.ElementProperty
- uid: System.Web.Configuration.PassportAuthentication.Properties*
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: Properties
  nameWithType: PassportAuthentication.Properties
- uid: System.Web.Configuration.PassportAuthentication.RedirectUrl*
  parent: System.Web.Configuration.PassportAuthentication
  isExternal: false
  name: RedirectUrl
  nameWithType: PassportAuthentication.RedirectUrl
