### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelLogLevel
  id: ProcessModelLogLevel
  children:
  - System.Web.Configuration.ProcessModelLogLevel.All
  - System.Web.Configuration.ProcessModelLogLevel.Errors
  - System.Web.Configuration.ProcessModelLogLevel.None
  langs:
  - csharp
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
  type: Enum
  summary: "指定要在事件記錄檔記錄的事件類型。"
  remarks: "ProcessModelLogLevel 列舉型別包含使用當您設定的值<xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>屬性。</xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>       預設值是錯誤。"
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/csharp/t-system.web.configurati_95_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/visualbasic/t-system.web.configurati_95_1.vb)]"
  syntax:
    content: public enum ProcessModelLogLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  id: All
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定也會記錄所有的處理程序事件。 這個欄位是常數。"
  remarks: "當您想要瀏覽應用程式可能發生的不含任何篩選條件的可能錯誤，請使用此選項。 建置和偵錯階段期間，這個選項非常有用。"
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  id: Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定記錄未預期的關機、 記憶體限制的關機和死結關機。 這個欄位是常數。"
  remarks: "這是預設值。"
  syntax:
    content: Errors
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定也會記錄任何事件。 這個欄位是常數。"
  remarks: "您可以使用此選項來測試和部署應用程式。"
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
- uid: System.Web.Configuration.ProcessModelLogLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
