### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ClientTargetSection
  id: ClientTargetSection
  children:
  - System.Web.Configuration.ClientTargetSection.#ctor
  - System.Web.Configuration.ClientTargetSection.ClientTargets
  - System.Web.Configuration.ClientTargetSection.Properties
  langs:
  - csharp
  name: ClientTargetSection
  nameWithType: ClientTargetSection
  fullName: System.Web.Configuration.ClientTargetSection
  type: Class
  summary: "設定<xref uid=&quot;langword_csharp_clientTarget&quot; name=&quot;clientTarget&quot; href=&quot;&quot;> </xref> > 一節。 這個類別無法被繼承。"
  remarks: "ClientTargetSection 類別可用來以程式設計方式存取和修改`clientTarget`組態檔區段。 它所屬的群組，其中包含的<xref:System.Web.Configuration.ClientTargetCollection>類別和<xref:System.Web.Configuration.ClientTarget>類別。</xref:System.Web.Configuration.ClientTarget> </xref:System.Web.Configuration.ClientTargetCollection>       ClientTargetSection 類別包含<xref:System.Web.Configuration.ClientTarget>定義成對的別名和相關聯的目標使用者代理程式的 asp.net 伺服器控制項應該轉譯其內容的物件。</xref:System.Web.Configuration.ClientTarget>"
  example:
  - "This section provides two code examples. The first displays a declarative representation of the ClientTargetSection class and also demonstrates how to declaratively specify values for several properties of the <xref:System.Web.Configuration.ClientTarget> class. The second shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file. You use this object to access the <xref:System.Web.Configuration.ClientTarget> objects it contains.  \n  \n The following code example shows how to declaratively specify values for several properties of the <xref:System.Web.Configuration.ClientTarget> class.  \n  \n```  \n<clientTarget>  \n  <add alias=  \n    \"uplevel\" userAgent=\"Mozilla/5.0 (compatible;MSIE 6.0;Windows NT 5.1)\"/>  \n  <add alias=\"downlevel\" userAgent=\"Generic Downlevel\"/>  \n</clientTarget>  \n```  \n  \n The following code example shows how to obtain the <xref:System.Web.Configuration.ClientTargetCollection> object from the configuration file  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/visualbasic/t-system.web.configurati_24_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#1](~/add/codesnippet/csharp/t-system.web.configurati_24_1.cs)]"
  syntax:
    content: 'public sealed class ClientTargetSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ClientTargetSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: ClientTargetSection()
  nameWithType: ClientTargetSection.ClientTargetSection()
  fullName: System.Web.Configuration.ClientTargetSection.ClientTargetSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.ClientTargetSection&quot;></xref>類別。"
  remarks: "ASP.NET 組態系統會呼叫這個建構函式，並不是直接從您的程式碼使用。 您可以取得的執行個體<xref:System.Web.Configuration.ClientTargetSection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.ClientTargetSection>"
  syntax:
    content: public ClientTargetSection ();
    parameters: []
  overload: System.Web.Configuration.ClientTargetSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets
  id: ClientTargets
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
  fullName: System.Web.Configuration.ClientTargetSection.ClientTargets
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得集合<xref href=&quot;System.Web.Configuration.ClientTarget&quot;></xref>物件。"
  remarks: "每個<xref:System.Web.Configuration.ClientTarget>物件包含用來識別用戶端瀏覽器中，也稱為使用者代理程式的兩個屬性。</xref:System.Web.Configuration.ClientTarget> 其中一個屬性是與另一個屬性由用戶端瀏覽器相關聯的別名。 ASP.NET 會使用此資訊頁面上呈現伺服器控制項。"
  example:
  - "The following code example shows how to get the ClientTargets collection.  \n  \n [!code-vb[System.Web.Configuration.ClientTarget#2](~/add/codesnippet/visualbasic/p-system.web.configurati_60_1.vb)]\n [!code-cs[System.Web.Configuration.ClientTarget#2](~/add/codesnippet/csharp/p-system.web.configurati_60_1.cs)]"
  syntax:
    content: public System.Web.Configuration.ClientTargetCollection ClientTargets { get; }
    return:
      type: System.Web.Configuration.ClientTargetCollection
      description: "A <xref href=&quot;System.Web.Configuration.ClientTargetCollection&quot;> </xref>包含<xref href=&quot;System.Web.Configuration.ClientTarget&quot;></xref>物件。"
  overload: System.Web.Configuration.ClientTargetSection.ClientTargets*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ClientTargetSection.Properties
  id: Properties
  parent: System.Web.Configuration.ClientTargetSection
  langs:
  - csharp
  name: Properties
  nameWithType: ClientTargetSection.Properties
  fullName: System.Web.Configuration.ClientTargetSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.ClientTargetSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ClientTargetSection.#ctor
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargetSection()
  nameWithType: ClientTargetSection.ClientTargetSection()
  fullName: System.Web.Configuration.ClientTargetSection.ClientTargetSection()
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
  fullName: System.Web.Configuration.ClientTargetSection.ClientTargets
- uid: System.Web.Configuration.ClientTargetCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ClientTargetCollection
  nameWithType: ClientTargetCollection
  fullName: System.Web.Configuration.ClientTargetCollection
- uid: System.Web.Configuration.ClientTargetSection.Properties
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: Properties
  nameWithType: ClientTargetSection.Properties
  fullName: System.Web.Configuration.ClientTargetSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ClientTargetSection.#ctor*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargetSection
  nameWithType: ClientTargetSection.ClientTargetSection
- uid: System.Web.Configuration.ClientTargetSection.ClientTargets*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: ClientTargets
  nameWithType: ClientTargetSection.ClientTargets
- uid: System.Web.Configuration.ClientTargetSection.Properties*
  parent: System.Web.Configuration.ClientTargetSection
  isExternal: false
  name: Properties
  nameWithType: ClientTargetSection.Properties
