### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProvidersHelper
  id: ProvidersHelper
  children:
  - System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  - System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  langs:
  - csharp
  name: ProvidersHelper
  nameWithType: ProvidersHelper
  fullName: System.Web.Configuration.ProvidersHelper
  type: Class
  summary: "提供方法來建立提供者執行個體中，針對單一或批次中。"
  syntax:
    content: public static class ProvidersHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  id: InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  langs:
  - csharp
  name: InstantiateProvider(ProviderSettings,Type)
  nameWithType: ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化並傳回單一提供者的指定型別使用提供的設定。"
  syntax:
    content: public static System.Configuration.Provider.ProviderBase InstantiateProvider (System.Configuration.ProviderSettings providerSettings, Type providerType);
    parameters:
    - id: providerSettings
      type: System.Configuration.ProviderSettings
      description: "要傳遞給提供者在初始化時的設定。"
    - id: providerType
      type: System.Type
      description: "<xref:System.Type>初始化提供者。</xref:System.Type>"
    return:
      type: System.Configuration.Provider.ProviderBase
      description: "使用提供的設定給定型別的新的提供者。"
  overload: System.Web.Configuration.ProvidersHelper.InstantiateProvider*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The provider type defined in configuration was <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref> or an empty string (\"\").  \n  \n \\- or -  \n  \n The provider type defined in configuration is not compatible with the type used by the feature that is attempting to create a new instance of the provider."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The provider threw an exception while it was being initialized.  \n  \n \\- or -  \n  \n An error occurred while attempting to resolve a <xref:System.Type> instance for the provider specified in <code>providerSettings</code>."
  platform:
  - net462
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  id: InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  langs:
  - csharp
  name: InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  nameWithType: ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "使用提供的設定指定之類型的提供者的集合初始化。"
  remarks: "這個方法會呼叫<xref:System.Web.Configuration.ProvidersHelper.InstantiateProvider%2A>方法，以及該方法所擲回任何例外狀況會反昇透過 InstantiateProviders 方法。</xref:System.Web.Configuration.ProvidersHelper.InstantiateProvider%2A>"
  syntax:
    content: public static void InstantiateProviders (System.Configuration.ProviderSettingsCollection configProviders, System.Configuration.Provider.ProviderCollection providers, Type providerType);
    parameters:
    - id: configProviders
      type: System.Configuration.ProviderSettingsCollection
      description: "要傳遞給提供者在初始化時設定的集合。"
    - id: providers
      type: System.Configuration.Provider.ProviderCollection
      description: "用來包含初始化提供者方法傳回後的集合。"
    - id: providerType
      type: System.Type
      description: "<xref:System.Type>初始化提供者。</xref:System.Type>"
  overload: System.Web.Configuration.ProvidersHelper.InstantiateProviders*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider(System.Configuration.ProviderSettings,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProvider(ProviderSettings,Type)
  nameWithType: ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProvider(ProviderSettings,Type)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProviderSettings
  parent: System.Configuration
  isExternal: false
  name: ProviderSettings
  nameWithType: ProviderSettings
  fullName: System.Configuration.ProviderSettings
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders(System.Configuration.ProviderSettingsCollection,System.Configuration.Provider.ProviderCollection,System.Type)
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  nameWithType: ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
  fullName: System.Web.Configuration.ProvidersHelper.InstantiateProviders(ProviderSettingsCollection,ProviderCollection,Type)
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Configuration.Provider.ProviderCollection
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderCollection
  nameWithType: ProviderCollection
  fullName: System.Configuration.Provider.ProviderCollection
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProvider*
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProvider
  nameWithType: ProvidersHelper.InstantiateProvider
- uid: System.Web.Configuration.ProvidersHelper.InstantiateProviders*
  parent: System.Web.Configuration.ProvidersHelper
  isExternal: false
  name: InstantiateProviders
  nameWithType: ProvidersHelper.InstantiateProviders
