### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingSectionGroup
  id: ScriptingSectionGroup
  children:
  - System.Web.Configuration.ScriptingSectionGroup.#ctor
  - System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  - System.Web.Configuration.ScriptingSectionGroup.WebServices
  langs:
  - csharp
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup
  fullName: System.Web.Configuration.ScriptingSectionGroup
  type: Class
  summary: "表示指令碼設定的組態區段。 這個類別無法被繼承。"
  remarks: "以程式設計方式設定和擷取的值使用 ScriptingSectionGroup 類別`scripting`組態檔區段。"
  syntax:
    content: 'public sealed class ScriptingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.ScriptingSectionGroup&quot;></xref>類別。"
  syntax:
    content: public ScriptingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  id: ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得<xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;></xref>衍生自目前的系統設定的物件。"
  remarks: "使用`ScriptingScriptResourceHandler`組態區段，以設定指令碼的檔案是否為內嵌隨著資源的壓縮和快取。 您可以啟用或停用壓縮和快取使用<xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>和<xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A>屬性。</xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching%2A> </xref:System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression%2A>"
  syntax:
    content: public System.Web.Configuration.ScriptingScriptResourceHandlerSection ScriptResourceHandler { get; }
    return:
      type: System.Web.Configuration.ScriptingScriptResourceHandlerSection
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  id: WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  langs:
  - csharp
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得<xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;></xref>衍生自目前的系統設定的物件。"
  syntax:
    content: public System.Web.Configuration.ScriptingWebServicesSectionGroup WebServices { get; }
    return:
      type: System.Web.Configuration.ScriptingWebServicesSectionGroup
      description: "A <xref href=&quot;System.Web.Configuration.ScriptingWebServicesSectionGroup&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup()
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup()
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptingSectionGroup()
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
  fullName: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
  fullName: System.Web.Configuration.ScriptingSectionGroup.WebServices
- uid: System.Web.Configuration.ScriptingWebServicesSectionGroup
  parent: System.Web.Configuration
  isExternal: false
  name: ScriptingWebServicesSectionGroup
  nameWithType: ScriptingWebServicesSectionGroup
  fullName: System.Web.Configuration.ScriptingWebServicesSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.#ctor*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptingSectionGroup
  nameWithType: ScriptingSectionGroup.ScriptingSectionGroup
- uid: System.Web.Configuration.ScriptingSectionGroup.ScriptResourceHandler*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: ScriptResourceHandler
  nameWithType: ScriptingSectionGroup.ScriptResourceHandler
- uid: System.Web.Configuration.ScriptingSectionGroup.WebServices*
  parent: System.Web.Configuration.ScriptingSectionGroup
  isExternal: false
  name: WebServices
  nameWithType: ScriptingSectionGroup.WebServices
