### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetMsmqSecurity
  id: NetMsmqSecurity
  children:
  - System.ServiceModel.NetMsmqSecurity.#ctor
  - System.ServiceModel.NetMsmqSecurity.Message
  - System.ServiceModel.NetMsmqSecurity.Mode
  - System.ServiceModel.NetMsmqSecurity.Transport
  langs:
  - csharp
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity
  fullName: System.ServiceModel.NetMsmqSecurity
  type: Class
  summary: "NetMsmqSecurity 類別會封裝，可用的 MSMQ 安全性功能時使用<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  remarks: "會建立此類型的物件建立的執行個體<xref:System.ServiceModel.NetMsmqBinding>繫結。</xref:System.ServiceModel.NetMsmqBinding> 您接著可以使用此物件參考所有相關的各種安全性設定<xref:System.ServiceModel.NetMsmqBinding>繫結。</xref:System.ServiceModel.NetMsmqBinding>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_3_1.cs)]
     [!code-vb[UENetMsmqSecurity#1](~/add/codesnippet/visualbasic/t-system.servicemodel.ne_3_1.vb)]
  syntax:
    content: public sealed class NetMsmqSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.NetMsmqSecurity&quot;></xref>類別。"
  syntax:
    content: public NetMsmqSecurity ();
    parameters: []
  overload: System.ServiceModel.NetMsmqSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Message
  id: Message
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;></xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  remarks: "<xref:System.ServiceModel.MessageSecurityOverMsmq>封裝 SOAP 訊息安全性設定。</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_11_1.cs)]
     [!code-vb[UENetMsmqSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_11_1.vb)]
  syntax:
    content: public System.ServiceModel.MessageSecurityOverMsmq Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverMsmq
      description: "<xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  overload: System.ServiceModel.NetMsmqSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;></xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  remarks: "此屬性會決定關聯之 NetMsmqBinding 所使用的安全性類型。 下列清單描述可接受的值:-**無**-未使用任何安全性。      -**傳輸**-使用傳輸安全性。      -**訊息**-使用以訊息為基礎的安全性。      -**兩者**-使用這兩個訊息型安全性與傳輸安全性。"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_13_1.cs)]
     [!code-vb[UENetMsmqSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_13_1.vb)]
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "<xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  overload: System.ServiceModel.NetMsmqSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "值不是其中一個<xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;></xref>值。"
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  remarks: "這個屬性允許存取 MSMQ 傳輸安全性設定。"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#4](~/add/codesnippet/csharp/p-system.servicemodel.ne_19_1.cs)]
     [!code-vb[UENetMsmqSecurity#4](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_19_1.vb)]
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref>相關聯<xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;></xref>繫結。"
  overload: System.ServiceModel.NetMsmqSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
- uid: System.ServiceModel.NetMsmqSecurity.Message
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverMsmq
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverMsmq
  nameWithType: MessageSecurityOverMsmq
  fullName: System.ServiceModel.MessageSecurityOverMsmq
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.NetMsmqSecurity.#ctor*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity.NetMsmqSecurity
- uid: System.ServiceModel.NetMsmqSecurity.Message*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
- uid: System.ServiceModel.NetMsmqSecurity.Mode*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurity.Transport*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
