### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  id: X509PeerCertificateAuthenticationElement
  children:
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.#ctor
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement)
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode
  - System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  langs:
  - csharp
  name: X509PeerCertificateAuthenticationElement
  nameWithType: X509PeerCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  type: Class
  summary: "表示組態項目，指定對等憑證驗證設定。 這個類別無法被繼承。"
  syntax:
    content: 'public sealed class X509PeerCertificateAuthenticationElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: X509PeerCertificateAuthenticationElement()
  nameWithType: X509PeerCertificateAuthenticationElement.X509PeerCertificateAuthenticationElement()
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.X509PeerCertificateAuthenticationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement&quot;></xref>類別。"
  syntax:
    content: public X509PeerCertificateAuthenticationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode
  id: CertificateValidationMode
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: CertificateValidationMode
  nameWithType: X509PeerCertificateAuthenticationElement.CertificateValidationMode
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得憑證驗證模式。"
  syntax:
    content: public System.ServiceModel.Security.X509CertificateValidationMode CertificateValidationMode { get; set; }
    return:
      type: System.ServiceModel.Security.X509CertificateValidationMode
      description: "憑證驗證模式。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement)
  id: Copy(System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement)
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: Copy(X509PeerCertificateAuthenticationElement)
  nameWithType: X509PeerCertificateAuthenticationElement.Copy(X509PeerCertificateAuthenticationElement)
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy(X509PeerCertificateAuthenticationElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "將指定的組態項目的內容複製到這個組態項目。"
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
      description: "要複製的組態元素。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "組態檔為唯讀。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  id: CustomCertificateValidatorType
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: CustomCertificateValidatorType
  nameWithType: X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定要使用的自訂對等憑證驗證程式的型別。"
  remarks: '[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]提供預設的對等憑證驗證程式，用來驗證對等憑證，針對受信任的人存放區。 它也會驗證憑證鏈結直到有效根。 您可以實作自訂驗證程式指定不同的行為，並使用這個屬性指向自訂的驗證程式。'
  syntax:
    content: public string CustomCertificateValidatorType { get; set; }
    return:
      type: System.String
      description: "型別<xref href=&quot;System.IdentityModel.Selectors.X509CertificateValidator&quot;></xref>使用。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509PeerCertificateAuthenticationElement.Properties
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode
  id: RevocationMode
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: RevocationMode
  nameWithType: X509PeerCertificateAuthenticationElement.RevocationMode
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定憑證撤銷模式。"
  remarks: "系統會驗證，對等憑證尚未被撤銷查閱撤銷的憑證清單中。 藉由線上檢查或是針對快取的撤銷清單，可以執行這項檢查。 撤銷檢查可以關閉這個屬性設定為<xref:System.Security.Cryptography.X509Certificates.X509RevocationMode>.</xref:System.Security.Cryptography.X509Certificates.X509RevocationMode>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509RevocationMode RevocationMode { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509RevocationMode
      description: "憑證撤銷模式。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  id: TrustedStoreLocation
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  langs:
  - csharp
  name: TrustedStoreLocation
  nameWithType: X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定驗證對等憑證的受信任存放區位置。"
  remarks: '[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]安全性系統會驗證<xref:System.Security.Cryptography.X509Certificates.StoreLocation>.</xref:System.Security.Cryptography.X509Certificates.StoreLocation>針對對等憑證 使用這個屬性指定的存放區位置。'
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation TrustedStoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "對等憑證驗證受信任存放區位置。"
  overload: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.#ctor
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: X509PeerCertificateAuthenticationElement()
  nameWithType: X509PeerCertificateAuthenticationElement.X509PeerCertificateAuthenticationElement()
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.X509PeerCertificateAuthenticationElement()
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: CertificateValidationMode
  nameWithType: X509PeerCertificateAuthenticationElement.CertificateValidationMode
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode
- uid: System.ServiceModel.Security.X509CertificateValidationMode
  parent: System.ServiceModel.Security
  isExternal: true
  name: X509CertificateValidationMode
  nameWithType: X509CertificateValidationMode
  fullName: System.ServiceModel.Security.X509CertificateValidationMode
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy(System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement)
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: Copy(X509PeerCertificateAuthenticationElement)
  nameWithType: X509PeerCertificateAuthenticationElement.Copy(X509PeerCertificateAuthenticationElement)
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy(X509PeerCertificateAuthenticationElement)
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509PeerCertificateAuthenticationElement
  nameWithType: X509PeerCertificateAuthenticationElement
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: CustomCertificateValidatorType
  nameWithType: X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: Properties
  nameWithType: X509PeerCertificateAuthenticationElement.Properties
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: RevocationMode
  nameWithType: X509PeerCertificateAuthenticationElement.RevocationMode
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode
- uid: System.Security.Cryptography.X509Certificates.X509RevocationMode
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509RevocationMode
  nameWithType: X509RevocationMode
  fullName: System.Security.Cryptography.X509Certificates.X509RevocationMode
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: TrustedStoreLocation
  nameWithType: X509PeerCertificateAuthenticationElement.TrustedStoreLocation
  fullName: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.#ctor*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: X509PeerCertificateAuthenticationElement
  nameWithType: X509PeerCertificateAuthenticationElement.X509PeerCertificateAuthenticationElement
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CertificateValidationMode*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: CertificateValidationMode
  nameWithType: X509PeerCertificateAuthenticationElement.CertificateValidationMode
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Copy*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: Copy
  nameWithType: X509PeerCertificateAuthenticationElement.Copy
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: CustomCertificateValidatorType
  nameWithType: X509PeerCertificateAuthenticationElement.CustomCertificateValidatorType
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.Properties*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: Properties
  nameWithType: X509PeerCertificateAuthenticationElement.Properties
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.RevocationMode*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: RevocationMode
  nameWithType: X509PeerCertificateAuthenticationElement.RevocationMode
- uid: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement.TrustedStoreLocation*
  parent: System.ServiceModel.Configuration.X509PeerCertificateAuthenticationElement
  isExternal: false
  name: TrustedStoreLocation
  nameWithType: X509PeerCertificateAuthenticationElement.TrustedStoreLocation
