### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsGroupDescriptionAttribute
  id: SettingsGroupDescriptionAttribute
  children:
  - System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsGroupDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute
  fullName: System.Configuration.SettingsGroupDescriptionAttribute
  type: Class
  summary: "提供描述應用程式設定屬性群組的字串。 這個類別無法被繼承。"
  remarks: "應用程式設定類別，衍生自<xref:System.Configuration.ApplicationSettingsBase>，定義一個或多個屬於相同的應用程式屬性群組的內容。</xref:System.Configuration.ApplicationSettingsBase> SettingsGroupDescriptionAttribute 是選擇性屬性，可讓您設定屬性群組提供描述性文字。 此文字被為了協助識別並描述相關聯的屬性群組中的設計階段工具和系統管理的執行階段工具。      > [!NOTE] > 這個屬性只能套用在包裝函式類別層級。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class SettingsGroupDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.SettingsGroupDescriptionAttribute&quot;></xref>類別。"
  remarks: "雖然理論上的最大長度`description`參數受到的上限<xref:System.Int32>，實際限制，取決於可用性和設定提供者，所加諸的配額限制會小很多。</xref:System.Int32>"
  syntax:
    content: public SettingsGroupDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "A<xref:System.String>包含應用程式設定群組的描述性文字。</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "應用程式設定屬性群組的描述性文字。"
  remarks: "描述屬性值是否以設定<xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>建構函式。</xref:System.Configuration.SettingsGroupDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "A<xref:System.String>包含應用程式設定群組的描述性文字。</xref:System.String>"
  overload: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute(String)
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
  fullName: System.Configuration.SettingsGroupDescriptionAttribute.Description
- uid: System.Configuration.SettingsGroupDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: SettingsGroupDescriptionAttribute
  nameWithType: SettingsGroupDescriptionAttribute.SettingsGroupDescriptionAttribute
- uid: System.Configuration.SettingsGroupDescriptionAttribute.Description*
  parent: System.Configuration.SettingsGroupDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsGroupDescriptionAttribute.Description
