### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementElement
  id: ConnectionManagementElement
  children:
  - System.Net.Configuration.ConnectionManagementElement.#ctor
  - System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  - System.Net.Configuration.ConnectionManagementElement.Address
  - System.Net.Configuration.ConnectionManagementElement.MaxConnection
  - System.Net.Configuration.ConnectionManagementElement.Properties
  langs:
  - csharp
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement
  type: Class
  summary: "代表連接至遠端電腦的連線數目上限。 這個類別無法被繼承。"
  remarks: "This class corresponds to the [\\&lt;add\\&gt; Element for connectionManagement (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20connectionManagement%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the maximum number of simultaneous connections to a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;></xref>類別。"
  syntax:
    content: public ConnectionManagementElement ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;></xref>類別具有指定的位址和連線限制資訊。"
  remarks: "這個建構函式設定<xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>屬性`address`和<xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>屬性`maxConnection`。</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> </xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>"
  syntax:
    content: public ConnectionManagementElement (string address, int maxConnection);
    parameters:
    - id: address
      type: System.String
      description: "字串，識別遠端電腦的位址。"
    - id: maxConnection
      type: System.Int32
      description: "識別允許的連線數目上限的整數`address`從本機電腦。"
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  id: Address
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得或設定遠端電腦的位址。"
  remarks: "您可以設定這個屬性使用星號 （*） 來設定預設未指定電腦的連接數目。       這個屬性會識別一個或多個遠端電腦和<xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>屬性會指定本機電腦和遠端電腦之間允許同時連線數目。</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>"
  syntax:
    content: public string Address { get; set; }
    return:
      type: System.String
      description: "包含描述的 IP 位址或 DNS 名稱的規則運算式的字串。"
  overload: System.Net.Configuration.ConnectionManagementElement.Address*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  id: MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得或設定要對遠端電腦的連線數目上限。"
  remarks: "這個屬性會指定本機電腦和遠端電腦之間允許同時連線數目。 使用指定的遠端電腦<xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>屬性。</xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>       每個<xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>是 MaxConnection 屬性 如果應用程式不會變更<xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>預設值，然後 MaxConnection 屬性將套用至整個應用程式網域。</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> 如果只有您的應用程式中執行單一應用程式定義域，MaxConnection 屬性設定為整個應用程式。"
  syntax:
    content: public int MaxConnection { get; set; }
    return:
      type: System.Int32
      description: "指定的連線數目上限的整數。"
  overload: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Net.Configuration.ConnectionManagementElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement.ConnectionManagementElement
- uid: System.Net.Configuration.ConnectionManagementElement.Address*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
