### YamlMime:ManagedReference
items:
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute
  id: RecommendedAsConfigurableAttribute
  children:
  - System.ComponentModel.RecommendedAsConfigurableAttribute.#ctor(System.Boolean)
  - System.ComponentModel.RecommendedAsConfigurableAttribute.Default
  - System.ComponentModel.RecommendedAsConfigurableAttribute.Equals(System.Object)
  - System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode
  - System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute
  - System.ComponentModel.RecommendedAsConfigurableAttribute.No
  - System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  - System.ComponentModel.RecommendedAsConfigurableAttribute.Yes
  langs:
  - csharp
  name: RecommendedAsConfigurableAttribute
  nameWithType: RecommendedAsConfigurableAttribute
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute
  type: Class
  summary: "指定可用來當作應用程式設定屬性。"
  remarks: "以 RecommendedAsConfigurableAttribute 標記的屬性設定為`true`顯示當您展開**ConfigurableProperties**中一行**屬性**視窗。 屬性有任何建議的設定或 RecommendedAsConfigurableAttribute 標記設為`false`未顯示，且不太可能的候選的應用程式設定。 預設值是`false`。       您可以繫結屬性沒有設定 RecommendedAsConfigurableAttribute Visual Studio 中依序按一下省略符號按鈕 （...） 下的**設定**中**屬性**視窗，並從清單中選取適當的屬性。      > [!NOTE] > 您將標記與 RecommendedAsConfigurableAttribute 屬性設定為`true`，這個屬性的值設定為常數成員<xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Yes>.</xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Yes> 針對屬性使用 RecommendedAsConfigurableAttribute 設值標示`false`，值為<xref:System.ComponentModel.RecommendedAsConfigurableAttribute.No>。</xref:System.ComponentModel.RecommendedAsConfigurableAttribute.No> 因此，當您想要檢查您的程式碼中的此屬性的值，您必須指定屬性或<xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Yes?displayProperty=fullName><xref:System.ComponentModel.RecommendedAsConfigurableAttribute.No?displayProperty=fullName>.</xref:System.ComponentModel.RecommendedAsConfigurableAttribute.No?displayProperty=fullName> </xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Yes?displayProperty=fullName>       如需詳細資訊，請參閱[屬性](~/add/includes/ajax-current-ext-md.md)。       。"
  example:
  - "The following example marks a property as usable as an application setting.  \n  \n [!code-cpp[Classic RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/cpp/t-system.componentmodel._10_1.cpp)]\n [!code-vb[Classic RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/visualbasic/t-system.componentmodel._10_1.vb)]\n [!code-cs[Classic RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/csharp/t-system.componentmodel._10_1.cs)]  \n  \n The next example shows how to check the value of the RecommendedAsConfigurableAttribute for `MyProperty`. First the code gets a <xref:System.ComponentModel.PropertyDescriptorCollection> with all the properties for the object. Next it indexes into the <xref:System.ComponentModel.PropertyDescriptorCollection> to get `MyProperty`. Then it returns the attributes for this property and saves them in the attributes variable.  \n  \n This example presents two different ways of checking the value of the RecommendedAsConfigurableAttribute. In the second code fragment, the example calls the <xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Equals%2A> method. In the last code fragment, the example uses the <xref:System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable%2A> property to check the value.  \n  \n [!code-cpp[Classic RecommendedAsConfigurableAttribute Example#2](~/add/codesnippet/cpp/t-system.componentmodel._10_2.cpp)]\n [!code-vb[Classic RecommendedAsConfigurableAttribute Example#2](~/add/codesnippet/visualbasic/t-system.componentmodel._10_2.vb)]\n [!code-cs[Classic RecommendedAsConfigurableAttribute Example#2](~/add/codesnippet/csharp/t-system.componentmodel._10_2.cs)]  \n  \n If you marked a class with the RecommendedAsConfigurableAttribute, use the following code to check the value.  \n  \n [!code-cpp[Classic RecommendedAsConfigurableAttribute Example#3](~/add/codesnippet/cpp/t-system.componentmodel._10_3.cpp)]\n [!code-vb[Classic RecommendedAsConfigurableAttribute Example#3](~/add/codesnippet/visualbasic/t-system.componentmodel._10_3.vb)]\n [!code-cs[Classic RecommendedAsConfigurableAttribute Example#3](~/add/codesnippet/csharp/t-system.componentmodel._10_3.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      [System.Obsolete("Use System.ComponentModel.SettingsBindableAttribute instead to work with the new settings model.")]

      public class RecommendedAsConfigurableAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: RecommendedAsConfigurableAttribute(Boolean)
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute(Boolean)
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute(Boolean)
  type: Constructor
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "初始化的新執行個體<xref href=&quot;System.ComponentModel.RecommendedAsConfigurableAttribute&quot;></xref>類別。"
  remarks: ''
  example:
  - "The following example marks a property as usable as an application setting. This code creates a new <xref:System.ComponentModel.RecommendedAsConfigurableAttribute>, sets its value to <xref:System.ComponentModel.RecommendedAsConfigurableAttribute.Yes?displayProperty=fullName>, and binds it to the property.  \n  \n [!code-vb[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/visualbasic/bdd6c030-1ad6-4039-832c-_1.vb)]\n [!code-cpp[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/cpp/bdd6c030-1ad6-4039-832c-_1.cpp)]\n [!code-cs[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute Example#1](~/add/codesnippet/csharp/bdd6c030-1ad6-4039-832c-_1.cs)]"
  syntax:
    content: public RecommendedAsConfigurableAttribute (bool recommendedAsConfigurable);
    parameters:
    - id: recommendedAsConfigurable
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果這個屬性繫結至屬性可用來當做應用程式設定。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ComponentModel.RecommendedAsConfigurableAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Default
  id: Default
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: Default
  nameWithType: RecommendedAsConfigurableAttribute.Default
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Default
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "指定的預設值為<xref href=&quot;System.ComponentModel.RecommendedAsConfigurableAttribute&quot;> </xref>，也就是<xref href=&quot;System.ComponentModel.RecommendedAsConfigurableAttribute.No&quot;> </xref>。 這<xref uid=&quot;langword_csharp_static&quot; name=&quot;static&quot; href=&quot;&quot;></xref>欄位為唯讀。"
  syntax:
    content: public static readonly System.ComponentModel.RecommendedAsConfigurableAttribute Default;
    return:
      type: System.ComponentModel.RecommendedAsConfigurableAttribute
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: RecommendedAsConfigurableAttribute.Equals(Object)
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals(Object)
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "指出這個執行個體和指定的物件是否相等。"
  syntax:
    content: public override bool Equals (object obj);
    parameters:
    - id: obj
      type: System.Object
      description: "要比較的另一個物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<code> obj </code>等於這個執行個體; 否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode
  id: GetHashCode
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: RecommendedAsConfigurableAttribute.GetHashCode()
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "傳回這個執行個體的雜湊碼。"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "目前的雜湊碼<xref href=&quot;System.ComponentModel.RecommendedAsConfigurableAttribute&quot;> </xref>。"
  overload: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute
  id: IsDefaultAttribute
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: IsDefaultAttribute()
  nameWithType: RecommendedAsConfigurableAttribute.IsDefaultAttribute()
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute()
  type: Method
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "指出這個執行個體的值是否為類別的預設值。"
  syntax:
    content: public override bool IsDefaultAttribute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果這個執行個體是預設屬性的類別。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.No
  id: No
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: No
  nameWithType: RecommendedAsConfigurableAttribute.No
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.No
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "指定的屬性不能當做應用程式設定。 這<xref uid=&quot;langword_csharp_static&quot; name=&quot;static&quot; href=&quot;&quot;></xref>欄位為唯讀。"
  remarks: "這個欄位是此屬性的預設設定。       當您將屬性標記與<xref:System.ComponentModel.RecommendedAsConfigurableAttribute>設`false`，這個屬性的值設定為常數成員不可以。</xref:System.ComponentModel.RecommendedAsConfigurableAttribute> 因此，當您想要檢查屬性是否設定為這個程式碼中的值，您必須指定屬性 [否]。"
  syntax:
    content: public static readonly System.ComponentModel.RecommendedAsConfigurableAttribute No;
    return:
      type: System.ComponentModel.RecommendedAsConfigurableAttribute
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  id: RecommendedAsConfigurable
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: RecommendedAsConfigurable
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  type: Property
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "取得值，指出是否將屬性這個屬性是繫結可用來當做應用程式設定。"
  remarks: ''
  example:
  - "The following example checks to see whether `MyProperty` is bindable. First the code gets the attributes for `MyProperty` by:  \n  \n-   Retrieving a <xref:System.ComponentModel.PropertyDescriptorCollection> with all the properties for the object.  \n  \n-   Indexing into the <xref:System.ComponentModel.PropertyDescriptorCollection> to get `MyProperty`.  \n  \n-   Saving the attributes for this property in the attributes variable.  \n  \n Then the code sets `myAttribute` to the value of the <xref:System.ComponentModel.RecommendedAsConfigurableAttribute> in the <xref:System.ComponentModel.AttributeCollection> and checks whether the property is bindable.  \n  \n [!code-vb[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurable Example#1](~/add/codesnippet/visualbasic/bcb3e1a6-9a5f-4958-883f-_1.vb)]\n [!code-cs[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurable Example#1](~/add/codesnippet/csharp/bcb3e1a6-9a5f-4958-883f-_1.cs)]\n [!code-cpp[Classic RecommendedAsConfigurableAttribute.RecommendedAsConfigurable Example#1](~/add/codesnippet/cpp/bcb3e1a6-9a5f-4958-883f-_1.cpp)]"
  syntax:
    content: public bool RecommendedAsConfigurable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果這個屬性繫結至屬性可用來當做應用程式設定。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable*
  exceptions: []
  platform:
  - net462
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Yes
  id: Yes
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  langs:
  - csharp
  name: Yes
  nameWithType: RecommendedAsConfigurableAttribute.Yes
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Yes
  type: Field
  assemblies:
  - System
  namespace: System.ComponentModel
  summary: "指定可用來當作應用程式設定屬性。 這<xref uid=&quot;langword_csharp_static&quot; name=&quot;static&quot; href=&quot;&quot;></xref>欄位為唯讀。"
  remarks: "當您將屬性標記與<xref:System.ComponentModel.RecommendedAsConfigurableAttribute>設`true`，這個屬性的值設定為常數成員 [是]。</xref:System.ComponentModel.RecommendedAsConfigurableAttribute>       因此，當您想要檢查屬性是否設定為這個程式碼中的值，您必須指定屬性為 [是]。"
  syntax:
    content: public static readonly System.ComponentModel.RecommendedAsConfigurableAttribute Yes;
    return:
      type: System.ComponentModel.RecommendedAsConfigurableAttribute
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.#ctor(System.Boolean)
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: RecommendedAsConfigurableAttribute(Boolean)
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute(Boolean)
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Default
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: Default
  nameWithType: RecommendedAsConfigurableAttribute.Default
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Default
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute
  parent: System.ComponentModel
  isExternal: false
  name: RecommendedAsConfigurableAttribute
  nameWithType: RecommendedAsConfigurableAttribute
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals(System.Object)
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: Equals(Object)
  nameWithType: RecommendedAsConfigurableAttribute.Equals(Object)
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: GetHashCode()
  nameWithType: RecommendedAsConfigurableAttribute.GetHashCode()
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: IsDefaultAttribute()
  nameWithType: RecommendedAsConfigurableAttribute.IsDefaultAttribute()
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute()
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.No
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: No
  nameWithType: RecommendedAsConfigurableAttribute.No
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.No
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: RecommendedAsConfigurable
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Yes
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: Yes
  nameWithType: RecommendedAsConfigurableAttribute.Yes
  fullName: System.ComponentModel.RecommendedAsConfigurableAttribute.Yes
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.#ctor*
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: RecommendedAsConfigurableAttribute
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurableAttribute
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.Equals*
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: Equals
  nameWithType: RecommendedAsConfigurableAttribute.Equals
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.GetHashCode*
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: GetHashCode
  nameWithType: RecommendedAsConfigurableAttribute.GetHashCode
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.IsDefaultAttribute*
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: IsDefaultAttribute
  nameWithType: RecommendedAsConfigurableAttribute.IsDefaultAttribute
- uid: System.ComponentModel.RecommendedAsConfigurableAttribute.RecommendedAsConfigurable*
  parent: System.ComponentModel.RecommendedAsConfigurableAttribute
  isExternal: false
  name: RecommendedAsConfigurable
  nameWithType: RecommendedAsConfigurableAttribute.RecommendedAsConfigurable
