### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsLoadedEventArgs
  id: SettingsLoadedEventArgs
  children:
  - System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  - System.Configuration.SettingsLoadedEventArgs.Provider
  langs:
  - csharp
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs
  fullName: System.Configuration.SettingsLoadedEventArgs
  type: Class
  summary: "提供資料給<xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsLoaded&quot;></xref>事件。"
  remarks: "SettingsLoadedEventArgs 類別提供資料給<xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>設定擷取來自提供者時，就會發生的事件。</xref:System.Configuration.ApplicationSettingsBase.SettingsLoaded>"
  syntax:
    content: 'public class SettingsLoadedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  id: '#ctor(System.Configuration.SettingsProvider)'
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.SettingsLoadedEventArgs&quot;></xref>類別。"
  syntax:
    content: public SettingsLoadedEventArgs (System.Configuration.SettingsProvider provider);
    parameters:
    - id: provider
      type: System.Configuration.SettingsProvider
      description: "A <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref>載入設定的物件。"
  overload: System.Configuration.SettingsLoadedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  id: Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  langs:
  - csharp
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得用來儲存組態設定的設定提供者。"
  syntax:
    content: public System.Configuration.SettingsProvider Provider { get; }
    return:
      type: System.Configuration.SettingsProvider
      description: "設定提供者。"
  overload: System.Configuration.SettingsLoadedEventArgs.Provider*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor(System.Configuration.SettingsProvider)
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs(SettingsProvider)
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
  fullName: System.Configuration.SettingsLoadedEventArgs.SettingsLoadedEventArgs(SettingsProvider)
- uid: System.Configuration.SettingsProvider
  parent: System.Configuration
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
- uid: System.Configuration.SettingsLoadedEventArgs.Provider
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
  fullName: System.Configuration.SettingsLoadedEventArgs.Provider
- uid: System.Configuration.SettingsLoadedEventArgs.#ctor*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: SettingsLoadedEventArgs
  nameWithType: SettingsLoadedEventArgs.SettingsLoadedEventArgs
- uid: System.Configuration.SettingsLoadedEventArgs.Provider*
  parent: System.Configuration.SettingsLoadedEventArgs
  isExternal: false
  name: Provider
  nameWithType: SettingsLoadedEventArgs.Provider
