### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.RegexWorker
  id: RegexWorker
  children:
  - System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.RegexWorker.Item(System.String)
  - System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  langs:
  - csharp
  name: RegexWorker
  nameWithType: RegexWorker
  fullName: System.Web.Configuration.RegexWorker
  type: Class
  summary: "在執行階段於內部使用<xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;></xref>和<xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;></xref>剖析要求資料，並識別瀏覽器。"
  syntax:
    content: public class RegexWorker
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  id: '#ctor(System.Web.HttpBrowserCapabilities)'
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.Web.Configuration.RegexWorker&quot;> </xref>。"
  syntax:
    content: public RegexWorker (System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "<xref href=&quot;System.Web.Configuration.HttpCapabilitiesBase&quot;> </xref>設定的物件。"
  overload: System.Web.Configuration.RegexWorker.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  id: Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "這個類別的存取子。"
  syntax:
    content: public string this[string key] { get; }
    parameters:
    - id: key
      type: System.String
      description: "指定的索引鍵。"
    return:
      type: System.String
      description: "指定相關聯的內部值<code>key</code>。"
  overload: System.Web.Configuration.RegexWorker.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  id: ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  langs:
  - csharp
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在執行階段於內部使用，以判斷指定的要求標頭值是否符合任何功能的瀏覽器的內部集合。"
  syntax:
    content: public bool ProcessRegex (string target, string regexExpression);
    parameters:
    - id: target
      type: System.String
      description: "來自的瀏覽器的內部集合的功能值。"
    - id: regexExpression
      type: System.String
      description: "指定的要求標頭值。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果指定的要求標頭值符合任何瀏覽器; 內部集合的功能否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.RegexWorker.ProcessRegex*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.RegexWorker.#ctor(System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker(HttpBrowserCapabilities)
  nameWithType: RegexWorker.RegexWorker(HttpBrowserCapabilities)
  fullName: System.Web.Configuration.RegexWorker.RegexWorker(HttpBrowserCapabilities)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.RegexWorker.Item(System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item(String)
  nameWithType: RegexWorker.Item(String)
  fullName: System.Web.Configuration.RegexWorker.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.RegexWorker.ProcessRegex(System.String,System.String)
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex(String,String)
  nameWithType: RegexWorker.ProcessRegex(String,String)
  fullName: System.Web.Configuration.RegexWorker.ProcessRegex(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.RegexWorker.#ctor*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: RegexWorker
  nameWithType: RegexWorker.RegexWorker
- uid: System.Web.Configuration.RegexWorker.Item*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: Item
  nameWithType: RegexWorker.Item
- uid: System.Web.Configuration.RegexWorker.ProcessRegex*
  parent: System.Web.Configuration.RegexWorker
  isExternal: false
  name: ProcessRegex
  nameWithType: RegexWorker.ProcessRegex
