### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationNameAttribute
  id: ApplicationNameAttribute
  children:
  - System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  - System.EnterpriseServices.ApplicationNameAttribute.Value
  langs:
  - csharp
  name: ApplicationNameAttribute
  nameWithType: ApplicationNameAttribute
  fullName: System.EnterpriseServices.ApplicationNameAttribute
  type: Class
  summary: "指定要用於安裝的元件組件中的 COM + 應用程式的名稱。 這個類別無法被繼承。"
  remarks: ''
  example:
  - "The following example demonstrates the use of this attribute to mark a <xref:System.EnterpriseServices.ServicedComponent> class.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/cpp/t-system.enterpriseservi_8_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/csharp/t-system.enterpriseservi_8_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationNameAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.EnterpriseServices.ApplicationNameAttribute
  langs:
  - csharp
  name: ApplicationNameAttribute(String)
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute(String)
  fullName: System.EnterpriseServices.ApplicationNameAttribute.ApplicationNameAttribute(String)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "初始化的新執行個體<xref href=&quot;System.EnterpriseServices.ApplicationNameAttribute&quot;></xref>類別，指定要用於安裝元件的 COM + 應用程式名稱。"
  remarks: ''
  example:
  - "The following example illustrates the use of this attribute to mark a <xref:System.EnterpriseServices.ServicedComponent> class.  \n  \n [!code-cpp[EnterpriseServices_Basic#1](~/add/codesnippet/cpp/m-system.enterpriseservi_28_1.cpp)]\n [!code-cs[EnterpriseServices_Basic#1](~/add/codesnippet/csharp/m-system.enterpriseservi_28_1.cs)]"
  syntax:
    content: public ApplicationNameAttribute (string name);
    parameters:
    - id: name
      type: System.String
      description: "COM + 應用程式名稱。"
  overload: System.EnterpriseServices.ApplicationNameAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationNameAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationNameAttribute.Value
  fullName: System.EnterpriseServices.ApplicationNameAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "取得值，指出包含組件中的元件的 COM + 應用程式名稱。"
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "COM + 應用程式名稱。"
  overload: System.EnterpriseServices.ApplicationNameAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor(System.String)
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: ApplicationNameAttribute(String)
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute(String)
  fullName: System.EnterpriseServices.ApplicationNameAttribute.ApplicationNameAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationNameAttribute.Value
  fullName: System.EnterpriseServices.ApplicationNameAttribute.Value
- uid: System.EnterpriseServices.ApplicationNameAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: ApplicationNameAttribute
  nameWithType: ApplicationNameAttribute.ApplicationNameAttribute
- uid: System.EnterpriseServices.ApplicationNameAttribute.Value*
  parent: System.EnterpriseServices.ApplicationNameAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationNameAttribute.Value
