### YamlMime:ManagedReference
items:
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  id: RibbonApplicationMenuItemLevel
  children:
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  langs:
  - csharp
  name: RibbonApplicationMenuItemLevel
  nameWithType: RibbonApplicationMenuItemLevel
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  type: Enum
  summary: "定義常數，指定功能表項目會顯示在功能區應用程式功能表中的層級。"
  remarks: "這個列舉型別由<xref:System.Windows.Controls.Ribbon.RibbonApplicationMenuItem.Level%2A>屬性。</xref:System.Windows.Controls.Ribbon.RibbonApplicationMenuItem.Level%2A>"
  syntax:
    content: public enum RibbonApplicationMenuItemLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  id: Middle
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Middle
  nameWithType: RibbonApplicationMenuItemLevel.Middle
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "功能表項目會顯示在的中介層級。"
  syntax:
    content: Middle
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  id: Sub
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Sub
  nameWithType: RibbonApplicationMenuItemLevel.Sub
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "功能表項目會顯示在最低層級。"
  syntax:
    content: Sub
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  id: Top
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Top
  nameWithType: RibbonApplicationMenuItemLevel.Top
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "功能表項目會顯示在最上層。"
  syntax:
    content: Top
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Middle
  nameWithType: RibbonApplicationMenuItemLevel.Middle
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  parent: System.Windows.Controls.Ribbon
  isExternal: false
  name: RibbonApplicationMenuItemLevel
  nameWithType: RibbonApplicationMenuItemLevel
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Sub
  nameWithType: RibbonApplicationMenuItemLevel.Sub
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Top
  nameWithType: RibbonApplicationMenuItemLevel.Top
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
