### YamlMime:ManagedReference
items:
- uid: System.Configuration.DictionarySectionHandler
  id: DictionarySectionHandler
  children:
  - System.Configuration.DictionarySectionHandler.#ctor
  - System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  - System.Configuration.DictionarySectionHandler.KeyAttributeName
  - System.Configuration.DictionarySectionHandler.ValueAttributeName
  langs:
  - csharp
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler
  type: Class
  summary: "提供索引鍵/值組的組態區段的設定資訊。"
  remarks: "這個類別會實作`IConfigSectionHandler`介面。 DictionarySectionHandler 定義規則操作 XML 組態區段。"
  syntax:
    content: 'public class DictionarySectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.DictionarySectionHandler&quot;></xref>類別。"
  syntax:
    content: public DictionarySectionHandler ();
    parameters: []
  overload: System.Configuration.DictionarySectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "建立新的組態處理常式，並將它加入至指定的參數為基礎的區段處理常式集合。"
  remarks: "`parent`物件參數做為對應的父組態區段中的組態設定。 `context`物件參數是組態區段處理常式，會計算組態值的虛擬路徑。 通常這個參數保留， `null`。  `section`參數是<xref:System.Xml.XmlNode>，其中包含要處理的組態資訊。</xref:System.Xml.XmlNode> `section`參數可直接存取組態區段的 XML 內容。"
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "父物件。"
    - id: context
      type: System.Object
      description: "設定內容物件。"
    - id: section
      type: System.Xml.XmlNode
      description: "區段的 XML 節點。"
    return:
      type: System.Object
      description: "組態物件。"
  overload: System.Configuration.DictionarySectionHandler.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  id: KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得要做為索引鍵/值組中的索引鍵的 XML 屬性名稱。"
  syntax:
    content: protected virtual string KeyAttributeName { get; }
    return:
      type: System.String
      description: "包含索引鍵屬性名稱的字串值。"
  overload: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  id: ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得 XML 屬性名稱做為索引鍵/值組中的值。"
  syntax:
    content: protected virtual string ValueAttributeName { get; }
    return:
      type: System.String
      description: "字串值，包含 value 屬性的名稱。"
  overload: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.DictionarySectionHandler.#ctor
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
- uid: System.Configuration.DictionarySectionHandler.#ctor*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler.DictionarySectionHandler
- uid: System.Configuration.DictionarySectionHandler.Create*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create
  nameWithType: DictionarySectionHandler.Create
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
