### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.PerformanceCountersElement
  id: PerformanceCountersElement
  children:
  - System.Net.Configuration.PerformanceCountersElement.#ctor
  - System.Net.Configuration.PerformanceCountersElement.Enabled
  - System.Net.Configuration.PerformanceCountersElement.Properties
  langs:
  - csharp
  name: PerformanceCountersElement
  nameWithType: PerformanceCountersElement
  fullName: System.Net.Configuration.PerformanceCountersElement
  type: Class
  summary: "表示效能計數器項目<xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;></xref>判斷是否啟用網路效能計數器的組態檔。 這個類別無法被繼承。"
  remarks: "這個類別會對應到[ \\&lt; performanceCounter\\&gt;項目 （網路設定）](../Topic/%3CperformanceCounter%3E%20Element%20\\(Network%20Settings\\).md)組態項目。 這個類別會提供以程式設計方式存取可以儲存在組態檔中的資訊。"
  syntax:
    content: 'public sealed class PerformanceCountersElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: PerformanceCountersElement()
  nameWithType: PerformanceCountersElement.PerformanceCountersElement()
  fullName: System.Net.Configuration.PerformanceCountersElement.PerformanceCountersElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "具現化<xref href=&quot;System.Net.Configuration.PerformanceCountersElement&quot;></xref>物件。"
  syntax:
    content: public PerformanceCountersElement ();
    parameters: []
  overload: System.Net.Configuration.PerformanceCountersElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled
  id: Enabled
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
  fullName: System.Net.Configuration.PerformanceCountersElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得或設定是否啟用效能計數器。"
  remarks: "這個屬性的預設值是`false`。"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果啟用效能計數器。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Net.Configuration.PerformanceCountersElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.PerformanceCountersElement.Properties
  id: Properties
  parent: System.Net.Configuration.PerformanceCountersElement
  langs:
  - csharp
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
  fullName: System.Net.Configuration.PerformanceCountersElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Net.Configuration.PerformanceCountersElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: PerformanceCountersElement()
  nameWithType: PerformanceCountersElement.PerformanceCountersElement()
  fullName: System.Net.Configuration.PerformanceCountersElement.PerformanceCountersElement()
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
  fullName: System.Net.Configuration.PerformanceCountersElement.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.PerformanceCountersElement.Properties
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
  fullName: System.Net.Configuration.PerformanceCountersElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.PerformanceCountersElement.#ctor*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: PerformanceCountersElement
  nameWithType: PerformanceCountersElement.PerformanceCountersElement
- uid: System.Net.Configuration.PerformanceCountersElement.Enabled*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Enabled
  nameWithType: PerformanceCountersElement.Enabled
- uid: System.Net.Configuration.PerformanceCountersElement.Properties*
  parent: System.Net.Configuration.PerformanceCountersElement
  isExternal: false
  name: Properties
  nameWithType: PerformanceCountersElement.Properties
