### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  id: BrowserCapabilitiesCodeGenerator
  children:
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  - System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  type: Class
  summary: "BrowserCapabilitiesCodeGenerator 類別會在內部使用<xref uid=&quot;langword_csharp_aspnet_regbrowsers&quot; name=&quot;aspnet_regbrowsers&quot; href=&quot;&quot;></xref>剖析.browser 瀏覽器定義檔案，並將瀏覽器加入至執行階段的已知瀏覽器集合中包含的工具<xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;></xref>物件。"
  remarks: "這個類別所產生的原始程式碼的組件以取得<xref:System.Web.Configuration.BrowserCapabilitiesFactory>類別，可在執行階段，會產生要求特定<xref:System.Web.Configuration.HttpCapabilitiesBase>透過 ASP.NET 內建函式可公開存取的物件`Request.Browser`屬性。</xref:System.Web.Configuration.HttpCapabilitiesBase> </xref:System.Web.Configuration.BrowserCapabilitiesFactory>"
  syntax:
    content: public class BrowserCapabilitiesCodeGenerator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在內部用來建立的新執行個體<xref href=&quot;System.Web.Configuration.BrowserCapabilitiesCodeGenerator&quot;> </xref>。"
  syntax:
    content: public BrowserCapabilitiesCodeGenerator ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  id: Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在內部使用，來協調此類別的行為。"
  remarks: "這個方法會先逐一 「 瀏覽器 」 資料夾。 然後它會呼叫<xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A>，其中載入及剖析的瀏覽器定義集合中包含的 XML 檔案，並將插入含瀏覽器的內部集合的資訊。</xref:System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles%2A> 然後它會呼叫產生來源的程式碼編譯的內部方法，以及暫存器，以在全域組件中的組件快取<xref:System.Web.Configuration.BrowserCapabilitiesFactory>物件。</xref:System.Web.Configuration.BrowserCapabilitiesFactory> 如有必要，這個方法會接著呼叫重新啟動 Web 伺服器的內部方法。"
  syntax:
    content: public virtual void Create ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  id: ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "載入和剖析瀏覽器定義檔案的集合中包含的 XML 並將插入含瀏覽器的內部集合的資訊。"
  syntax:
    content: protected void ProcessBrowserFiles (bool useVirtualPath, string virtualDir);
    parameters:
    - id: useVirtualPath
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要使用的虛擬路徑。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
    - id: virtualDir
      type: System.String
      description: "包含瀏覽器定義檔案的虛擬目錄的路徑。 預設值為<xref:System.String>.</xref:System.String>"
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  exceptions:
  - type: System.Web.HttpParseException
    commentId: T:System.Web.HttpParseException
    description: "One of the browser-definition files does not have a root element named \"browsers\".  \n  \n \\- or -  \n  \n One of the browser-definition files fails to load."
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  id: Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  langs:
  - csharp
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "從全域組件快取中移除瀏覽器能力處理站，並刪除其強式名稱公開金鑰語彙基元檔案。"
  remarks: "這個方法會重新啟動 Web 服務。 瀏覽器能力處理站從全域組件快取中移除，並會刪除其強式名稱公開金鑰語彙基元檔案。 Web 服務然後重新啟動一次如果解除安裝成功。"
  syntax:
    content: public bool Uninstall ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果瀏覽器能力處理站已從全域組件快取中，解除安裝否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.HttpParseException
  parent: System.Web
  isExternal: false
  name: HttpParseException
  nameWithType: HttpParseException
  fullName: System.Web.HttpParseException
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator()
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create()
  nameWithType: BrowserCapabilitiesCodeGenerator.Create()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(System.Boolean,System.String)
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles(Boolean,String)
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles(Boolean,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall()
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall()
  fullName: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall()
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: BrowserCapabilitiesCodeGenerator
  nameWithType: BrowserCapabilitiesCodeGenerator.BrowserCapabilitiesCodeGenerator
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Create*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Create
  nameWithType: BrowserCapabilitiesCodeGenerator.Create
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: ProcessBrowserFiles
  nameWithType: BrowserCapabilitiesCodeGenerator.ProcessBrowserFiles
- uid: System.Web.Configuration.BrowserCapabilitiesCodeGenerator.Uninstall*
  parent: System.Web.Configuration.BrowserCapabilitiesCodeGenerator
  isExternal: false
  name: Uninstall
  nameWithType: BrowserCapabilitiesCodeGenerator.Uninstall
