### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.DefaultProxySection
  id: DefaultProxySection
  children:
  - System.Net.Configuration.DefaultProxySection.#ctor
  - System.Net.Configuration.DefaultProxySection.BypassList
  - System.Net.Configuration.DefaultProxySection.Enabled
  - System.Net.Configuration.DefaultProxySection.Module
  - System.Net.Configuration.DefaultProxySection.PostDeserialize
  - System.Net.Configuration.DefaultProxySection.Properties
  - System.Net.Configuration.DefaultProxySection.Proxy
  - System.Net.Configuration.DefaultProxySection.Reset(System.Configuration.ConfigurationElement)
  - System.Net.Configuration.DefaultProxySection.UseDefaultCredentials
  langs:
  - csharp
  name: DefaultProxySection
  nameWithType: DefaultProxySection
  fullName: System.Net.Configuration.DefaultProxySection
  type: Class
  summary: "表示 Web proxy 伺服器使用的組態區段。 這個類別無法被繼承。"
  remarks: "This class corresponds to the [\\&lt;defaultProxy\\&gt; Element (Network Settings)](../Topic/%3CdefaultProxy%3E%20Element%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to access information about the Web proxy server used for requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes. The following table describes the configuration elements contained in the DefaultProxySection configuration section.  \n  \n|Element|Description|  \n|-------------|-----------------|  \n|<xref:System.Net.Configuration.ProxyElement>|Identifies the Web proxy server to use.|  \n|<xref:System.Net.Configuration.BypassElement>|Identifies resources that are not retrieved using the proxy server.|  \n|<xref:System.Net.Configuration.ModuleElement>|Identifies a custom <xref:System.Net.IWebProxy> implementation.|  \n  \n This class provides programmatic access to information that can be stored in configuration files.  \n  \n The DefaultProxySection settings apply only to the default proxy server."
  syntax:
    content: 'public sealed class DefaultProxySection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: DefaultProxySection()
  nameWithType: DefaultProxySection.DefaultProxySection()
  fullName: System.Net.Configuration.DefaultProxySection.DefaultProxySection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Net.Configuration.DefaultProxySection&quot;></xref>類別。"
  syntax:
    content: public DefaultProxySection ();
    parameters: []
  overload: System.Net.Configuration.DefaultProxySection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.BypassList
  id: BypassList
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: BypassList
  nameWithType: DefaultProxySection.BypassList
  fullName: System.Net.Configuration.DefaultProxySection.BypassList
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得不會使用 Web proxy 伺服器取得的資源集合。"
  remarks: "<xref:System.Net.Configuration.BypassElementCollection>傳回此屬性包含一個<xref:System.Net.Configuration.BypassElement>會略過 Web Proxy 伺服器的每個資源。</xref:System.Net.Configuration.BypassElement> </xref:System.Net.Configuration.BypassElementCollection>"
  syntax:
    content: public System.Net.Configuration.BypassElementCollection BypassList { get; }
    return:
      type: System.Net.Configuration.BypassElementCollection
      description: "A <xref href=&quot;System.Net.Configuration.BypassElementCollection&quot;> </xref> ，其中包含的位址不使用 Web proxy 伺服器的資源。"
  overload: System.Net.Configuration.DefaultProxySection.BypassList*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.Enabled
  id: Enabled
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: Enabled
  nameWithType: DefaultProxySection.Enabled
  fullName: System.Net.Configuration.DefaultProxySection.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得或設定是否使用 Web proxy。"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果將使用 Web proxy。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Net.Configuration.DefaultProxySection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.Module
  id: Module
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: Module
  nameWithType: DefaultProxySection.Module
  fullName: System.Net.Configuration.DefaultProxySection.Module
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得自訂的 Web proxy 實作的型別資訊。"
  remarks: "<xref:System.Net.Configuration.ModuleElement>傳回由此屬性識別類型、 組件和版本的自訂<xref:System.Net.IWebProxy>實作。</xref:System.Net.IWebProxy> </xref:System.Net.Configuration.ModuleElement>"
  syntax:
    content: public System.Net.Configuration.ModuleElement Module { get; }
    return:
      type: System.Net.Configuration.ModuleElement
      description: "A <xref href=&quot;System.Net.Configuration.ModuleElement&quot;></xref>.       如需自訂的 Web proxy 實作型別資訊。"
  overload: System.Net.Configuration.DefaultProxySection.Module*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.PostDeserialize
  id: PostDeserialize
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: DefaultProxySection.PostDeserialize()
  fullName: System.Net.Configuration.DefaultProxySection.PostDeserialize()
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Net.Configuration.DefaultProxySection.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.Properties
  id: Properties
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultProxySection.Properties
  fullName: System.Net.Configuration.DefaultProxySection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Net.Configuration.DefaultProxySection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.Proxy
  id: Proxy
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: Proxy
  nameWithType: DefaultProxySection.Proxy
  fullName: System.Net.Configuration.DefaultProxySection.Proxy
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得可識別要使用的 Web proxy 伺服器的 URI。"
  remarks: "<xref:System.Net.Configuration.ProxyElement>傳回由此屬性識別的資源不在使用 Web proxy 伺服器<xref:System.Net.Configuration.DefaultProxySection.BypassList%2A>集合。</xref:System.Net.Configuration.DefaultProxySection.BypassList%2A> </xref:System.Net.Configuration.ProxyElement>"
  syntax:
    content: public System.Net.Configuration.ProxyElement Proxy { get; }
    return:
      type: System.Net.Configuration.ProxyElement
      description: "A <xref href=&quot;System.Net.Configuration.ProxyElement&quot;></xref>.       識別 Web proxy 伺服器的 URI。"
  overload: System.Net.Configuration.DefaultProxySection.Proxy*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: DefaultProxySection.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.DefaultProxySection.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "即將加入。"
  overload: System.Net.Configuration.DefaultProxySection.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials
  id: UseDefaultCredentials
  parent: System.Net.Configuration.DefaultProxySection
  langs:
  - csharp
  name: UseDefaultCredentials
  nameWithType: DefaultProxySection.UseDefaultCredentials
  fullName: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得或設定預設的認證是否要用來存取 Web proxy 伺服器。"
  syntax:
    content: public bool UseDefaultCredentials { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果預設認證來使用。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.DefaultProxySection.#ctor
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: DefaultProxySection()
  nameWithType: DefaultProxySection.DefaultProxySection()
  fullName: System.Net.Configuration.DefaultProxySection.DefaultProxySection()
- uid: System.Net.Configuration.DefaultProxySection.BypassList
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: BypassList
  nameWithType: DefaultProxySection.BypassList
  fullName: System.Net.Configuration.DefaultProxySection.BypassList
- uid: System.Net.Configuration.BypassElementCollection
  parent: System.Net.Configuration
  isExternal: false
  name: BypassElementCollection
  nameWithType: BypassElementCollection
  fullName: System.Net.Configuration.BypassElementCollection
- uid: System.Net.Configuration.DefaultProxySection.Enabled
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Enabled
  nameWithType: DefaultProxySection.Enabled
  fullName: System.Net.Configuration.DefaultProxySection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Net.Configuration.DefaultProxySection.Module
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Module
  nameWithType: DefaultProxySection.Module
  fullName: System.Net.Configuration.DefaultProxySection.Module
- uid: System.Net.Configuration.ModuleElement
  parent: System.Net.Configuration
  isExternal: false
  name: ModuleElement
  nameWithType: ModuleElement
  fullName: System.Net.Configuration.ModuleElement
- uid: System.Net.Configuration.DefaultProxySection.PostDeserialize
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: PostDeserialize()
  nameWithType: DefaultProxySection.PostDeserialize()
  fullName: System.Net.Configuration.DefaultProxySection.PostDeserialize()
- uid: System.Net.Configuration.DefaultProxySection.Properties
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Properties
  nameWithType: DefaultProxySection.Properties
  fullName: System.Net.Configuration.DefaultProxySection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.DefaultProxySection.Proxy
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Proxy
  nameWithType: DefaultProxySection.Proxy
  fullName: System.Net.Configuration.DefaultProxySection.Proxy
- uid: System.Net.Configuration.ProxyElement
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement
  nameWithType: ProxyElement
  fullName: System.Net.Configuration.ProxyElement
- uid: System.Net.Configuration.DefaultProxySection.Reset(System.Configuration.ConfigurationElement)
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: DefaultProxySection.Reset(ConfigurationElement)
  fullName: System.Net.Configuration.DefaultProxySection.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: UseDefaultCredentials
  nameWithType: DefaultProxySection.UseDefaultCredentials
  fullName: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials
- uid: System.Net.Configuration.DefaultProxySection.#ctor*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: DefaultProxySection
  nameWithType: DefaultProxySection.DefaultProxySection
- uid: System.Net.Configuration.DefaultProxySection.BypassList*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: BypassList
  nameWithType: DefaultProxySection.BypassList
- uid: System.Net.Configuration.DefaultProxySection.Enabled*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Enabled
  nameWithType: DefaultProxySection.Enabled
- uid: System.Net.Configuration.DefaultProxySection.Module*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Module
  nameWithType: DefaultProxySection.Module
- uid: System.Net.Configuration.DefaultProxySection.PostDeserialize*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: PostDeserialize
  nameWithType: DefaultProxySection.PostDeserialize
- uid: System.Net.Configuration.DefaultProxySection.Properties*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Properties
  nameWithType: DefaultProxySection.Properties
- uid: System.Net.Configuration.DefaultProxySection.Proxy*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Proxy
  nameWithType: DefaultProxySection.Proxy
- uid: System.Net.Configuration.DefaultProxySection.Reset*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: Reset
  nameWithType: DefaultProxySection.Reset
- uid: System.Net.Configuration.DefaultProxySection.UseDefaultCredentials*
  parent: System.Net.Configuration.DefaultProxySection
  isExternal: false
  name: UseDefaultCredentials
  nameWithType: DefaultProxySection.UseDefaultCredentials
