### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: "指定的覆寫行為的組態項目之組態項目的子目錄中。"
  remarks: "使用 OverrideMode 列舉值來設定<xref:System.Configuration.SectionInformation.OverrideMode%2A>屬性的<xref:System.Configuration.SectionInformation>類別。</xref:System.Configuration.SectionInformation> </xref:System.Configuration.SectionInformation.OverrideMode%2A> 您可以設定此屬性若要以程式設計方式指定的組態項目或群組覆寫行為。 若要以宣告方式設定的覆寫行為項目內的所有組態項目，使用`allowOverride`屬性。 <xref:System.Configuration.SectionInformation.OverrideMode%2A>屬性可讓您更精確地控制從而內的項目`location`項目。</xref:System.Configuration.SectionInformation.OverrideMode%2A>"
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "項目或群組的組態設定會覆寫由子目錄中的組態設定。"
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "項目或群組的組態設定無法覆寫子目錄中的組態設定。"
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "如果目前的組態項目或群組的父項目明確允許的子目錄中的組態設定會覆寫項目或群組的組態設定。 若要覆寫權限會透過指定<xref uid=&quot;langword_csharp_OverrideMode&quot; name=&quot;OverrideMode&quot; href=&quot;&quot;></xref>屬性。"
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
