### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  id: DiscoveryVersionConverter
  children:
  - System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.#ctor
  - System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: DiscoveryVersionConverter
  nameWithType: DiscoveryVersionConverter
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  type: Class
  summary: "提供將 Ws-discovery 通訊協定版本變更為另一種類型的功能。"
  syntax:
    content: 'public class DiscoveryVersionConverter : System.ComponentModel.TypeConverter'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  langs:
  - csharp
  name: DiscoveryVersionConverter()
  nameWithType: DiscoveryVersionConverter.DiscoveryVersionConverter()
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.DiscoveryVersionConverter()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter&quot;></xref>類別。"
  syntax:
    content: public DiscoveryVersionConverter ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  langs:
  - csharp
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: DiscoveryVersionConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "傳回值，這個值，指出是否可以變更指定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>這個轉換子，並使用指定的內容和文化特性資訊的型別物件。"
  syntax:
    content: public override bool CanConvertFrom (System.ComponentModel.ITypeDescriptorContext context, Type sourceType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "描述子格式資訊，可協助輸入的轉換<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>另一種類型的物件。"
    - id: sourceType
      type: System.Type
      description: "<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;> </xref>變更為這個轉換子的類型的物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果可能的話，若要變更指定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>物件類型的這個轉換子; 否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  id: CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  langs:
  - csharp
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: DiscoveryVersionConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo(ITypeDescriptorContext,Type)
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "傳回值，這個值，指出是否可以變更指定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>至指定的型別，並使用指定的內容和文化特性資訊。"
  syntax:
    content: public override bool CanConvertTo (System.ComponentModel.ITypeDescriptorContext context, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "描述子格式資訊，可協助輸入的轉換<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>另一種類型的物件。"
    - id: destinationType
      type: System.Type
      description: "所得的類型<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>物件變更。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果可能的話，若要變更指定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>物件指定的類型; 否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: DiscoveryVersionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "將給定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>這個轉換子，並使用指定的內容和文化特性資訊的型別物件。"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "描述子格式資訊，可協助輸入的轉換<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>另一種類型的物件。"
    - id: culture
      type: System.Globalization.CultureInfo
      description: "要在類型轉換中使用的文化特性資訊。"
    - id: value
      type: System.Object
      description: "<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;> </xref>物件來變更。"
    return:
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;> </xref>已變更為這個轉換子的型別。"
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: DiscoveryVersionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "將給定<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>為指定的類型，使用指定的內容和文化特性資訊。"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType);
    parameters:
    - id: context
      type: System.ComponentModel.ITypeDescriptorContext
      description: "描述子格式資訊，可協助輸入的轉換<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>另一種類型的物件。"
    - id: culture
      type: System.Globalization.CultureInfo
      description: "要在類型轉換中使用的文化特性資訊。"
    - id: value
      type: System.Object
      description: "<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;> </xref>變更。"
    - id: destinationType
      type: System.Type
      description: "所得的類型<xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;></xref>物件已變更。"
    return:
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Discovery.DiscoveryVersion&quot;> </xref>已變更為指定的類型。"
  overload: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.TypeConverter
  isExternal: false
  name: System.ComponentModel.TypeConverter
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.#ctor
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: DiscoveryVersionConverter()
  nameWithType: DiscoveryVersionConverter.DiscoveryVersionConverter()
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.DiscoveryVersionConverter()
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: CanConvertFrom(ITypeDescriptorContext,Type)
  nameWithType: DiscoveryVersionConverter.CanConvertFrom(ITypeDescriptorContext,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom(ITypeDescriptorContext,Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: CanConvertTo(ITypeDescriptorContext,Type)
  nameWithType: DiscoveryVersionConverter.CanConvertTo(ITypeDescriptorContext,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo(ITypeDescriptorContext,Type)
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: DiscoveryVersionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: DiscoveryVersionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: DiscoveryVersionConverter
  nameWithType: DiscoveryVersionConverter.DiscoveryVersionConverter
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertFrom*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: CanConvertFrom
  nameWithType: DiscoveryVersionConverter.CanConvertFrom
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.CanConvertTo*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: CanConvertTo
  nameWithType: DiscoveryVersionConverter.CanConvertTo
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertFrom*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: DiscoveryVersionConverter.ConvertFrom
- uid: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter.ConvertTo*
  parent: System.ServiceModel.Discovery.Configuration.DiscoveryVersionConverter
  isExternal: false
  name: ConvertTo
  nameWithType: DiscoveryVersionConverter.ConvertTo
