### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PolicyImporterElement
  id: PolicyImporterElement
  children:
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.PolicyImporterElement.Properties
  - System.ServiceModel.Configuration.PolicyImporterElement.Type
  langs:
  - csharp
  name: PolicyImporterElement
  nameWithType: PolicyImporterElement
  fullName: System.ServiceModel.Configuration.PolicyImporterElement
  type: Class
  summary: "表示指定有關繫結的自訂原則判斷提示的匯入的組態項目。 這個類別無法被繼承。"
  remarks: "這個組態區段會指定搜尋有關繫結功能，以及附加可實作判斷提示所需要的功能的自訂繫結項目自訂原則判斷提示的設定。"
  syntax:
    content: 'public sealed class PolicyImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement()
  nameWithType: PolicyImporterElement.PolicyImporterElement()
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.PolicyImporterElement&quot;></xref>類別。"
  syntax:
    content: public PolicyImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement(String)
  nameWithType: PolicyImporterElement.PolicyImporterElement(String)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.PolicyImporterElement&quot;></xref>與特定的原則類型的類別。"
  syntax:
    content: public PolicyImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: "原則型別。"
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: PolicyImporterElement(Type)
  nameWithType: PolicyImporterElement.PolicyImporterElement(Type)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.PolicyImporterElement&quot;></xref>與特定的原則類型的類別。"
  syntax:
    content: public PolicyImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "原則型別。"
  overload: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: PolicyImporterElement.Properties
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.PolicyImporterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: PolicyImporterElement.Type
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定這個組態項目的類型。"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "這個組態項目的類型。"
  overload: System.ServiceModel.Configuration.PolicyImporterElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement()
  nameWithType: PolicyImporterElement.PolicyImporterElement()
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement()
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement(String)
  nameWithType: PolicyImporterElement.PolicyImporterElement(String)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement(Type)
  nameWithType: PolicyImporterElement.PolicyImporterElement(Type)
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.PolicyImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Properties
  nameWithType: PolicyImporterElement.Properties
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Type
  nameWithType: PolicyImporterElement.Type
  fullName: System.ServiceModel.Configuration.PolicyImporterElement.Type
- uid: System.ServiceModel.Configuration.PolicyImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: PolicyImporterElement
  nameWithType: PolicyImporterElement.PolicyImporterElement
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Properties*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Properties
  nameWithType: PolicyImporterElement.Properties
- uid: System.ServiceModel.Configuration.PolicyImporterElement.Type*
  parent: System.ServiceModel.Configuration.PolicyImporterElement
  isExternal: false
  name: Type
  nameWithType: PolicyImporterElement.Type
