### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMappingsSection
  id: UrlMappingsSection
  children:
  - System.Web.Configuration.UrlMappingsSection.#ctor
  - System.Web.Configuration.UrlMappingsSection.IsEnabled
  - System.Web.Configuration.UrlMappingsSection.Properties
  - System.Web.Configuration.UrlMappingsSection.UrlMappings
  langs:
  - csharp
  name: UrlMappingsSection
  nameWithType: UrlMappingsSection
  fullName: System.Web.Configuration.UrlMappingsSection
  type: Class
  summary: "提供以程式設計方式存取<xref uid=&quot;langword_csharp_urlMappings&quot; name=&quot;urlMappings&quot; href=&quot;&quot;></xref>組態區段。 這個類別無法被繼承。"
  remarks: "UrlMappingsSection 類別可用來以程式設計方式存取和修改`urlMappings`組態檔區段。      > [!NOTE] >`urlMappings`區段包含<xref:System.Web.Configuration.UrlMapping>對應會顯示存在於您的 Web 應用程式的 Url，使用者的 Url 的物件。</xref:System.Web.Configuration.UrlMapping> UrlMappingsSection 可將資訊寫入至組態檔，根據定義的區段屬性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值為<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>限制的相關區段 任何嘗試寫入組態檔不允許在階層中的層級，將會導致由剖析器產生的錯誤訊息。 不過，您可以使用這個類別來讀取階層架構中的任何層級的組態資訊。"
  example:
  - "The following code example shows how to obtain the UrlMappingsSection object from the configuration file of an existing Web application. Also shown is an excerpt of the configuration file.  \n  \n [!code-vb[System.Web.Configuration.UrlMapping#1](~/add/codesnippet/visualbasic/t-system.web.configurati_28_1.vb)]\n [!code-cs[System.Web.Configuration.UrlMapping#1](~/add/codesnippet/csharp/t-system.web.configurati_28_1.cs)]  \n  \n```  \n<urlMappings enabled=\"true\">  \n  <add url= \"~/home.aspx\"  \n    mappedUrl=\"~/default.aspx?parm1=1\"/>  \n  <add url= \"~/products.aspx\"  \n    mappedUrl=\"~/default.aspx?parm1=2\"/>  \n</urlMappings>  \n```"
  syntax:
    content: 'public sealed class UrlMappingsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.UrlMappingsSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.UrlMappingsSection
  langs:
  - csharp
  name: UrlMappingsSection()
  nameWithType: UrlMappingsSection.UrlMappingsSection()
  fullName: System.Web.Configuration.UrlMappingsSection.UrlMappingsSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.UrlMappingsSection&quot;></xref>類別。"
  remarks: "UrlMappingsSection 建構函式不是直接從您的程式碼使用。 它會呼叫 ASP.NET 組態系統。 取得執行個體<xref:System.Web.Configuration.UrlMappingsSection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.UrlMappingsSection>"
  syntax:
    content: public UrlMappingsSection ();
    parameters: []
  overload: System.Web.Configuration.UrlMappingsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMappingsSection.IsEnabled
  id: IsEnabled
  parent: System.Web.Configuration.UrlMappingsSection
  langs:
  - csharp
  name: IsEnabled
  nameWithType: UrlMappingsSection.IsEnabled
  fullName: System.Web.Configuration.UrlMappingsSection.IsEnabled
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指出是否啟用對應。"
  syntax:
    content: public bool IsEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果已啟用對應。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.UrlMappingsSection.IsEnabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMappingsSection.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMappingsSection
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMappingsSection.Properties
  fullName: System.Web.Configuration.UrlMappingsSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.UrlMappingsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMappingsSection.UrlMappings
  id: UrlMappings
  parent: System.Web.Configuration.UrlMappingsSection
  langs:
  - csharp
  name: UrlMappings
  nameWithType: UrlMappingsSection.UrlMappings
  fullName: System.Web.Configuration.UrlMappingsSection.UrlMappings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得集合的<xref href=&quot;System.Web.Configuration.UrlMapping&quot;></xref>物件。"
  remarks: "每個<xref:System.Web.Configuration.UrlMapping>物件包含兩個屬性的識別 URL。</xref:System.Web.Configuration.UrlMapping> 一個屬性會指定給使用者，顯示的 URL其他 Web 應用程式中指定的 URL。"
  example:
  - "The following code example shows how to obtain the `urlMappings` section.  \n  \n [!code-vb[System.Web.Configuration.UrlMapping#2](~/add/codesnippet/visualbasic/p-system.web.configurati_178_1.vb)]\n [!code-cs[System.Web.Configuration.UrlMapping#2](~/add/codesnippet/csharp/p-system.web.configurati_178_1.cs)]"
  syntax:
    content: public System.Web.Configuration.UrlMappingCollection UrlMappings { get; }
    return:
      type: System.Web.Configuration.UrlMappingCollection
      description: "A <xref href=&quot;System.Web.Configuration.UrlMappingCollection&quot;> </xref>包含<xref href=&quot;System.Web.Configuration.UrlMapping&quot;></xref>物件。"
  overload: System.Web.Configuration.UrlMappingsSection.UrlMappings*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.UrlMappingsSection.#ctor
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: UrlMappingsSection()
  nameWithType: UrlMappingsSection.UrlMappingsSection()
  fullName: System.Web.Configuration.UrlMappingsSection.UrlMappingsSection()
- uid: System.Web.Configuration.UrlMappingsSection.IsEnabled
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: IsEnabled
  nameWithType: UrlMappingsSection.IsEnabled
  fullName: System.Web.Configuration.UrlMappingsSection.IsEnabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.UrlMappingsSection.Properties
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: Properties
  nameWithType: UrlMappingsSection.Properties
  fullName: System.Web.Configuration.UrlMappingsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMappingsSection.UrlMappings
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: UrlMappings
  nameWithType: UrlMappingsSection.UrlMappings
  fullName: System.Web.Configuration.UrlMappingsSection.UrlMappings
- uid: System.Web.Configuration.UrlMappingCollection
  parent: System.Web.Configuration
  isExternal: false
  name: UrlMappingCollection
  nameWithType: UrlMappingCollection
  fullName: System.Web.Configuration.UrlMappingCollection
- uid: System.Web.Configuration.UrlMappingsSection.#ctor*
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: UrlMappingsSection
  nameWithType: UrlMappingsSection.UrlMappingsSection
- uid: System.Web.Configuration.UrlMappingsSection.IsEnabled*
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: IsEnabled
  nameWithType: UrlMappingsSection.IsEnabled
- uid: System.Web.Configuration.UrlMappingsSection.Properties*
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: Properties
  nameWithType: UrlMappingsSection.Properties
- uid: System.Web.Configuration.UrlMappingsSection.UrlMappings*
  parent: System.Web.Configuration.UrlMappingsSection
  isExternal: false
  name: UrlMappings
  nameWithType: UrlMappingsSection.UrlMappings
