### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SqlCacheDependencySection
  id: SqlCacheDependencySection
  children:
  - System.Web.Configuration.SqlCacheDependencySection.#ctor
  - System.Web.Configuration.SqlCacheDependencySection.Databases
  - System.Web.Configuration.SqlCacheDependencySection.ElementProperty
  - System.Web.Configuration.SqlCacheDependencySection.Enabled
  - System.Web.Configuration.SqlCacheDependencySection.PollTime
  - System.Web.Configuration.SqlCacheDependencySection.PostDeserialize
  - System.Web.Configuration.SqlCacheDependencySection.Properties
  langs:
  - csharp
  name: SqlCacheDependencySection
  nameWithType: SqlCacheDependencySection
  fullName: System.Web.Configuration.SqlCacheDependencySection
  type: Class
  summary: "設定 ASP.NET 應用程式的 SQL 快取相依性。 這個類別無法被繼承。"
  remarks: "SqlCacheDependencySection 可讓您以程式設計方式存取和修改`sqlCacheDependency`元素`cache`組態區段。       SQL 快取相依性可讓快取的資料與原始來源同步處理。 設定 ASP.NET 應用程式的快取和特定 SQL Server 資料庫資料表時，執行個體中儲存的項目之間的關聯性之後<xref:System.Web.Caching.SqlCacheDependency>類別監視資料表，以便從快取中的資料表變更的項目，當自動移除項目。</xref:System.Web.Caching.SqlCacheDependency>       這個項目中的設定只會影響資料表為基礎的版本<xref:System.Web.Caching.SqlCacheDependency>物件。</xref:System.Web.Caching.SqlCacheDependency> 資料列層級<xref:System.Web.Caching.SqlCacheDependency>物件搭配[!INCLUDE[sqprsqlong](~/add/includes/sqprsqlong-md.md)]和更新版本都不會受到這些設定。</xref:System.Web.Caching.SqlCacheDependency>      > [!NOTE] > SqlCacheDependencySection 可將資訊寫入至組態檔，根據定義的區段屬性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值為<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>限制的相關區段 任何嘗試寫入組態檔不允許在階層中的層級，將會導致由剖析器產生的錯誤訊息。 不過，您可以使用這個類別來讀取階層架構中的任何層級的組態資訊。"
  example:
  - "The following code example shows how to obtain the SqlCacheDependencySection object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SqlCacheDependencySection#1](~/add/codesnippet/csharp/t-system.web.configurati_59_1.cs)]\n [!code-vb[System.Web.Configuration.SqlCacheDependencySection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_59_1.vb)]"
  syntax:
    content: 'public sealed class SqlCacheDependencySection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: SqlCacheDependencySection()
  nameWithType: SqlCacheDependencySection.SqlCacheDependencySection()
  fullName: System.Web.Configuration.SqlCacheDependencySection.SqlCacheDependencySection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.SqlCacheDependencySection&quot;></xref>類別。"
  remarks: "SqlCacheDependencySection 建構函式不是直接從您的程式碼使用。 它會呼叫 ASP.NET 組態系統。 取得執行個體<xref:System.Web.Configuration.SqlCacheDependencySection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SqlCacheDependencySection>"
  syntax:
    content: public SqlCacheDependencySection ();
    parameters: []
  overload: System.Web.Configuration.SqlCacheDependencySection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.Databases
  id: Databases
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: Databases
  nameWithType: SqlCacheDependencySection.Databases
  fullName: System.Web.Configuration.SqlCacheDependencySection.Databases
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得集合<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>物件儲存在<xref href=&quot;System.Web.Configuration.SqlCacheDependencySection&quot;> </xref>。"
  remarks: "資料庫屬性可讓您以程式設計方式存取`databases`元素[sqlCacheDependency 元素 （ASP.NET 設定結構描述） 快取](http://msdn.microsoft.com/en-us/3ffabd95-87b6-4a52-b753-9d298d43841d)的`cache`區段的組態檔。"
  example:
  - "The following code example shows how to use the Databases property.  \n  \n [!code-cs[System.Web.Configuration.SqlCacheDependencySection#2](~/add/codesnippet/csharp/p-system.web.configurati_339_1.cs)]\n [!code-vb[System.Web.Configuration.SqlCacheDependencySection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_339_1.vb)]"
  syntax:
    content: public System.Web.Configuration.SqlCacheDependencyDatabaseCollection Databases { get; }
    return:
      type: System.Web.Configuration.SqlCacheDependencyDatabaseCollection
      description: "A <xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabaseCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref> objects"
  overload: System.Web.Configuration.SqlCacheDependencySection.Databases*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: ElementProperty
  nameWithType: SqlCacheDependencySection.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencySection.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: "即將加入。"
  overload: System.Web.Configuration.SqlCacheDependencySection.ElementProperty*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.Enabled
  id: Enabled
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: Enabled
  nameWithType: SqlCacheDependencySection.Enabled
  fullName: System.Web.Configuration.SqlCacheDependencySection.Enabled
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指出是否應該監視的資料庫資料表的變更。"
  remarks: "設定 ASP.NET 應用程式的快取和特定 SQL Server 資料庫資料表時，執行個體中儲存的項目之間的關聯性之後<xref:System.Web.Caching.SqlCacheDependency>類別監視資料表，以便從快取中的資料表變更的項目時自動移除項目。</xref:System.Web.Caching.SqlCacheDependency>       這個類別，以正確運作，如資料庫和您要設定相依性的任何資料表都必須啟用通知。 如需詳細資訊，請參閱備註提供<xref:System.Web.Caching.SqlCacheDependency>類別。</xref:System.Web.Caching.SqlCacheDependency>      > [!NOTE] > 取得或設定值，指出是否在資料庫資料表有使用中<xref:System.Web.Caching.SqlCacheDependency>物件應該受到監視的變更。</xref:System.Web.Caching.SqlCacheDependency>  此設定不會影響資料列層級<xref:System.Web.Caching.SqlCacheDependency>物件。</xref:System.Web.Caching.SqlCacheDependency>"
  example:
  - "The following code example shows how to use the Enabled property.  \n  \n [!code-cs[System.Web.Configuration.SqlCacheDependencySection#4](~/add/codesnippet/csharp/p-system.web.configurati_112_1.cs)]\n [!code-vb[System.Web.Configuration.SqlCacheDependencySection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_112_1.vb)]"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果已啟用 SQL 快取監視;否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.SqlCacheDependencySection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.PollTime
  id: PollTime
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: PollTime
  nameWithType: SqlCacheDependencySection.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencySection.PollTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定頻率<xref href=&quot;System.Web.Caching.SqlCacheDependency&quot;></xref>輪詢資料庫資料表的變更。"
  remarks: "PollTime 屬性定義與 ASP.NET 輪詢資料表連結至快取的項目中變更資料庫的時間頻率。       **請注意**中的資料庫層級可以覆寫頻率`databases`元素`sqlCacheDependency`中`cache`組態區段。"
  example:
  - "The following code example shows how to use the PollTime property.  \n  \n [!code-cs[System.Web.Configuration.SqlCacheDependencySection#3](~/add/codesnippet/csharp/p-system.web.configurati_52_1.cs)]\n [!code-vb[System.Web.Configuration.SqlCacheDependencySection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_52_1.vb)]"
  syntax:
    content: public int PollTime { get; set; }
    return:
      type: System.Int32
      description: "SQL 快取相依性輪詢時間 （毫秒）。 預設值為 500。"
  overload: System.Web.Configuration.SqlCacheDependencySection.PollTime*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize
  id: PostDeserialize
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: SqlCacheDependencySection.PostDeserialize()
  fullName: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencySection.Properties
  id: Properties
  parent: System.Web.Configuration.SqlCacheDependencySection
  langs:
  - csharp
  name: Properties
  nameWithType: SqlCacheDependencySection.Properties
  fullName: System.Web.Configuration.SqlCacheDependencySection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.SqlCacheDependencySection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SqlCacheDependencySection.#ctor
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: SqlCacheDependencySection()
  nameWithType: SqlCacheDependencySection.SqlCacheDependencySection()
  fullName: System.Web.Configuration.SqlCacheDependencySection.SqlCacheDependencySection()
- uid: System.Web.Configuration.SqlCacheDependencySection.Databases
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Databases
  nameWithType: SqlCacheDependencySection.Databases
  fullName: System.Web.Configuration.SqlCacheDependencySection.Databases
- uid: System.Web.Configuration.SqlCacheDependencyDatabaseCollection
  parent: System.Web.Configuration
  isExternal: false
  name: SqlCacheDependencyDatabaseCollection
  nameWithType: SqlCacheDependencyDatabaseCollection
  fullName: System.Web.Configuration.SqlCacheDependencyDatabaseCollection
- uid: System.Web.Configuration.SqlCacheDependencySection.ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencySection.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencySection.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.SqlCacheDependencySection.Enabled
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Enabled
  nameWithType: SqlCacheDependencySection.Enabled
  fullName: System.Web.Configuration.SqlCacheDependencySection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.SqlCacheDependencySection.PollTime
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencySection.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencySection.PollTime
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: PostDeserialize()
  nameWithType: SqlCacheDependencySection.PostDeserialize()
  fullName: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize()
- uid: System.Web.Configuration.SqlCacheDependencySection.Properties
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencySection.Properties
  fullName: System.Web.Configuration.SqlCacheDependencySection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SqlCacheDependencySection.#ctor*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: SqlCacheDependencySection
  nameWithType: SqlCacheDependencySection.SqlCacheDependencySection
- uid: System.Web.Configuration.SqlCacheDependencySection.Databases*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Databases
  nameWithType: SqlCacheDependencySection.Databases
- uid: System.Web.Configuration.SqlCacheDependencySection.ElementProperty*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencySection.ElementProperty
- uid: System.Web.Configuration.SqlCacheDependencySection.Enabled*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Enabled
  nameWithType: SqlCacheDependencySection.Enabled
- uid: System.Web.Configuration.SqlCacheDependencySection.PollTime*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencySection.PollTime
- uid: System.Web.Configuration.SqlCacheDependencySection.PostDeserialize*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: PostDeserialize
  nameWithType: SqlCacheDependencySection.PostDeserialize
- uid: System.Web.Configuration.SqlCacheDependencySection.Properties*
  parent: System.Web.Configuration.SqlCacheDependencySection
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencySection.Properties
