### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.ChannelCacheSettings
  id: ChannelCacheSettings
  children:
  - System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  - System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  - System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  langs:
  - csharp
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings
  fullName: System.ServiceModel.Activities.ChannelCacheSettings
  type: Class
  summary: "代表定義通道快取的作業特性的設定。"
  remarks: ''
  example:
  - "The following example shows how to create a ChannelCacheSettings instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/t-system.servicemodel.ac_21_1.cs)]"
  syntax:
    content: public class ChannelCacheSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "建立的新執行個體<xref href=&quot;System.ServiceModel.Activities.ChannelCacheSettings&quot;></xref>類別。"
  remarks: ''
  example:
  - "The following example shows how to create a <xref:System.ServiceModel.Activities.ChannelCacheSettings> instance.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/m-system.servicemodel.ac_8_1.cs)]"
  syntax:
    content: public ChannelCacheSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "取得最大的物件可以維持閒置的快取中處置前的時間間隔。"
  remarks: ''
  example:
  - "The following example shows how to set the IdleTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_2_1.cs)]"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "時間間隔。"
  overload: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "取得一段時間之後從快取移除物件。"
  remarks: ''
  example:
  - "The following example shows how to set the LeaseTimeout property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_6_1.cs)]"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "時間間隔。"
  overload: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  id: MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  langs:
  - csharp
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "取得可保留在快取中的物件數目上限。"
  remarks: ''
  example:
  - "The following example shows how to set the MaxItemsInCache property.  \n  \n [!code-cs[ChannelCache#0](~/add/codesnippet/csharp/p-system.servicemodel.ac_1_1.cs)]"
  syntax:
    content: public int MaxItemsInCache { get; set; }
    return:
      type: System.Int32
      description: "物件的數目上限。"
  overload: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings()
  nameWithType: ChannelCacheSettings.ChannelCacheSettings()
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.ChannelCacheSettings()
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
  fullName: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activities.ChannelCacheSettings.#ctor*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: ChannelCacheSettings
  nameWithType: ChannelCacheSettings.ChannelCacheSettings
- uid: System.ServiceModel.Activities.ChannelCacheSettings.IdleTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelCacheSettings.IdleTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.LeaseTimeout*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelCacheSettings.LeaseTimeout
- uid: System.ServiceModel.Activities.ChannelCacheSettings.MaxItemsInCache*
  parent: System.ServiceModel.Activities.ChannelCacheSettings
  isExternal: false
  name: MaxItemsInCache
  nameWithType: ChannelCacheSettings.MaxItemsInCache
