### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection
  id: NetTcpSection
  children:
  - System.ServiceModel.Activation.Configuration.NetTcpSection.#ctor
  - System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts
  - System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault
  - System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog
  - System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts
  - System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections
  - System.ServiceModel.Activation.Configuration.NetTcpSection.Properties
  - System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout
  - System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled
  langs:
  - csharp
  name: NetTcpSection
  nameWithType: NetTcpSection
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection
  type: Class
  summary: "包含 NetTcpPortSharing 共用服務的組態項目。 這個類別無法被繼承。"
  remarks: "網路。TCP Port Sharing Service 允許多個處理序共用相同的 TCP 通訊埠。 這個類別包含可設定此服務的屬性。"
  syntax:
    content: 'public sealed class NetTcpSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: NetTcpSection()
  nameWithType: NetTcpSection.NetTcpSection()
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.NetTcpSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Activation.Configuration.NetTcpSection&quot;></xref>類別。"
  syntax:
    content: public NetTcpSection ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts
  id: AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: AllowAccounts
  nameWithType: NetTcpSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得使用者帳戶的處理序裝載[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]服務且已授權可連線共用服務。"
  syntax:
    content: public System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection AllowAccounts { get; }
    return:
      type: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection&quot;> </xref>包含該主機處理序的使用者帳戶[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]服務且已授權可連線共用服務。 傳回預設值為 LocalSystem、 Admin、 NS、 LS 和 IIS_USRS。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: NetTcpSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog
  id: ListenBacklog
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: ListenBacklog
  nameWithType: NetTcpSection.ListenBacklog
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得或設定最大未處理的連接，由共用連線所接受但是尚未分派到[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]服務。"
  syntax:
    content: public int ListenBacklog { get; set; }
    return:
      type: System.Int32
      description: "最大未處理的連接，由共用連線所接受但是尚未分派到[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]。 預設值為 10。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts
  id: MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: MaxPendingAccepts
  nameWithType: NetTcpSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得或設定最大未處理並行接收執行緒的共用服務之接聽端點上。"
  syntax:
    content: public int MaxPendingAccepts { get; set; }
    return:
      type: System.Int32
      description: "最大未處理並行接收執行緒的共用服務之接聽端點上。 預設值為 2。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections
  id: MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: MaxPendingConnections
  nameWithType: NetTcpSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得或設定的擱置連線數目上限這個共用服務。"
  remarks: "預設值為 100。"
  syntax:
    content: public int MaxPendingConnections { get; set; }
    return:
      type: System.Int32
      description: "這個共用服務的擱置連線最大數目。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties
  id: Properties
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: Properties
  nameWithType: NetTcpSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout
  id: ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: ReceiveTimeout
  nameWithType: NetTcpSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得或設定 NetTcpPortSharing 共用服務的逾時。"
  remarks: "此屬性會指定讀取框架資料以及從基礎連線執行連線分派的逾時。"
  syntax:
    content: public TimeSpan ReceiveTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "預設為 10 秒。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled
  id: TeredoEnabled
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  langs:
  - csharp
  name: TeredoEnabled
  nameWithType: NetTcpSection.TeredoEnabled
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Activation.Configuration
  summary: "取得或設定布林值，指出連接埠共用服務使用 Microsoft Teredo 服務代表的 TCP 連接埠上接聽[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]服務。"
  syntax:
    content: public bool TeredoEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果連接埠共用服務使用 Microsoft Teredo 服務代表的 TCP 連接埠上接聽[!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]服務; 否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.#ctor
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: NetTcpSection()
  nameWithType: NetTcpSection.NetTcpSection()
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.NetTcpSection()
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetTcpSection.AllowAccounts
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
  parent: System.ServiceModel.Activation.Configuration
  isExternal: false
  name: SecurityIdentifierElementCollection
  nameWithType: SecurityIdentifierElementCollection
  fullName: System.ServiceModel.Activation.Configuration.SecurityIdentifierElementCollection
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: NetTcpSection.InitializeDefault()
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault()
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: ListenBacklog
  nameWithType: NetTcpSection.ListenBacklog
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetTcpSection.MaxPendingAccepts
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetTcpSection.MaxPendingConnections
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: Properties
  nameWithType: NetTcpSection.Properties
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetTcpSection.ReceiveTimeout
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: TeredoEnabled
  nameWithType: NetTcpSection.TeredoEnabled
  fullName: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.#ctor*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: NetTcpSection
  nameWithType: NetTcpSection.NetTcpSection
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.AllowAccounts*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: AllowAccounts
  nameWithType: NetTcpSection.AllowAccounts
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.InitializeDefault*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: InitializeDefault
  nameWithType: NetTcpSection.InitializeDefault
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ListenBacklog*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: ListenBacklog
  nameWithType: NetTcpSection.ListenBacklog
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingAccepts*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: MaxPendingAccepts
  nameWithType: NetTcpSection.MaxPendingAccepts
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.MaxPendingConnections*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: MaxPendingConnections
  nameWithType: NetTcpSection.MaxPendingConnections
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.Properties*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: Properties
  nameWithType: NetTcpSection.Properties
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.ReceiveTimeout*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: ReceiveTimeout
  nameWithType: NetTcpSection.ReceiveTimeout
- uid: System.ServiceModel.Activation.Configuration.NetTcpSection.TeredoEnabled*
  parent: System.ServiceModel.Activation.Configuration.NetTcpSection
  isExternal: false
  name: TeredoEnabled
  nameWithType: NetTcpSection.TeredoEnabled
