### YamlMime:ManagedReference
items:
- uid: System.Web.UnvalidatedRequestValues
  id: UnvalidatedRequestValues
  children:
  - System.Web.UnvalidatedRequestValues.Cookies
  - System.Web.UnvalidatedRequestValues.Files
  - System.Web.UnvalidatedRequestValues.Form
  - System.Web.UnvalidatedRequestValues.Headers
  - System.Web.UnvalidatedRequestValues.Item(System.String)
  - System.Web.UnvalidatedRequestValues.Path
  - System.Web.UnvalidatedRequestValues.PathInfo
  - System.Web.UnvalidatedRequestValues.QueryString
  - System.Web.UnvalidatedRequestValues.RawUrl
  - System.Web.UnvalidatedRequestValues.Url
  langs:
  - csharp
  name: UnvalidatedRequestValues
  nameWithType: UnvalidatedRequestValues
  fullName: System.Web.UnvalidatedRequestValues
  type: Class
  summary: "提供對 HTTP 要求值的存取，而不觸發 ASP.NET 要求驗證。"
  remarks: "當 ASP.NET 讀取的值在 HTTP 要求的集合 (例如<xref:System.Web.HttpRequest.Form%2A>， <xref:System.Web.HttpRequest.QueryString%2A>，和<xref:System.Web.HttpRequest.Cookies%2A>集合)，它會執行*要求驗證*。</xref:System.Web.HttpRequest.Cookies%2A> </xref:System.Web.HttpRequest.QueryString%2A> </xref:System.Web.HttpRequest.Form%2A> 要求在驗證期間，ASP.NET 會檢查已張貼的值，並判斷它們是否包含標記、 指令碼或保留的字元。 根據預設，如果 ASP.NET 偵測到任何一種類型的輸入，就會擲回<xref:System.Web.HttpRequestValidationException>例外狀況。</xref:System.Web.HttpRequestValidationException> 這有助於防止惡意指令碼資料隱碼攻擊，在您的網站。       不過，在某些情況下，您可以略過 ASP.NET 要求驗證，並允許的值，包含標記、 指令碼或保留的字元。  例如，如果您的應用程式使用 rtf 文字編輯器，讓使用者提交格式的內容為 HTML 標記，您可以使用 UnvalidatedRequestValues 類別的成員來擷取 rtf 文字要求值，而不觸發預設 ASP.NET 要求驗證。 您可以在您的程式碼中存取這個類別的成員來使用<xref:System.Web.HttpRequest.Unvalidated%2A>屬性。</xref:System.Web.HttpRequest.Unvalidated%2A>      > [!IMPORTANT] > 如果您使用這個類別，您必須手動檢查潛在的跨網站指令碼攻擊的資料。"
  syntax:
    content: public sealed class UnvalidatedRequestValues
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Cookies
  id: Cookies
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
  fullName: System.Web.UnvalidatedRequestValues.Cookies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "取得用戶端送出，而不觸發 ASP.NET 要求驗證的 cookie 集合。"
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Web.HttpCookieCollection Cookies { get; }
    return:
      type: System.Web.HttpCookieCollection
      description: The cookies from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Cookies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Files
  id: Files
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
  fullName: System.Web.UnvalidatedRequestValues.Files
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of files that the client uploaded, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Web.HttpFileCollection Files { get; }
    return:
      type: System.Web.HttpFileCollection
      description: The files from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Files*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Form
  id: Form
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
  fullName: System.Web.UnvalidatedRequestValues.Form
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of form variables that the client submitted, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Form { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The form variables from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Form*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Headers
  id: Headers
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
  fullName: System.Web.UnvalidatedRequestValues.Headers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of HTTP headers that the client sent, without triggering request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Headers { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The headers from the HTTP request.
  overload: System.Web.UnvalidatedRequestValues.Headers*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Item(System.String)
  id: Item(System.String)
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Item(String)
  nameWithType: UnvalidatedRequestValues.Item(String)
  fullName: System.Web.UnvalidatedRequestValues.Item(String)
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the specified object from the <xref:System.Web.HttpRequest.Form*>, <xref:System.Web.HttpRequest.Cookies*>, <xref:System.Web.HttpRequest.QueryString*>, or <xref:System.Web.HttpRequest.ServerVariables*> collection, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string this[string field] { get; }
    parameters:
    - id: field
      type: System.String
      description: The key of the object to retrieve.
    return:
      type: System.String
      description: The requested object, or <xref uid="langword_csharp_null" name="null" href=""></xref> if the object is not found.
  overload: System.Web.UnvalidatedRequestValues.Item*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Path
  id: Path
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
  fullName: System.Web.UnvalidatedRequestValues.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the virtual path of the requested resource without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: The virtual path.
  overload: System.Web.UnvalidatedRequestValues.Path*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.PathInfo
  id: PathInfo
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
  fullName: System.Web.UnvalidatedRequestValues.PathInfo
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets additional path information for a resource that has a URL extension, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public string PathInfo { get; }
    return:
      type: System.String
      description: A string that contains additional path information for a resource.
  overload: System.Web.UnvalidatedRequestValues.PathInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.QueryString
  id: QueryString
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
  fullName: System.Web.UnvalidatedRequestValues.QueryString
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the collection of HTTP query string variables that the client submitted, without triggering ASP.NET request validation.
  remarks: >-
    > [!IMPORTANT]

    >  If you use this property, you must manually check the data for potential cross-site scripting attacks.
  syntax:
    content: public System.Collections.Specialized.NameValueCollection QueryString { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: The collection of query string variables sent by the client.
  overload: System.Web.UnvalidatedRequestValues.QueryString*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.RawUrl
  id: RawUrl
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
  fullName: System.Web.UnvalidatedRequestValues.RawUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the part of the requested URL that follows the website name, without triggering ASP.NET request validation.
  remarks: "> [!IMPORTANT]> 如果您使用這個屬性時，您必須手動檢查潛在的跨網站指令碼攻擊的資料。  \n  \n If the complete request URL is `http://www.contoso.com/default.aspx?id=44`, the value of RawUrl is `/default.aspx?id=44`."
  syntax:
    content: public string RawUrl { get; }
    return:
      type: System.String
      description: The part of the URL that follows the website name.
  overload: System.Web.UnvalidatedRequestValues.RawUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UnvalidatedRequestValues.Url
  id: Url
  parent: System.Web.UnvalidatedRequestValues
  langs:
  - csharp
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
  fullName: System.Web.UnvalidatedRequestValues.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: Gets the URL data for the request without triggering ASP.NET request validation.
  remarks: "> [!IMPORTANT]\n>  If you use this property, you must manually check the data for potential cross-site scripting attacks.  \n  \n You can retrieve URL data such as the port number, host name, path information, and data about the user from the <xref:System.Uri> object that this property returns."
  syntax:
    content: public Uri Url { get; }
    return:
      type: System.Uri
      description: An object that contains the URL data for the request.
  overload: System.Web.UnvalidatedRequestValues.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UnvalidatedRequestValues.Cookies
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
  fullName: System.Web.UnvalidatedRequestValues.Cookies
- uid: System.Web.HttpCookieCollection
  parent: System.Web
  isExternal: false
  name: HttpCookieCollection
  nameWithType: HttpCookieCollection
  fullName: System.Web.HttpCookieCollection
- uid: System.Web.UnvalidatedRequestValues.Files
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
  fullName: System.Web.UnvalidatedRequestValues.Files
- uid: System.Web.HttpFileCollection
  parent: System.Web
  isExternal: false
  name: HttpFileCollection
  nameWithType: HttpFileCollection
  fullName: System.Web.HttpFileCollection
- uid: System.Web.UnvalidatedRequestValues.Form
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
  fullName: System.Web.UnvalidatedRequestValues.Form
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.UnvalidatedRequestValues.Headers
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
  fullName: System.Web.UnvalidatedRequestValues.Headers
- uid: System.Web.UnvalidatedRequestValues.Item(System.String)
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Item(String)
  nameWithType: UnvalidatedRequestValues.Item(String)
  fullName: System.Web.UnvalidatedRequestValues.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UnvalidatedRequestValues.Path
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
  fullName: System.Web.UnvalidatedRequestValues.Path
- uid: System.Web.UnvalidatedRequestValues.PathInfo
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
  fullName: System.Web.UnvalidatedRequestValues.PathInfo
- uid: System.Web.UnvalidatedRequestValues.QueryString
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
  fullName: System.Web.UnvalidatedRequestValues.QueryString
- uid: System.Web.UnvalidatedRequestValues.RawUrl
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
  fullName: System.Web.UnvalidatedRequestValues.RawUrl
- uid: System.Web.UnvalidatedRequestValues.Url
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
  fullName: System.Web.UnvalidatedRequestValues.Url
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Web.UnvalidatedRequestValues.Cookies*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Cookies
  nameWithType: UnvalidatedRequestValues.Cookies
- uid: System.Web.UnvalidatedRequestValues.Files*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Files
  nameWithType: UnvalidatedRequestValues.Files
- uid: System.Web.UnvalidatedRequestValues.Form*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Form
  nameWithType: UnvalidatedRequestValues.Form
- uid: System.Web.UnvalidatedRequestValues.Headers*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Headers
  nameWithType: UnvalidatedRequestValues.Headers
- uid: System.Web.UnvalidatedRequestValues.Item*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Item
  nameWithType: UnvalidatedRequestValues.Item
- uid: System.Web.UnvalidatedRequestValues.Path*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Path
  nameWithType: UnvalidatedRequestValues.Path
- uid: System.Web.UnvalidatedRequestValues.PathInfo*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: PathInfo
  nameWithType: UnvalidatedRequestValues.PathInfo
- uid: System.Web.UnvalidatedRequestValues.QueryString*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: QueryString
  nameWithType: UnvalidatedRequestValues.QueryString
- uid: System.Web.UnvalidatedRequestValues.RawUrl*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: RawUrl
  nameWithType: UnvalidatedRequestValues.RawUrl
- uid: System.Web.UnvalidatedRequestValues.Url*
  parent: System.Web.UnvalidatedRequestValues
  isExternal: false
  name: Url
  nameWithType: UnvalidatedRequestValues.Url
