### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  id: SendMessageChannelCacheElement
  children:
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  - System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  langs:
  - csharp
  name: SendMessageChannelCacheElement
  nameWithType: SendMessageChannelCacheElement
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  type: Class
  summary: "建立並維護設定使用的子元素<xref href=&quot;System.ServiceModel.Activities.SendMessageChannelCache&quot;> </xref>，工作流程組態檔的服務行為區段中。 這是密封的類別。"
  syntax:
    content: 'public sealed class SendMessageChannelCacheElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: SendMessageChannelCacheElement()
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement&quot;></xref>類別。"
  syntax:
    content: public SendMessageChannelCacheElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  id: AllowUnsafeCaching
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得值，指出與工作流程執行個體相關聯的快取開啟或關閉。"
  remarks: "在大部分情況下的任何自訂繫結和/或行為，我們快取依預設開啟。 在使用者確實插入其本身的繫結和行為的情況下，通道處理站快取可能會變得不安全，因此，我們快取會關閉預設。 但使用者可以設定 AllowUnsafeCachingback 上需要仔細閱讀適當的 MSDN 文件，並做出決定，萬一安全性與效能之間 balanace 它們。"
  syntax:
    content: public bool AllowUnsafeCaching { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果工作流程執行個體快取已開啟。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得或設定型別<xref href=&quot;System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement&quot;> </xref>。"
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "型別物件。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  id: ChannelSettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得或設定通道快取的設定。"
  syntax:
    content: public System.ServiceModel.Activities.Configuration.ChannelSettingsElement ChannelSettings { get; }
    return:
      type: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
      description: "通道快取設定。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: SendMessageChannelCacheElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "即將加入。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  id: FactorySettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得或設定之通道處理站快取的設定。"
  remarks: "通道處理站快取代表快取的通道處理站。 如需通道處理站的詳細資訊，請參閱<xref:System.ServiceModel.ChannelFactory>和<xref:System.ServiceModel.ChannelFactory%601>。</xref:System.ServiceModel.ChannelFactory%601> </xref:System.ServiceModel.ChannelFactory>"
  syntax:
    content: public System.ServiceModel.Activities.Configuration.FactorySettingsElement FactorySettings { get; }
    return:
      type: System.ServiceModel.Activities.Configuration.FactorySettingsElement
      description: "通道處理站快取設定。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  langs:
  - csharp
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: SendMessageChannelCacheElement()
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.SendMessageChannelCacheElement()
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings
- uid: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: ChannelSettingsElement
  nameWithType: ChannelSettingsElement
  fullName: System.ServiceModel.Activities.Configuration.ChannelSettingsElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: SendMessageChannelCacheElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings
- uid: System.ServiceModel.Activities.Configuration.FactorySettingsElement
  parent: System.ServiceModel.Activities.Configuration
  isExternal: false
  name: FactorySettingsElement
  nameWithType: FactorySettingsElement
  fullName: System.ServiceModel.Activities.Configuration.FactorySettingsElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: SendMessageChannelCacheElement
  nameWithType: SendMessageChannelCacheElement.SendMessageChannelCacheElement
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.AllowUnsafeCaching*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: AllowUnsafeCaching
  nameWithType: SendMessageChannelCacheElement.AllowUnsafeCaching
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: BehaviorType
  nameWithType: SendMessageChannelCacheElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.ChannelSettings*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: ChannelSettings
  nameWithType: SendMessageChannelCacheElement.ChannelSettings
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: CreateBehavior
  nameWithType: SendMessageChannelCacheElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.FactorySettings*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: FactorySettings
  nameWithType: SendMessageChannelCacheElement.FactorySettings
- uid: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.SendMessageChannelCacheElement
  isExternal: false
  name: Properties
  nameWithType: SendMessageChannelCacheElement.Properties
