### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement
  id: PeerTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  - System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  langs:
  - csharp
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement
  type: Class
  summary: "定義對等所傳送的訊息的安全傳輸組態項目。"
  syntax:
    content: 'public sealed class PeerTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: PeerTransportSecurityElement()
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.PeerTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.PeerTransportSecurityElement&quot;></xref>類別。"
  syntax:
    content: public PeerTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  id: CredentialType
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得及設定用來驗證與對等傳輸所傳送訊息的認證類型的組態。"
  syntax:
    content: public System.ServiceModel.PeerTransportCredentialType CredentialType { get; set; }
    return:
      type: System.ServiceModel.PeerTransportCredentialType
      description: "<xref href=&quot;System.ServiceModel.PeerTransportCredentialType&quot;></xref>列舉值，包含用來驗證訊息的認證類型傳輸所傳送的對等。"
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: PeerTransportSecurityElement()
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.PeerTransportSecurityElement()
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType
- uid: System.ServiceModel.PeerTransportCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportCredentialType
  nameWithType: PeerTransportCredentialType
  fullName: System.ServiceModel.PeerTransportCredentialType
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: PeerTransportSecurityElement
  nameWithType: PeerTransportSecurityElement.PeerTransportSecurityElement
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.CredentialType*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecurityElement.CredentialType
- uid: System.ServiceModel.Configuration.PeerTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.PeerTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: PeerTransportSecurityElement.Properties
