### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer
  id: PointCollectionValueSerializer
  children:
  - System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  - System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: PointCollectionValueSerializer
  nameWithType: PointCollectionValueSerializer
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer
  type: Class
  summary: "將轉換的執行個體<xref:System.String>的執行個體，以及<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
  remarks: "這個類別通常只能使用<xref:System.Windows.Markup.Primitives.MarkupWriter>進行序列化。</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class PointCollectionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: PointCollectionValueSerializer()
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer()
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.PointCollectionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "初始化的新執行個體<xref href=&quot;System.Windows.Media.Converters.PointCollectionValueSerializer&quot;></xref>類別。"
  syntax:
    content: public PointCollectionValueSerializer ();
    parameters: []
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "決定是否轉換從給定<xref:System.String>的執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>可能。</xref:System.String>"
  remarks: "這個方法一律會傳回`true`。"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "要評估以進行轉換的字串。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果此值可以轉換。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "判斷執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>可以轉換成<xref:System.String>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>来評估以進行轉換。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<code> value </code>可以轉換成<xref:System.String>，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。</xref:System.String>"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "Occurs when <code>value</code> is not a <xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>."
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "將轉換<xref:System.String>到<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>要轉換成值<xref href=&quot;System.Windows.Media.PointCollection&quot;> </xref>。</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.Object
      description: "新執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>根據所提供<code> value </code>。"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media.Converters
  summary: "將轉換的執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>至<xref:System.String>。</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "執行個體<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>来評估以進行轉換。"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "用來進行轉換的內容資訊。"
    return:
      type: System.String
      description: "A<xref:System.String>所提供的表示法<xref href=&quot;System.Windows.Media.PointCollection&quot;></xref>物件。</xref:System.String>"
  overload: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: PointCollectionValueSerializer()
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer()
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.PointCollectionValueSerializer()
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.#ctor*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: PointCollectionValueSerializer
  nameWithType: PointCollectionValueSerializer.PointCollectionValueSerializer
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: PointCollectionValueSerializer.CanConvertFromString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.CanConvertToString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: PointCollectionValueSerializer.CanConvertToString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertFromString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: PointCollectionValueSerializer.ConvertFromString
- uid: System.Windows.Media.Converters.PointCollectionValueSerializer.ConvertToString*
  parent: System.Windows.Media.Converters.PointCollectionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: PointCollectionValueSerializer.ConvertToString
