### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement
  id: NetMsmqBindingCollectionElement
  children:
  - System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.#ctor
  langs:
  - csharp
  name: NetMsmqBindingCollectionElement
  nameWithType: NetMsmqBindingCollectionElement
  fullName: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement
  type: Class
  summary: "表示保存的集合的組態區段<xref href=&quot;System.ServiceModel.Configuration.NetMsmqBindingElement&quot;></xref>執行個體。"
  remarks: "此集合<xref:System.ServiceModel.Configuration.NetMsmqBindingElement>物件包含的所需的設定所有<xref:System.ServiceModel.NetMsmqBinding>函式繫結。</xref:System.ServiceModel.NetMsmqBinding> </xref:System.ServiceModel.Configuration.NetMsmqBindingElement> <xref:System.ServiceModel.NetMsmqBinding>繫結支援佇列，利用 Microsoft Message Queuing (MSMQ) 做為傳輸，並可支援鬆散偶合的應用程式、 失敗隔離、 負載撫平和中斷連接的作業。</xref:System.ServiceModel.NetMsmqBinding>"
  syntax:
    content: 'public class NetMsmqBindingCollectionElement : System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetMsmqBinding,System.ServiceModel.Configuration.NetMsmqBindingElement>'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.BindingCollectionElement
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.BindingCollectionElement.BindingName
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Bindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.BindingType
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ConfiguredBindings
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.ContainsKey(System.String)
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.GetDefault
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.Properties
  - System.ServiceModel.Configuration.StandardBindingCollectionElement`2.TryAdd(System.String,System.ServiceModel.Channels.Binding,System.Configuration.Configuration)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement
  langs:
  - csharp
  name: NetMsmqBindingCollectionElement()
  nameWithType: NetMsmqBindingCollectionElement.NetMsmqBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.NetMsmqBindingCollectionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.NetMsmqBindingCollectionElement&quot;></xref>類別。"
  syntax:
    content: public NetMsmqBindingCollectionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.StandardBindingCollectionElement`2
  isExternal: false
  name: System.ServiceModel.Configuration.StandardBindingCollectionElement<System.ServiceModel.NetMsmqBinding,System.ServiceModel.Configuration.NetMsmqBindingElement>
- uid: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.#ctor
  parent: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement
  isExternal: false
  name: NetMsmqBindingCollectionElement()
  nameWithType: NetMsmqBindingCollectionElement.NetMsmqBindingCollectionElement()
  fullName: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.NetMsmqBindingCollectionElement()
- uid: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement.#ctor*
  parent: System.ServiceModel.Configuration.NetMsmqBindingCollectionElement
  isExternal: false
  name: NetMsmqBindingCollectionElement
  nameWithType: NetMsmqBindingCollectionElement.NetMsmqBindingCollectionElement
