### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSetting
  id: SpecialSetting
  children:
  - System.Configuration.SpecialSetting.ConnectionString
  - System.Configuration.SpecialSetting.WebServiceUrl
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
  type: Enum
  summary: "指定應用程式設定屬性的特殊設定分類。"
  remarks: "SpecialSetting 列舉會定義一組特殊的類別目錄套用至應用程式設定屬性與 ttribute 類別。      > [!CAUTION] > 預設設定提供者， <xref:System.Configuration.LocalFileSettingsProvider>，不會加密或否則保護連接字串。</xref:System.Configuration.LocalFileSettingsProvider> 簡單它將這種類型的設定儲存在個別`<connectionstrings>`適當的組態檔中的一節。"
  syntax:
    content: public enum SpecialSetting
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.ConnectionString
  id: ConnectionString
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "組態屬性代表的連接字串，通常是資料存放區或網路資源。"
  syntax:
    content: ConnectionString
    return:
      type: System.Configuration.SpecialSetting
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  id: WebServiceUrl
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "組態屬性代表統一資源定位器 (URL) 的 Web 服務。"
  syntax:
    content: WebServiceUrl
    return:
      type: System.Configuration.SpecialSetting
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SpecialSetting.ConnectionString
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
