### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultSection
  id: DefaultSection
  children:
  - System.Configuration.DefaultSection.#ctor
  - System.Configuration.DefaultSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.DefaultSection.IsModified
  - System.Configuration.DefaultSection.Properties
  - System.Configuration.DefaultSection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.DefaultSection.ResetModified
  - System.Configuration.DefaultSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  langs:
  - csharp
  name: DefaultSection
  nameWithType: DefaultSection
  fullName: System.Configuration.DefaultSection
  type: Class
  summary: "代表組態區段的 XML 公開的讀取和寫入存取的基本組態區段處理常式。"
  remarks: "這是類型時所傳回的設計階段 API 會讀取區段中，未登錄於`<configSections>`> 一節。 此類型也會傳回已註冊的區段類型不是繼承自<xref:System.Configuration.ConfigurationSection>，就像使用章節，使用 ASP.NET 1.0 或 1.1<xref:System.Configuration.IConfigurationSectionHandler>型別。</xref:System.Configuration.IConfigurationSectionHandler> </xref:System.Configuration.ConfigurationSection>"
  syntax:
    content: 'public sealed class DefaultSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Configuration.DefaultSection.#ctor
  id: '#ctor'
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: DefaultSection()
  nameWithType: DefaultSection.DefaultSection()
  fullName: System.Configuration.DefaultSection.DefaultSection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.DefaultSection&quot;></xref>類別。"
  syntax:
    content: public DefaultSection ();
    parameters: []
  overload: System.Configuration.DefaultSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.DeserializeSection(System.Xml.XmlReader)
  id: DeserializeSection(System.Xml.XmlReader)
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: DeserializeSection(XmlReader)
  nameWithType: DefaultSection.DeserializeSection(XmlReader)
  fullName: System.Configuration.DefaultSection.DeserializeSection(XmlReader)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override void DeserializeSection (System.Xml.XmlReader xmlReader);
    parameters:
    - id: xmlReader
      type: System.Xml.XmlReader
      description: "即將加入。"
  overload: System.Configuration.DefaultSection.DeserializeSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.IsModified
  id: IsModified
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: IsModified()
  nameWithType: DefaultSection.IsModified()
  fullName: System.Configuration.DefaultSection.IsModified()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override bool IsModified ();
    parameters: []
    return:
      type: System.Boolean
      description: "即將加入。"
  overload: System.Configuration.DefaultSection.IsModified*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.Properties
  id: Properties
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: Properties
  nameWithType: DefaultSection.Properties
  fullName: System.Configuration.DefaultSection.Properties
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Configuration.DefaultSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: DefaultSection.Reset(ConfigurationElement)
  fullName: System.Configuration.DefaultSection.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentSection);
    parameters:
    - id: parentSection
      type: System.Configuration.ConfigurationElement
      description: "即將加入。"
  overload: System.Configuration.DefaultSection.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.ResetModified
  id: ResetModified
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: ResetModified()
  nameWithType: DefaultSection.ResetModified()
  fullName: System.Configuration.DefaultSection.ResetModified()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override void ResetModified ();
    parameters: []
  overload: System.Configuration.DefaultSection.ResetModified*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  id: SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  parent: System.Configuration.DefaultSection
  langs:
  - csharp
  name: SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
  nameWithType: DefaultSection.SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
  fullName: System.Configuration.DefaultSection.SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  syntax:
    content: protected override string SerializeSection (System.Configuration.ConfigurationElement parentSection, string name, System.Configuration.ConfigurationSaveMode saveMode);
    parameters:
    - id: parentSection
      type: System.Configuration.ConfigurationElement
      description: "即將加入。"
    - id: name
      type: System.String
      description: "即將加入。"
    - id: saveMode
      type: System.Configuration.ConfigurationSaveMode
      description: "即將加入。"
    return:
      type: System.String
      description: "即將加入。"
  overload: System.Configuration.DefaultSection.SerializeSection*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Configuration.DefaultSection.#ctor
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: DefaultSection()
  nameWithType: DefaultSection.DefaultSection()
  fullName: System.Configuration.DefaultSection.DefaultSection()
- uid: System.Configuration.DefaultSection.DeserializeSection(System.Xml.XmlReader)
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: DeserializeSection(XmlReader)
  nameWithType: DefaultSection.DeserializeSection(XmlReader)
  fullName: System.Configuration.DefaultSection.DeserializeSection(XmlReader)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Configuration.DefaultSection.IsModified
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: IsModified()
  nameWithType: DefaultSection.IsModified()
  fullName: System.Configuration.DefaultSection.IsModified()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.DefaultSection.Properties
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSection.Properties
  fullName: System.Configuration.DefaultSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.DefaultSection.Reset(System.Configuration.ConfigurationElement)
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: DefaultSection.Reset(ConfigurationElement)
  fullName: System.Configuration.DefaultSection.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Configuration.DefaultSection.ResetModified
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: ResetModified()
  nameWithType: DefaultSection.ResetModified()
  fullName: System.Configuration.DefaultSection.ResetModified()
- uid: System.Configuration.DefaultSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
  nameWithType: DefaultSection.SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
  fullName: System.Configuration.DefaultSection.SerializeSection(ConfigurationElement,String,ConfigurationSaveMode)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.DefaultSection.#ctor*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: DefaultSection
  nameWithType: DefaultSection.DefaultSection
- uid: System.Configuration.DefaultSection.DeserializeSection*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: DeserializeSection
  nameWithType: DefaultSection.DeserializeSection
- uid: System.Configuration.DefaultSection.IsModified*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: IsModified
  nameWithType: DefaultSection.IsModified
- uid: System.Configuration.DefaultSection.Properties*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: Properties
  nameWithType: DefaultSection.Properties
- uid: System.Configuration.DefaultSection.Reset*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: Reset
  nameWithType: DefaultSection.Reset
- uid: System.Configuration.DefaultSection.ResetModified*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: ResetModified
  nameWithType: DefaultSection.ResetModified
- uid: System.Configuration.DefaultSection.SerializeSection*
  parent: System.Configuration.DefaultSection
  isExternal: false
  name: SerializeSection
  nameWithType: DefaultSection.SerializeSection
