### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  id: EtwTrackingBehaviorElement
  children:
  - System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.#ctor
  - System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType
  - System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior
  - System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName
  - System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties
  langs:
  - csharp
  name: EtwTrackingBehaviorElement
  nameWithType: EtwTrackingBehaviorElement
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  type: Class
  summary: "建立及維護<xref href=&quot;System.ServiceModel.Activities.Description.EtwTrackingBehavior&quot;> </xref> Sql 工作流程組態檔的服務行為區段中的子元素。"
  remarks: "<xref:System.ServiceModel.Activities.Description.EtwTrackingBehavior>物件包含用來控制工作流程應用程式中事件追蹤行為設定。</xref:System.ServiceModel.Activities.Description.EtwTrackingBehavior>"
  syntax:
    content: 'public class EtwTrackingBehaviorElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  langs:
  - csharp
  name: EtwTrackingBehaviorElement()
  nameWithType: EtwTrackingBehaviorElement.EtwTrackingBehaviorElement()
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.EtwTrackingBehaviorElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "建立的新執行個體<xref href=&quot;System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement&quot;></xref>類別。"
  syntax:
    content: public EtwTrackingBehaviorElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: EtwTrackingBehaviorElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得型別<xref href=&quot;System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement&quot;></xref>執行個體。"
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "事件追蹤行為項目類型。"
  overload: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: EtwTrackingBehaviorElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "傳回的新執行個體<xref href=&quot;System.ServiceModel.Activities.Description.EtwTrackingBehavior&quot;></xref>類別。"
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "事件追蹤行為物件執行個體。"
  overload: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName
  id: ProfileName
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  langs:
  - csharp
  name: ProfileName
  nameWithType: EtwTrackingBehaviorElement.ProfileName
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得追蹤設定檔名稱參數事件追蹤行為項目。"
  remarks: "追蹤設定檔來篩選特定事件追蹤工作流程執行階段產生的資料。"
  syntax:
    content: public string ProfileName { get; set; }
    return:
      type: System.String
      description: "字串設定檔名稱。"
  overload: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  langs:
  - csharp
  name: Properties
  nameWithType: EtwTrackingBehaviorElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Configuration
  summary: "取得<xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref>目前事件追蹤行為項目。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "組態屬性的集合。"
  overload: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.#ctor
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: EtwTrackingBehaviorElement()
  nameWithType: EtwTrackingBehaviorElement.EtwTrackingBehaviorElement()
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.EtwTrackingBehaviorElement()
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: BehaviorType
  nameWithType: EtwTrackingBehaviorElement.BehaviorType
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: EtwTrackingBehaviorElement.CreateBehavior()
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: ProfileName
  nameWithType: EtwTrackingBehaviorElement.ProfileName
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: Properties
  nameWithType: EtwTrackingBehaviorElement.Properties
  fullName: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.#ctor*
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: EtwTrackingBehaviorElement
  nameWithType: EtwTrackingBehaviorElement.EtwTrackingBehaviorElement
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.BehaviorType*
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: BehaviorType
  nameWithType: EtwTrackingBehaviorElement.BehaviorType
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.CreateBehavior*
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: CreateBehavior
  nameWithType: EtwTrackingBehaviorElement.CreateBehavior
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.ProfileName*
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: ProfileName
  nameWithType: EtwTrackingBehaviorElement.ProfileName
- uid: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement.Properties*
  parent: System.ServiceModel.Activities.Configuration.EtwTrackingBehaviorElement
  isExternal: false
  name: Properties
  nameWithType: EtwTrackingBehaviorElement.Properties
