### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase
  id: EndpointAddressElementBase
  children:
  - System.ServiceModel.Configuration.EndpointAddressElementBase.#ctor
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  - System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(System.ServiceModel.EndpointAddress)
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Properties
  langs:
  - csharp
  name: EndpointAddressElementBase
  nameWithType: EndpointAddressElementBase
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase
  type: Class
  summary: "XML 項目，其中包含用戶端用來與服務端點通訊的唯一網路位址。"
  syntax:
    content: 'public class EndpointAddressElementBase : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: EndpointAddressElementBase()
  nameWithType: EndpointAddressElementBase.EndpointAddressElementBase()
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.EndpointAddressElementBase()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.EndpointAddressElementBase&quot;></xref>類別。"
  syntax:
    content: protected EndpointAddressElementBase ();
    parameters: []
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  id: Address
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: Address
  nameWithType: EndpointAddressElementBase.Address
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定端點的 URI。"
  syntax:
    content: public Uri Address { get; set; }
    return:
      type: System.Uri
      description: "<xref:System.Uri>識別端點的網路位置。</xref:System.Uri>"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  id: Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: Copy(EndpointAddressElementBase)
  nameWithType: EndpointAddressElementBase.Copy(EndpointAddressElementBase)
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(EndpointAddressElementBase)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "將指定的組態項目的內容複製到這個組態項目。"
  syntax:
    content: protected void Copy (System.ServiceModel.Configuration.EndpointAddressElementBase source);
    parameters:
    - id: source
      type: System.ServiceModel.Configuration.EndpointAddressElementBase
      description: "要複製的組態元素。"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>source</code>是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>或空白。"
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "設定為唯讀。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  id: Headers
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: Headers
  nameWithType: EndpointAddressElementBase.Headers
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得產生器可以建立之端點位址標頭的集合。"
  syntax:
    content: public System.ServiceModel.Configuration.AddressHeaderCollectionElement Headers { get; }
    return:
      type: System.ServiceModel.Configuration.AddressHeaderCollectionElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.AddressHeaderCollectionElement&quot;> </xref> ，其中包含端點的位址資訊。"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  id: Identity
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: Identity
  nameWithType: EndpointAddressElementBase.Identity
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得端點的身分識別。"
  syntax:
    content: public System.ServiceModel.Configuration.IdentityElement Identity { get; }
    return:
      type: System.ServiceModel.Configuration.IdentityElement
      description: "<xref href=&quot;System.ServiceModel.Configuration.IdentityElement&quot;> </xref>提供可讓其他端點交換訊息的端點驗證的識別。"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(System.ServiceModel.EndpointAddress)
  id: InitializeFrom(System.ServiceModel.EndpointAddress)
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: InitializeFrom(EndpointAddress)
  nameWithType: EndpointAddressElementBase.InitializeFrom(EndpointAddress)
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(EndpointAddress)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化這個端點位址與指定的端點位址的內容。"
  syntax:
    content: public void InitializeFrom (System.ServiceModel.EndpointAddress endpointAddress);
    parameters:
    - id: endpointAddress
      type: System.ServiceModel.EndpointAddress
      description: "端點位址。"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>endpointAddress</code>是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>或空白。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  langs:
  - csharp
  name: Properties
  nameWithType: EndpointAddressElementBase.Properties
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得<xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref>包含集合的執行個體<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>可能是屬性的物件或<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>這個組態項目的物件。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref>包含集合的執行個體<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>可能是屬性的物件或<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>這個組態項目的物件。"
  overload: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.#ctor
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: EndpointAddressElementBase()
  nameWithType: EndpointAddressElementBase.EndpointAddressElementBase()
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.EndpointAddressElementBase()
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Address
  nameWithType: EndpointAddressElementBase.Address
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Address
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Copy(EndpointAddressElementBase)
  nameWithType: EndpointAddressElementBase.Copy(EndpointAddressElementBase)
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(EndpointAddressElementBase)
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndpointAddressElementBase
  nameWithType: EndpointAddressElementBase
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Headers
  nameWithType: EndpointAddressElementBase.Headers
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
- uid: System.ServiceModel.Configuration.AddressHeaderCollectionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: AddressHeaderCollectionElement
  nameWithType: AddressHeaderCollectionElement
  fullName: System.ServiceModel.Configuration.AddressHeaderCollectionElement
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Identity
  nameWithType: EndpointAddressElementBase.Identity
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
- uid: System.ServiceModel.Configuration.IdentityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: IdentityElement
  nameWithType: IdentityElement
  fullName: System.ServiceModel.Configuration.IdentityElement
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(System.ServiceModel.EndpointAddress)
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: InitializeFrom(EndpointAddress)
  nameWithType: EndpointAddressElementBase.InitializeFrom(EndpointAddress)
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(EndpointAddress)
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Properties
  nameWithType: EndpointAddressElementBase.Properties
  fullName: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.#ctor*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: EndpointAddressElementBase
  nameWithType: EndpointAddressElementBase.EndpointAddressElementBase
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Address*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Address
  nameWithType: EndpointAddressElementBase.Address
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Copy*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Copy
  nameWithType: EndpointAddressElementBase.Copy
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Headers*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Headers
  nameWithType: EndpointAddressElementBase.Headers
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Identity*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Identity
  nameWithType: EndpointAddressElementBase.Identity
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: InitializeFrom
  nameWithType: EndpointAddressElementBase.InitializeFrom
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase.Properties*
  parent: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: Properties
  nameWithType: EndpointAddressElementBase.Properties
