### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidator
  id: CallbackValidator
  children:
  - System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  - System.Configuration.CallbackValidator.CanValidate(System.Type)
  - System.Configuration.CallbackValidator.Validate(System.Object)
  langs:
  - csharp
  name: CallbackValidator
  nameWithType: CallbackValidator
  fullName: System.Configuration.CallbackValidator
  type: Class
  summary: "提供物件的動態驗證。"
  remarks: "若要使用這個類別，您需要實作<xref:System.Configuration.ValidatorCallback>用於您想要驗證的物件類型的委派。</xref:System.Configuration.ValidatorCallback> 當您具現化這個類別時，您要傳入的物件類型和委派的參考。 您可以接著呼叫<xref:System.Configuration.CallbackValidator.CanValidate%2A>判斷物件是否為正確的型別或<xref:System.Configuration.CallbackValidator.Validate%2A>物件上執行委派。</xref:System.Configuration.CallbackValidator.Validate%2A> </xref:System.Configuration.CallbackValidator.CanValidate%2A>"
  syntax:
    content: 'public sealed class CallbackValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  id: '#ctor(System.Type,System.Configuration.ValidatorCallback)'
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.CallbackValidator&quot;></xref>類別。"
  syntax:
    content: public CallbackValidator (Type type, System.Configuration.ValidatorCallback callback);
    parameters:
    - id: type
      type: System.Type
      description: "將驗證的物件類型。"
    - id: callback
      type: System.Configuration.ValidatorCallback
      description: "<xref href=&quot;System.Configuration.ValidatorCallback&quot;> </xref>做為委派。"
  overload: System.Configuration.CallbackValidator.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>type </code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "判斷是否可以驗證的物件類型。"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "物件的類型。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;></xref>參數必須符合建立的執行個體時使用的第一個參數的型別<xref href=&quot;System.Configuration.CallbackValidator&quot;> </xref>，否則<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.CallbackValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "判斷物件的值是否有效。"
  remarks: "<xref:System.Configuration.CallbackValidator>類別包含的類型和委派需要驗證物件。</xref:System.Configuration.CallbackValidator> 執行個體時建立的類型和委派<xref:System.Configuration.CallbackValidator>類別建立。</xref:System.Configuration.CallbackValidator> 要驗證的物件會傳遞做為驗證方法的參數。"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "物件的值。"
  overload: System.Configuration.CallbackValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.CallbackValidator.#ctor(System.Type,System.Configuration.ValidatorCallback)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator(Type,ValidatorCallback)
  nameWithType: CallbackValidator.CallbackValidator(Type,ValidatorCallback)
  fullName: System.Configuration.CallbackValidator.CallbackValidator(Type,ValidatorCallback)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ValidatorCallback
  parent: System.Configuration
  isExternal: false
  name: ValidatorCallback
  nameWithType: ValidatorCallback
  fullName: System.Configuration.ValidatorCallback
- uid: System.Configuration.CallbackValidator.CanValidate(System.Type)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: CallbackValidator.CanValidate(Type)
  fullName: System.Configuration.CallbackValidator.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.CallbackValidator.Validate(System.Object)
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: CallbackValidator.Validate(Object)
  fullName: System.Configuration.CallbackValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.CallbackValidator.#ctor*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CallbackValidator
  nameWithType: CallbackValidator.CallbackValidator
- uid: System.Configuration.CallbackValidator.CanValidate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: CanValidate
  nameWithType: CallbackValidator.CanValidate
- uid: System.Configuration.CallbackValidator.Validate*
  parent: System.Configuration.CallbackValidator
  isExternal: false
  name: Validate
  nameWithType: CallbackValidator.Validate
