### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSaveMode
  id: ConfigurationSaveMode
  children:
  - System.Configuration.ConfigurationSaveMode.Full
  - System.Configuration.ConfigurationSaveMode.Minimal
  - System.Configuration.ConfigurationSaveMode.Modified
  langs:
  - csharp
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
  type: Enum
  summary: "決定哪些內容寫出至組態檔。"
  remarks: "ConfigurationSaveMode 列舉值會識別哪一個屬性會寫出至組態檔時呼叫<xref:System.Configuration.Configuration.Save%2A>和<xref:System.Configuration.Configuration.SaveAs%2A>方法。</xref:System.Configuration.Configuration.SaveAs%2A> </xref:System.Configuration.Configuration.Save%2A>"
  syntax:
    content: public enum ConfigurationSaveMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Full
  id: Full
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "導致要寫入至組態檔的所有屬性。 這是大部分用於建立設定檔的資訊或設定值移動到另一部電腦很有用。"
  syntax:
    content: Full
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  id: Minimal
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "會導致與繼承值寫入至組態檔不同的屬性。"
  syntax:
    content: Minimal
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSaveMode.Modified
  id: Modified
  parent: System.Configuration.ConfigurationSaveMode
  langs:
  - csharp
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "只有讓修改過的內容寫入組態檔中，即使值是繼承的值相同。"
  syntax:
    content: Modified
    return:
      type: System.Configuration.ConfigurationSaveMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationSaveMode.Full
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Full
  nameWithType: ConfigurationSaveMode.Full
  fullName: System.Configuration.ConfigurationSaveMode.Full
- uid: System.Configuration.ConfigurationSaveMode
  parent: System.Configuration
  isExternal: false
  name: ConfigurationSaveMode
  nameWithType: ConfigurationSaveMode
  fullName: System.Configuration.ConfigurationSaveMode
- uid: System.Configuration.ConfigurationSaveMode.Minimal
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Minimal
  nameWithType: ConfigurationSaveMode.Minimal
  fullName: System.Configuration.ConfigurationSaveMode.Minimal
- uid: System.Configuration.ConfigurationSaveMode.Modified
  parent: System.Configuration.ConfigurationSaveMode
  isExternal: false
  name: Modified
  nameWithType: ConfigurationSaveMode.Modified
  fullName: System.Configuration.ConfigurationSaveMode.Modified
