### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthenticationUser
  id: FormsAuthenticationUser
  children:
  - System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  - System.Web.Configuration.FormsAuthenticationUser.Name
  - System.Web.Configuration.FormsAuthenticationUser.Password
  - System.Web.Configuration.FormsAuthenticationUser.Properties
  langs:
  - csharp
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser
  fullName: System.Web.Configuration.FormsAuthenticationUser
  type: Class
  summary: "設定使用表單型驗證的 Web 應用程式的使用者的認證。"
  remarks: "FormsAuthenticationUser 類別可用來以程式設計方式存取和修改組態檔的區段。       此類型屬於的群組，其中包含<xref:System.Web.Configuration.FormsAuthenticationCredentials>、 <xref:System.Web.Configuration.FormsAuthenticationUserCollection>，而<xref:System.Web.Configuration.FormsAuthenticationConfiguration>型別。</xref:System.Web.Configuration.FormsAuthenticationConfiguration> </xref:System.Web.Configuration.FormsAuthenticationUserCollection> </xref:System.Web.Configuration.FormsAuthenticationCredentials> 集合型別以外的類型會直接影響基礎的組態標記。      > [!NOTE] > FormsAuthenticationUser 可將資訊寫入至位於機器、 網站或應用程式層級的組態檔的相關區段。 任何嘗試寫入階層中不同層級的組態檔中將會導致由剖析器產生的錯誤訊息。 不過，您可以使用這個類別來讀取階層架構中的任何層級的組態資訊。 基於安全性和延展性，建議您使用外部儲存機制，例如資料庫、 使用，來保留使用者的認證。"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.FormsAuthenticationUserCollection> to access the FormsAuthenticationUser objects of an existing Web application. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the [credentials Element for forms for authentication (ASP.NET Settings Schema)](http://msdn.microsoft.com/en-us/e5a001f8-fdbe-4c88-80ca-bfe36df23479) section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security, it is recommended you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authentication mode=\"Forms\">  \n  <forms name=\"MyAppCookieName\" loginUrl=\"/login.aspx\">  \n    defaultUrl=\"formsdefault.aspx\"  \n    protection=\"Encryption\" timeout=\"5\" path=\"aspnet\"  \n    slidingExpiration=\"false\"  \n    cookieless=\"UseCookies\" domain=\"domainName\">  \n    <credentials passwordFormat=\"SHA1\">  \n      <user name=\"aspnetuser1\"  \n        password=\"5BAA61E4C9B93F3F0682250B6CF8331B7EE68FD8\"/>  \n       <user name=\"aspnetuser2\"  \n         password=\"E38AD214943DAAD1D64C102FAEC29DE4AFE9DA3D\"/>  \n    </credentials>            \n  </forms>  \n</authentication>  \n```  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#1](~/add/codesnippet/csharp/t-system.web.configurati_51_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#1](~/add/codesnippet/visualbasic/t-system.web.configurati_51_1.vb)]"
  syntax:
    content: 'public sealed class FormsAuthenticationUser : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: FormsAuthenticationUser(String,String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.FormsAuthenticationUser&quot;></xref>類別使用傳遞的參數。"
  remarks: "這個建構函式會建立<xref:System.Web.Configuration.FormsAuthenticationUser>物件使用傳遞的參數。</xref:System.Web.Configuration.FormsAuthenticationUser>"
  example:
  - "The following code example shows how to create a <xref:System.Web.Configuration.FormsAuthenticationUser> object.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#3](~/add/codesnippet/csharp/ba248448-bbbd-40de-aba6-_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#3](~/add/codesnippet/visualbasic/ba248448-bbbd-40de-aba6-_1.vb)]"
  syntax:
    content: public FormsAuthenticationUser (string name, string password);
    parameters:
    - id: name
      type: System.String
      description: "使用者的名稱。"
    - id: password
      type: System.String
      description: "使用者的密碼。"
  overload: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  id: Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定登入使用者名稱。"
  remarks: ''
  example:
  - "The following code example shows how to use the Name property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#5](~/add/codesnippet/csharp/p-system.web.configurati_336_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#5](~/add/codesnippet/visualbasic/p-system.web.configurati_336_1.vb)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "應用程式所需要的登入使用者名稱。"
  overload: System.Web.Configuration.FormsAuthenticationUser.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  id: Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定使用者的密碼。"
  remarks: ''
  example:
  - "The following code example shows how to use the Password property. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUser> class topic to learn how to get the section.  \n  \n [!code-cs[System.Web.Configuration.FormsAuthenticationUser#4](~/add/codesnippet/csharp/p-system.web.configurati_127_1.cs)]\n [!code-vb[System.Web.Configuration.FormsAuthenticationUser#4](~/add/codesnippet/visualbasic/p-system.web.configurati_127_1.vb)]"
  syntax:
    content: public string Password { get; set; }
    return:
      type: System.String
      description: "應用程式所需的使用者的密碼。"
  overload: System.Web.Configuration.FormsAuthenticationUser.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  id: Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  langs:
  - csharp
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.FormsAuthenticationUser.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser(String,String)
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser(String,String)
  fullName: System.Web.Configuration.FormsAuthenticationUser.FormsAuthenticationUser(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FormsAuthenticationUser.Name
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
  fullName: System.Web.Configuration.FormsAuthenticationUser.Name
- uid: System.Web.Configuration.FormsAuthenticationUser.Password
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
  fullName: System.Web.Configuration.FormsAuthenticationUser.Password
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
  fullName: System.Web.Configuration.FormsAuthenticationUser.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FormsAuthenticationUser.#ctor*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: FormsAuthenticationUser
  nameWithType: FormsAuthenticationUser.FormsAuthenticationUser
- uid: System.Web.Configuration.FormsAuthenticationUser.Name*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Name
  nameWithType: FormsAuthenticationUser.Name
- uid: System.Web.Configuration.FormsAuthenticationUser.Password*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Password
  nameWithType: FormsAuthenticationUser.Password
- uid: System.Web.Configuration.FormsAuthenticationUser.Properties*
  parent: System.Web.Configuration.FormsAuthenticationUser
  isExternal: false
  name: Properties
  nameWithType: FormsAuthenticationUser.Properties
