### YamlMime:ManagedReference
items:
- uid: System.Configuration.PropertyValueOrigin
  id: PropertyValueOrigin
  children:
  - System.Configuration.PropertyValueOrigin.Default
  - System.Configuration.PropertyValueOrigin.Inherited
  - System.Configuration.PropertyValueOrigin.SetHere
  langs:
  - csharp
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
  type: Enum
  summary: "組態屬性值的發生位置的組態階層架構中指定的層級。"
  syntax:
    content: public enum PropertyValueOrigin
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.Default
  id: Default
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "組態屬性值來自<xref:System.Configuration.ConfigurationProperty.DefaultValue*>屬性。</xref:System.Configuration.ConfigurationProperty.DefaultValue*>"
  syntax:
    content: Default
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.Inherited
  id: Inherited
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "組態屬性值繼承自父層級組態中。"
  syntax:
    content: Inherited
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PropertyValueOrigin.SetHere
  id: SetHere
  parent: System.Configuration.PropertyValueOrigin
  langs:
  - csharp
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "設定內容值定義之階層的目前層級。"
  syntax:
    content: SetHere
    return:
      type: System.Configuration.PropertyValueOrigin
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.PropertyValueOrigin.Default
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Default
  nameWithType: PropertyValueOrigin.Default
  fullName: System.Configuration.PropertyValueOrigin.Default
- uid: System.Configuration.PropertyValueOrigin
  parent: System.Configuration
  isExternal: false
  name: PropertyValueOrigin
  nameWithType: PropertyValueOrigin
  fullName: System.Configuration.PropertyValueOrigin
- uid: System.Configuration.PropertyValueOrigin.Inherited
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: Inherited
  nameWithType: PropertyValueOrigin.Inherited
  fullName: System.Configuration.PropertyValueOrigin.Inherited
- uid: System.Configuration.PropertyValueOrigin.SetHere
  parent: System.Configuration.PropertyValueOrigin
  isExternal: false
  name: SetHere
  nameWithType: PropertyValueOrigin.SetHere
  fullName: System.Configuration.PropertyValueOrigin.SetHere
