### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "指定應用程式設定屬性具有共通的值，應用程式的所有使用者。 這個類別無法被繼承。"
  remarks: "應用程式設定屬性具有，取決於應用程式或使用者層級的範圍。 如分類所暗示，應用程式範圍的設定屬性則會顯示統一值給所有使用者的應用程式，而使用者範圍的屬性具有專用應用程式的每位使用者的值。       ApplicationScopedSettingAttribute 表示屬性應該被視為應用程式層級設定，而且，要據以進行適當的儲存體決策設定提供者。       需要為每個設定的屬性範圍屬性。 如果屬性不會套用與任一 ApplicationScopedSettingAttribute 或<xref:System.Configuration.UserScopedSettingAttribute>，設定提供者無法辨識的屬性，都沒有序列化。</xref:System.Configuration.UserScopedSettingAttribute> 是無效的不過，若要將這兩個屬性套用至相同的屬性。 這類的嘗試會導致<xref:System.Configuration.ConfigurationErrorsException>擲回。</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;></xref>類別。"
  remarks: "每個應用程式設定屬性必須套用具有單一領域屬性，才能讓它辨識和序列化的設定提供者。"
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
