### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.NamespaceInfo
  id: NamespaceInfo
  children:
  - System.Web.Configuration.NamespaceInfo.#ctor(System.String)
  - System.Web.Configuration.NamespaceInfo.Equals(System.Object)
  - System.Web.Configuration.NamespaceInfo.GetHashCode
  - System.Web.Configuration.NamespaceInfo.Namespace
  - System.Web.Configuration.NamespaceInfo.Properties
  langs:
  - csharp
  name: NamespaceInfo
  nameWithType: NamespaceInfo
  fullName: System.Web.Configuration.NamespaceInfo
  type: Class
  summary: "包含單一組態命名空間的參考，類似於<xref uid=&quot;langword_csharp_Import&quot; name=&quot;Import&quot; href=&quot;&quot;></xref>指示詞。 這個類別無法被繼承。"
  remarks: "<xref:System.Web.Configuration.NamespaceCollection>包含 NamespaceInfo 物件，其對應至`add`內的項目`namespaces`> 一節。</xref:System.Web.Configuration.NamespaceCollection> 每個 NamespaceInfo 物件等同於`Import`(`%@ Import %`>)，可以套用到所有頁面，並控制在組態檔的範圍內指示詞。 `Import`指示詞可讓您匯入到您的 ASP.NET 網頁，因此它的類別可以使用您的頁面上的命名空間。"
  example:
  - "This example demonstrates how to specify values declaratively for properties of the <xref:System.Web.Configuration.NamespaceCollection> and NamespaceInfo classes.  \n  \n The following configuration file example shows how to specify values declaratively for the `namespaces` section.  \n  \n```  \n  \n<system.web>  \n  <pages>  \n    <namespaces>  \n      <add namespace=\"System\" />  \n      <add namespace=\"System.Collections\" />  \n      <add namespace=\"System.Collections.Specialized\" />  \n      <add namespace=\"System.ComponentModel\" />  \n      <add namespace=\"System.Configuration\" />  \n      <add namespace=\"System.Web\" />  \n    </namespaces>  \n  </pages>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the NamespaceInfo class. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#22](~/add/codesnippet/csharp/t-system.web.configurati_1_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#22](~/add/codesnippet/visualbasic/t-system.web.configurati_1_1.vb)]"
  syntax:
    content: 'public sealed class NamespaceInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.NamespaceInfo.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Configuration.NamespaceInfo
  langs:
  - csharp
  name: NamespaceInfo(String)
  nameWithType: NamespaceInfo.NamespaceInfo(String)
  fullName: System.Web.Configuration.NamespaceInfo.NamespaceInfo(String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.NamespaceInfo&quot;></xref>類別具有指定的命名空間參考。"
  remarks: "不會執行驗證來驗證命名空間參考有效。"
  example:
  - "The following code example shows how to use NamespaceInfo constructor. It is part of a larger example for the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#23](~/add/codesnippet/csharp/m-system.web.configurati_24_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#23](~/add/codesnippet/visualbasic/m-system.web.configurati_24_1.vb)]"
  syntax:
    content: public NamespaceInfo (string name);
    parameters:
    - id: name
      type: System.String
      description: "新的命名空間參考<xref href=&quot;System.Web.Configuration.NamespaceInfo&quot;></xref>物件。"
  overload: System.Web.Configuration.NamespaceInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.NamespaceInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.NamespaceInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: NamespaceInfo.Equals(Object)
  fullName: System.Web.Configuration.NamespaceInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "比較目前的執行個體，與傳入<xref href=&quot;System.Web.Configuration.NamespaceInfo&quot;></xref>物件。"
  syntax:
    content: public override bool Equals (object namespaceInformation);
    parameters:
    - id: namespaceInformation
      type: System.Object
      description: "A <xref href=&quot;System.Web.Configuration.NamespaceInfo&quot;> </xref>来比較的物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果兩個物件相同。"
  overload: System.Web.Configuration.NamespaceInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.NamespaceInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.NamespaceInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: NamespaceInfo.GetHashCode()
  fullName: System.Web.Configuration.NamespaceInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "傳回目前執行個體的雜湊值。"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "目前的執行個體的雜湊值。"
  overload: System.Web.Configuration.NamespaceInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.NamespaceInfo.Namespace
  id: Namespace
  parent: System.Web.Configuration.NamespaceInfo
  langs:
  - csharp
  name: Namespace
  nameWithType: NamespaceInfo.Namespace
  fullName: System.Web.Configuration.NamespaceInfo.Namespace
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定命名空間參考。"
  remarks: "不會執行驗證來驗證命名空間參考有效。"
  example:
  - "The following code example shows how to use the Namespace property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#29](~/add/codesnippet/csharp/p-system.web.configurati_393_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#29](~/add/codesnippet/visualbasic/p-system.web.configurati_393_1.vb)]"
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "字串，指定的命名空間名稱。"
  overload: System.Web.Configuration.NamespaceInfo.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.NamespaceInfo.Properties
  id: Properties
  parent: System.Web.Configuration.NamespaceInfo
  langs:
  - csharp
  name: Properties
  nameWithType: NamespaceInfo.Properties
  fullName: System.Web.Configuration.NamespaceInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.NamespaceInfo.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.NamespaceInfo.#ctor(System.String)
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: NamespaceInfo(String)
  nameWithType: NamespaceInfo.NamespaceInfo(String)
  fullName: System.Web.Configuration.NamespaceInfo.NamespaceInfo(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.NamespaceInfo.Equals(System.Object)
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: NamespaceInfo.Equals(Object)
  fullName: System.Web.Configuration.NamespaceInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.NamespaceInfo.GetHashCode
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: NamespaceInfo.GetHashCode()
  fullName: System.Web.Configuration.NamespaceInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.NamespaceInfo.Namespace
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Namespace
  nameWithType: NamespaceInfo.Namespace
  fullName: System.Web.Configuration.NamespaceInfo.Namespace
- uid: System.Web.Configuration.NamespaceInfo.Properties
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Properties
  nameWithType: NamespaceInfo.Properties
  fullName: System.Web.Configuration.NamespaceInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.NamespaceInfo.#ctor*
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: NamespaceInfo
  nameWithType: NamespaceInfo.NamespaceInfo
- uid: System.Web.Configuration.NamespaceInfo.Equals*
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Equals
  nameWithType: NamespaceInfo.Equals
- uid: System.Web.Configuration.NamespaceInfo.GetHashCode*
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: GetHashCode
  nameWithType: NamespaceInfo.GetHashCode
- uid: System.Web.Configuration.NamespaceInfo.Namespace*
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Namespace
  nameWithType: NamespaceInfo.Namespace
- uid: System.Web.Configuration.NamespaceInfo.Properties*
  parent: System.Web.Configuration.NamespaceInfo
  isExternal: false
  name: Properties
  nameWithType: NamespaceInfo.Properties
