### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.MsmqTransportSecurity
  id: MsmqTransportSecurity
  children:
  - System.ServiceModel.MsmqTransportSecurity.#ctor
  - System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  - System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  - System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  - System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  - System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  langs:
  - csharp
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
  type: Class
  summary: "MsmqTransportSecurity 類別會封裝佇列傳輸的傳輸安全性設定。"
  syntax:
    content: public sealed class MsmqTransportSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  syntax:
    content: public MsmqTransportSecurity ();
    parameters: []
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  id: '#ctor(System.ServiceModel.MsmqTransportSecurity)'
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別，使用現有的執行個體。"
  syntax:
    content: public MsmqTransportSecurity (System.ServiceModel.MsmqTransportSecurity other);
    parameters:
    - id: other
      type: System.ServiceModel.MsmqTransportSecurity
      description: "現有的執行個體<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別，以用來初始化新執行個體。"
  overload: System.ServiceModel.MsmqTransportSecurity.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>other</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  id: MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;></xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  remarks: "MSMQ 可以驗證傳送至需要驗證，訊息佇列的訊息或訊息可以明確要求驗證。 預設的驗證模式為<xref:System.ServiceModel.MsmqAuthenticationMode>。</xref:System.ServiceModel.MsmqAuthenticationMode>"
  syntax:
    content: public System.ServiceModel.MsmqAuthenticationMode MsmqAuthenticationMode { get; set; }
    return:
      type: System.ServiceModel.MsmqAuthenticationMode
      description: "<xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;> </xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "值不是其中一個<xref href=&quot;System.ServiceModel.MsmqAuthenticationMode&quot;></xref>值。"
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  id: MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;></xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  remarks: "MSMQ 可以加密在網路上的訊息，訊息佇列管理員之間傳輸訊息時。 預設加密演算法為<xref:System.ServiceModel.MsmqEncryptionAlgorithm>。</xref:System.ServiceModel.MsmqEncryptionAlgorithm>"
  syntax:
    content: public System.ServiceModel.MsmqEncryptionAlgorithm MsmqEncryptionAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqEncryptionAlgorithm
      description: "<xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;> </xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "值不是其中一個<xref href=&quot;System.ServiceModel.MsmqEncryptionAlgorithm&quot;></xref>值。"
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  id: MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.Net.Security.ProtectionLevel&quot;></xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  remarks: "預設保護層級為<xref:System.Net.Security.ProtectionLevel>。</xref:System.Net.Security.ProtectionLevel>"
  syntax:
    content: public System.Net.Security.ProtectionLevel MsmqProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "<xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "值不是其中一個<xref href=&quot;System.Net.Security.ProtectionLevel&quot;></xref>值。"
  platform:
  - net462
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  id: MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  langs:
  - csharp
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "取得或設定<xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;></xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  remarks: "預設的雜湊演算法是<xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>.</xref:System.ServiceModel.MsmqSecureHashAlgorithm.SHA1>"
  syntax:
    content: public System.ServiceModel.MsmqSecureHashAlgorithm MsmqSecureHashAlgorithm { get; set; }
    return:
      type: System.ServiceModel.MsmqSecureHashAlgorithm
      description: "<xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;> </xref>與這個執行個體相關聯<xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;></xref>類別。"
  overload: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "值不是其中一個<xref href=&quot;System.ServiceModel.MsmqSecureHashAlgorithm&quot;></xref>值。"
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity()
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity()
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity()
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor(System.ServiceModel.MsmqTransportSecurity)
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity(MsmqTransportSecurity)
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqTransportSecurity(MsmqTransportSecurity)
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqAuthenticationMode
  parent: System.ServiceModel
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqAuthenticationMode
  fullName: System.ServiceModel.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqEncryptionAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqEncryptionAlgorithm
  fullName: System.ServiceModel.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqSecureHashAlgorithm
  parent: System.ServiceModel
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqSecureHashAlgorithm
  fullName: System.ServiceModel.MsmqSecureHashAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.#ctor*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity.MsmqTransportSecurity
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqAuthenticationMode*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqAuthenticationMode
  nameWithType: MsmqTransportSecurity.MsmqAuthenticationMode
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqEncryptionAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqEncryptionAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqEncryptionAlgorithm
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqProtectionLevel*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqProtectionLevel
  nameWithType: MsmqTransportSecurity.MsmqProtectionLevel
- uid: System.ServiceModel.MsmqTransportSecurity.MsmqSecureHashAlgorithm*
  parent: System.ServiceModel.MsmqTransportSecurity
  isExternal: false
  name: MsmqSecureHashAlgorithm
  nameWithType: MsmqTransportSecurity.MsmqSecureHashAlgorithm
