### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TicketCompatibilityMode
  id: TicketCompatibilityMode
  children:
  - System.Web.Configuration.TicketCompatibilityMode.Framework20
  - System.Web.Configuration.TicketCompatibilityMode.Framework40
  langs:
  - csharp
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
  type: Enum
  summary: "定義是否要使用表單驗證票證到期日 Coordinated Universal Time (UTC) 或本地時間。"
  remarks: "使用國際標準時間 (UTC) 或本地時間可以儲存 ASP.NET 表單驗證票證到期日。 應用程式之間的相容性和.NET Framework 的不同版本之間的相容性，可以藉由指定票證到期時間`ticketCompatilityMode`項目的屬性。 預設值為`ticketCompatibilityMode`屬性是 Framework20。"
  example:
  - "The following example configures the forms authentication ticket expiration date as UTC time.  \n  \n```  \n<system.web>  \n  <authentication mode=\"Forms\">   \n    <forms ticketCompatilityMode=\"Framework40\">  \n    </forms>  \n  </authentication>  \n</system.web>  \n```"
  syntax:
    content: public enum TicketCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定票證到期日儲存為當地時間。 這是預設值。"
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定票證到期日會儲存為 UTC。"
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
- uid: System.Web.Configuration.TicketCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
