### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  id: CustomErrorsRedirectMode
  children:
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  langs:
  - csharp
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
  type: Enum
  summary: "指定自訂錯誤頁面顯示時，如何處理原始要求的 URL 的值。"
  remarks: "當您設定時，使用 CustomErrorsRedirectMode 值<xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>屬性。</xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>"
  syntax:
    content: public enum CustomErrorsRedirectMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  id: ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "顯示錯誤頁面，然後將原始要求的 URL。"
  syntax:
    content: ResponseRedirect
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  id: ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "顯示錯誤頁面，而不需要變更的原始 URL。"
  syntax:
    content: ResponseRewrite
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
