### YamlMime:ManagedReference
items:
- uid: System.Xml.IApplicationResourceStreamResolver
  id: IApplicationResourceStreamResolver
  children:
  - System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  langs:
  - csharp
  name: IApplicationResourceStreamResolver
  nameWithType: IApplicationResourceStreamResolver
  fullName: System.Xml.IApplicationResourceStreamResolver
  type: Interface
  summary: "表示應用程式資源資料流解析程式。"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      [System.Obsolete("This API supports the .NET Framework infrastructure and is not intended to be used directly from your code.", true)]

      public interface IApplicationResourceStreamResolver
  implements: []
  platform:
  - net462
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  id: GetApplicationResourceStream(System.Uri)
  parent: System.Xml.IApplicationResourceStreamResolver
  langs:
  - csharp
  name: GetApplicationResourceStream(Uri)
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  fullName: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  type: Method
  assemblies:
  - System.Xml
  namespace: System.Xml
  summary: "傳回指定之 URI 的應用程式資源資料流。"
  syntax:
    content: public System.IO.Stream GetApplicationResourceStream (Uri relativeUri);
    parameters:
    - id: relativeUri
      type: System.Uri
      description: "相對的 URI。"
    return:
      type: System.IO.Stream
      description: "應用程式資源資料流。"
  overload: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(System.Uri)
  parent: System.Xml.IApplicationResourceStreamResolver
  isExternal: false
  name: GetApplicationResourceStream(Uri)
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
  fullName: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream(Uri)
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xml.IApplicationResourceStreamResolver.GetApplicationResourceStream*
  parent: System.Xml.IApplicationResourceStreamResolver
  isExternal: false
  name: GetApplicationResourceStream
  nameWithType: IApplicationResourceStreamResolver.GetApplicationResourceStream
