### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadManager
  id: IApplicationPreloadManager
  children:
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  langs:
  - csharp
  name: IApplicationPreloadManager
  nameWithType: IApplicationPreloadManager
  fullName: System.Web.Hosting.IApplicationPreloadManager
  type: Interface
  summary: "提供 ASP.NET 用來叫用中的應用程式預先載入功能方法[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("AE54F424-71BC-4da5-AA2F-8C0CD53496FC")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadManager
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  id: SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "由呼叫[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]通知 ASP.NET 應用程式是否應該預先載入。"
  syntax:
    content: public void SetApplicationPreloadState (string context, string appId, bool enabled);
    parameters:
    - id: context
      type: System.String
      description: "應用程式內容。"
    - id: appId
      type: System.String
      description: "應用程式的唯一識別碼。"
    - id: enabled
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>表示，就應該預先載入應用程式。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  id: SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "呼叫[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]取得預先載入應用程式所需的資訊。"
  remarks: "IIS 會呼叫 ASP.NET 透過這個介面，提供物件，用於實作的參考<xref:System.Web.Hosting.IApplicationPreloadUtil>介面。</xref:System.Web.Hosting.IApplicationPreloadUtil> ASP.NET 會使用該介面稍後執行回呼 iis 以取得個別應用程式預先載入的資訊。"
  syntax:
    content: public void SetApplicationPreloadUtil (System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
    parameters:
    - id: preloadUtil
      type: System.Web.Hosting.IApplicationPreloadUtil
      description: "Unmanaged 介面中的控制代碼[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]該 ASP.NET 呼叫來取得資訊。"
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
- uid: System.Web.Hosting.IApplicationPreloadUtil
  parent: System.Web.Hosting
  isExternal: false
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil
