### YamlMime:ManagedReference
items:
- uid: System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  langs:
  - csharp
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  summary: "指定的值<xref:System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent*>.</xref:System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent*> 可能的值為<xref uid=&quot;langword_csharp_ReadWrite&quot; name=&quot;ReadWrite&quot; href=&quot;&quot;></xref>和<xref uid=&quot;langword_csharp_ReadOnly&quot; name=&quot;ReadOnly&quot; href=&quot;&quot;> </xref>。"
  syntax:
    content: public enum ApplicationIntent
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  summary: "連接到伺服器時，才會進行應用程式工作負載類型是唯讀的。"
  syntax:
    content: ReadOnly
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  assemblies:
  - System.Data
  namespace: System.Data.SqlClient
  summary: "連接到伺服器時，才會進行應用程式工作負載類型是可讀寫。"
  syntax:
    content: ReadWrite
    return:
      type: System.Data.SqlClient.ApplicationIntent
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
- uid: System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  isExternal: false
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
