### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  id: SoapEnvelopeProcessingElement
  children:
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  - System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  type: Class
  summary: "設定逾時，可協助降低阻絕服務攻擊所終止的時間超過任何要求<xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>屬性值。</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*>"
  remarks: "逾時值會檢查在每次呼叫<xref:System.Xml.XmlReader.Read%2A>和<xref:System.Xml.XmlReader.MoveToContent%2A>。</xref:System.Xml.XmlReader.MoveToContent%2A> </xref:System.Xml.XmlReader.Read%2A>"
  syntax:
    content: 'public sealed class SoapEnvelopeProcessingElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;></xref>類別。"
  syntax:
    content: public SoapEnvelopeProcessingElement ();
    parameters: []
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  id: '#ctor(System.Int32)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Services.Configuration.SoapEnvelopeProcessingElement&quot;></xref>類別使用提供<xref:System.Int32>值。</xref:System.Int32>"
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "逾時期限的值。"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  id: '#ctor(System.Int32,System.Boolean)'
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得或設定用來判斷是否要終止要求，以降低阻絕服務攻擊的逾時期限。"
  syntax:
    content: public SoapEnvelopeProcessingElement (int readTimeout, bool strict);
    parameters:
    - id: readTimeout
      type: System.Int32
      description: "要求結束之前的等待時間<> *> 和<> *>。"
    - id: strict
      type: System.Boolean
      description: "是否要擲回例外狀況的序列化程式遭遇項目或屬性 (attribute) 的原始結構描述中。 如需詳細資訊，請參閱<xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>屬性。</xref:System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*>"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  id: IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得或設定值，指出是否要擲回例外狀況的序列化程式遭遇非預期的元素或屬性。"
  remarks: "將 IsStrict 屬性設定為`true`以協助偵錯互通的案例。 在一般情況下，當<xref:System.Xml.Serialization.XmlSerializer>類別符合的元素或屬性，它不會預期它會引發<xref:System.Xml.Serialization.XmlSerializer.UnknownNode>事件，並繼續處理。</xref:System.Xml.Serialization.XmlSerializer.UnknownNode> </xref:System.Xml.Serialization.XmlSerializer> (也是如此當<xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A>， <xref:System.Xml.Serialization.XmlElementAttribute.Order%2A>，或<xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A>屬性使用，但資料會傳送順序。)</xref:System.Xml.Serialization.XmlAnyElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlElementAttribute.Order%2A> </xref:System.Xml.Serialization.XmlArrayAttribute.Order%2A>IsStrict 屬性設定為`true`指示的 Web 服務執行階段處理該事件，並擲回<xref:System.InvalidOperationException>包含預期的項目和屬性的清單。</xref:System.InvalidOperationException>      > [!NOTE] > 所有非預期的元素和屬性不會擲回例外狀況，因為 IsStrict 屬性應該不依賴除了做為偵錯輔助工具。 例如，非預期`xml:lang`和`xml:space`屬性不會導致例外狀況。"
  syntax:
    content: public bool IsStrict { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果 Web 服務的序列化程式會嘗試偵測到非預期的元素或屬性;否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  id: ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  langs:
  - csharp
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "取得或設定用來判斷是否要終止要求，以降低阻絕服務攻擊的逾時期限。"
  syntax:
    content: public int ReadTimeout { get; set; }
    return:
      type: System.Int32
      description: "要求結束之前的等待時間<> *> 和<> *>。"
  overload: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement()
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement()
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor(System.Int32,System.Boolean)
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement(Int32,Boolean)
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement(Int32,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
  fullName: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.#ctor*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: SoapEnvelopeProcessingElement
  nameWithType: SoapEnvelopeProcessingElement.SoapEnvelopeProcessingElement
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.IsStrict*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: IsStrict
  nameWithType: SoapEnvelopeProcessingElement.IsStrict
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.Properties*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: Properties
  nameWithType: SoapEnvelopeProcessingElement.Properties
- uid: System.Web.Services.Configuration.SoapEnvelopeProcessingElement.ReadTimeout*
  parent: System.Web.Services.Configuration.SoapEnvelopeProcessingElement
  isExternal: false
  name: ReadTimeout
  nameWithType: SoapEnvelopeProcessingElement.ReadTimeout
