### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  id: ScriptingProfileServiceSection
  children:
  - System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  - System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  - System.Web.Configuration.ScriptingProfileServiceSection.Properties
  - System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  - System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  langs:
  - csharp
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
  type: Class
  summary: "表示組態區段的設定檔服務的設定。 這個類別無法被繼承。"
  remarks: "ScriptingProfileServiceSection 類別可讓您以程式設計方式存取和修改`profileService`使用 AJAX 功能的 ASP.NET 應用程式的組態區段的項目。       設定檔服務用來取得及設定與目前的要求相關聯之使用者識別的設定檔屬性。 這表示設定檔服務適用於已驗證的使用者。 它也適用於匿名使用者已啟用 （或提供） 的匿名識別功能時在組態檔中。"
  example:
  - "The following example shows how to declaratively specify values for properties of the ScriptingProfileServiceSection class in a configuration file.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <profileService enabled=\"true\"   \n        readAccessProperties=\"FirstName,LastName\"   \n        writeAccessProperties=\"FirstName,LastName\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example shows how to access the ScriptingProfileServiceSection section programmatically.  \n  \n [!code-cs[System.Web.Configuration#2](~/add/codesnippet/csharp/t-system.web.configurati_50_1.cs)]\n [!code-vb[System.Web.Configuration#2](~/add/codesnippet/visualbasic/t-system.web.configurati_50_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingProfileServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.ScriptingProfileServiceSection&quot;></xref>類別。"
  syntax:
    content: public ScriptingProfileServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得或設定值，這個值，指出是否已啟用 AJAX 的 ASP.NET 應用程式中提供設定檔服務。"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果已啟用設定檔服務。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  id: ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得或設定讀取權限設定檔內容。"
  remarks: "若要使用 ajax 能力的應用程式中的讀取權限設定檔屬性，加入 ReadAccessProperties 屬性中的一個或多個設定檔屬性名稱。       您可以設定 ReadAccessProperties 為空白的字串陣列。 這表示，設定檔不允許任何屬性来讀取的用戶端指令碼。"
  syntax:
    content: public string[] ReadAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "陣列，其中包含的讀取權限設定檔屬性的名稱。"
  overload: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  id: WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "取得或設定寫入權限設定檔屬性。"
  remarks: "若要使用的寫入存取設定檔屬性已啟用 AJAX 的應用程式中，加入 WriteAccessProperties 屬性中的一個或多個設定檔屬性名稱。       您可以設定 WriteAccessProperties 為空白的字串陣列。 這表示，設定檔不允許任何屬性來設定用戶端指令碼。"
  syntax:
    content: public string[] WriteAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "陣列，其中包含寫入權限設定檔屬性的名稱。"
  overload: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
