### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.NetSectionGroup
  id: NetSectionGroup
  children:
  - System.Net.Configuration.NetSectionGroup.#ctor
  - System.Net.Configuration.NetSectionGroup.AuthenticationModules
  - System.Net.Configuration.NetSectionGroup.ConnectionManagement
  - System.Net.Configuration.NetSectionGroup.DefaultProxy
  - System.Net.Configuration.NetSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  - System.Net.Configuration.NetSectionGroup.MailSettings
  - System.Net.Configuration.NetSectionGroup.RequestCaching
  - System.Net.Configuration.NetSectionGroup.Settings
  - System.Net.Configuration.NetSectionGroup.WebRequestModules
  langs:
  - csharp
  name: NetSectionGroup
  nameWithType: NetSectionGroup
  fullName: System.Net.Configuration.NetSectionGroup
  type: Class
  summary: "取得網路命名空間的區段群組資訊。 這個類別無法被繼承。"
  remarks: "This class corresponds to the [\\&lt;system.Net\\&gt; Element (Network Settings)](../Topic/%3Csystem.Net%3E%20Element%20\\(Network%20Settings\\).md) configuration element described in the [Network Settings Schema](~/add/includes/ajax-current-ext-md.md) documentation.  \n  \n This section group controls configuration settings for the following namespaces:  \n  \n-   <xref:System.Net>  \n  \n-   <xref:System.Net.Cache>  \n  \n-   <xref:System.Net.Mail>  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class NetSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: NetSectionGroup()
  nameWithType: NetSectionGroup.NetSectionGroup()
  fullName: System.Net.Configuration.NetSectionGroup.NetSectionGroup()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Net.Configuration.NetSectionGroup&quot;></xref>類別。"
  remarks: "這個建構函式沒有任何作用。"
  syntax:
    content: public NetSectionGroup ();
    parameters: []
  overload: System.Net.Configuration.NetSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.AuthenticationModules
  id: AuthenticationModules
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: AuthenticationModules
  nameWithType: NetSectionGroup.AuthenticationModules
  fullName: System.Net.Configuration.NetSectionGroup.AuthenticationModules
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含註冊本機電腦的驗證模組的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; authenticationModules\\&gt;項目 （網路設定）](../Topic/%3CauthenticationModules%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.AuthenticationModulesSection AuthenticationModules { get; }
    return:
      type: System.Net.Configuration.AuthenticationModulesSection
      description: "A <xref href=&quot;System.Net.Configuration.AuthenticationModulesSection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.AuthenticationModules*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.ConnectionManagement
  id: ConnectionManagement
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: ConnectionManagement
  nameWithType: NetSectionGroup.ConnectionManagement
  fullName: System.Net.Configuration.NetSectionGroup.ConnectionManagement
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含在本機電腦的連線管理設定的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; connectionManagement\\&gt;項目 （網路設定）](../Topic/%3CconnectionManagement%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.ConnectionManagementSection ConnectionManagement { get; }
    return:
      type: System.Net.Configuration.ConnectionManagementSection
      description: "A <xref href=&quot;System.Net.Configuration.ConnectionManagementSection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.ConnectionManagement*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.DefaultProxy
  id: DefaultProxy
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: DefaultProxy
  nameWithType: NetSectionGroup.DefaultProxy
  fullName: System.Net.Configuration.NetSectionGroup.DefaultProxy
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含在本機電腦的預設 Web proxy 伺服器設定的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; defaultProxy\\&gt;項目 （網路設定）](../Topic/%3CdefaultProxy%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.DefaultProxySection DefaultProxy { get; }
    return:
      type: System.Net.Configuration.DefaultProxySection
      description: "A <xref href=&quot;System.Net.Configuration.DefaultProxySection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.DefaultProxy*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  id: GetSectionGroup(System.Configuration.Configuration)
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: GetSectionGroup(Configuration)
  nameWithType: NetSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Net.Configuration.NetSectionGroup.GetSectionGroup(Configuration)
  type: Method
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得<xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;></xref>從指定的組態檔的組態區段群組。"
  remarks: "使用這個方法從組態檔中擷取網路設定。"
  syntax:
    content: public static System.Net.Configuration.NetSectionGroup GetSectionGroup (System.Configuration.Configuration config);
    parameters:
    - id: config
      type: System.Configuration.Configuration
      description: "A <xref href=&quot;System.Configuration.Configuration&quot;> </xref>表示組態檔。"
    return:
      type: System.Net.Configuration.NetSectionGroup
      description: "A <xref href=&quot;System.Net.Configuration.NetSectionGroup&quot;></xref> that represents the <xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;></xref> settings in <code>config</code>."
  overload: System.Net.Configuration.NetSectionGroup.GetSectionGroup*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.MailSettings
  id: MailSettings
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: MailSettings
  nameWithType: NetSectionGroup.MailSettings
  fullName: System.Net.Configuration.NetSectionGroup.MailSettings
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含用戶端電子郵件的 SMTP 設定本機電腦的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; mailSettings\\&gt;項目 （網路設定）](../Topic/%3CmailSettings%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.MailSettingsSectionGroup MailSettings { get; }
    return:
      type: System.Net.Configuration.MailSettingsSectionGroup
      description: "A <xref href=&quot;System.Net.Configuration.MailSettingsSectionGroup&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.MailSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.RequestCaching
  id: RequestCaching
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: RequestCaching
  nameWithType: NetSectionGroup.RequestCaching
  fullName: System.Net.Configuration.NetSectionGroup.RequestCaching
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含在本機電腦的快取組態設定的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; requestCaching\\&gt;項目 （網路設定）](../Topic/%3CrequestCaching%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.RequestCachingSection RequestCaching { get; }
    return:
      type: System.Net.Configuration.RequestCachingSection
      description: "A <xref href=&quot;System.Net.Configuration.RequestCachingSection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.RequestCaching*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.Settings
  id: Settings
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: Settings
  nameWithType: NetSectionGroup.Settings
  fullName: System.Net.Configuration.NetSectionGroup.Settings
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得包含在本機電腦的網路設定的組態區段。"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; 設定\\&gt;項目 （網路設定）](../Topic/%3Csettings%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.SettingsSection Settings { get; }
    return:
      type: System.Net.Configuration.SettingsSection
      description: "A <xref href=&quot;System.Net.Configuration.SettingsSection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.Settings*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.NetSectionGroup.WebRequestModules
  id: WebRequestModules
  parent: System.Net.Configuration.NetSectionGroup
  langs:
  - csharp
  name: WebRequestModules
  nameWithType: NetSectionGroup.WebRequestModules
  fullName: System.Net.Configuration.NetSectionGroup.WebRequestModules
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "取得組態區段包含的模組註冊為用於<xref:System.Net.WebRequest>類別。</xref:System.Net.WebRequest>"
  remarks: "這個屬性所傳回的區段對應至[ \\&lt; webRequestModules\\&gt;項目 （網路設定）](../Topic/%3CwebRequestModules%3E%20Element%20\\(Network%20Settings\\).md)組態項目。"
  syntax:
    content: public System.Net.Configuration.WebRequestModulesSection WebRequestModules { get; }
    return:
      type: System.Net.Configuration.WebRequestModulesSection
      description: "A <xref href=&quot;System.Net.Configuration.WebRequestModulesSection&quot;></xref> object."
  overload: System.Net.Configuration.NetSectionGroup.WebRequestModules*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Net.Configuration.NetSectionGroup.#ctor
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: NetSectionGroup()
  nameWithType: NetSectionGroup.NetSectionGroup()
  fullName: System.Net.Configuration.NetSectionGroup.NetSectionGroup()
- uid: System.Net.Configuration.NetSectionGroup.AuthenticationModules
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: AuthenticationModules
  nameWithType: NetSectionGroup.AuthenticationModules
  fullName: System.Net.Configuration.NetSectionGroup.AuthenticationModules
- uid: System.Net.Configuration.AuthenticationModulesSection
  parent: System.Net.Configuration
  isExternal: false
  name: AuthenticationModulesSection
  nameWithType: AuthenticationModulesSection
  fullName: System.Net.Configuration.AuthenticationModulesSection
- uid: System.Net.Configuration.NetSectionGroup.ConnectionManagement
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: ConnectionManagement
  nameWithType: NetSectionGroup.ConnectionManagement
  fullName: System.Net.Configuration.NetSectionGroup.ConnectionManagement
- uid: System.Net.Configuration.ConnectionManagementSection
  parent: System.Net.Configuration
  isExternal: false
  name: ConnectionManagementSection
  nameWithType: ConnectionManagementSection
  fullName: System.Net.Configuration.ConnectionManagementSection
- uid: System.Net.Configuration.NetSectionGroup.DefaultProxy
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: DefaultProxy
  nameWithType: NetSectionGroup.DefaultProxy
  fullName: System.Net.Configuration.NetSectionGroup.DefaultProxy
- uid: System.Net.Configuration.DefaultProxySection
  parent: System.Net.Configuration
  isExternal: false
  name: DefaultProxySection
  nameWithType: DefaultProxySection
  fullName: System.Net.Configuration.DefaultProxySection
- uid: System.Net.Configuration.NetSectionGroup.GetSectionGroup(System.Configuration.Configuration)
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: GetSectionGroup(Configuration)
  nameWithType: NetSectionGroup.GetSectionGroup(Configuration)
  fullName: System.Net.Configuration.NetSectionGroup.GetSectionGroup(Configuration)
- uid: System.Net.Configuration.NetSectionGroup
  parent: System.Net.Configuration
  isExternal: false
  name: NetSectionGroup
  nameWithType: NetSectionGroup
  fullName: System.Net.Configuration.NetSectionGroup
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Net.Configuration.NetSectionGroup.MailSettings
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: MailSettings
  nameWithType: NetSectionGroup.MailSettings
  fullName: System.Net.Configuration.NetSectionGroup.MailSettings
- uid: System.Net.Configuration.MailSettingsSectionGroup
  parent: System.Net.Configuration
  isExternal: false
  name: MailSettingsSectionGroup
  nameWithType: MailSettingsSectionGroup
  fullName: System.Net.Configuration.MailSettingsSectionGroup
- uid: System.Net.Configuration.NetSectionGroup.RequestCaching
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: RequestCaching
  nameWithType: NetSectionGroup.RequestCaching
  fullName: System.Net.Configuration.NetSectionGroup.RequestCaching
- uid: System.Net.Configuration.RequestCachingSection
  parent: System.Net.Configuration
  isExternal: false
  name: RequestCachingSection
  nameWithType: RequestCachingSection
  fullName: System.Net.Configuration.RequestCachingSection
- uid: System.Net.Configuration.NetSectionGroup.Settings
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: Settings
  nameWithType: NetSectionGroup.Settings
  fullName: System.Net.Configuration.NetSectionGroup.Settings
- uid: System.Net.Configuration.SettingsSection
  parent: System.Net.Configuration
  isExternal: false
  name: SettingsSection
  nameWithType: SettingsSection
  fullName: System.Net.Configuration.SettingsSection
- uid: System.Net.Configuration.NetSectionGroup.WebRequestModules
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: WebRequestModules
  nameWithType: NetSectionGroup.WebRequestModules
  fullName: System.Net.Configuration.NetSectionGroup.WebRequestModules
- uid: System.Net.Configuration.WebRequestModulesSection
  parent: System.Net.Configuration
  isExternal: false
  name: WebRequestModulesSection
  nameWithType: WebRequestModulesSection
  fullName: System.Net.Configuration.WebRequestModulesSection
- uid: System.Net.Configuration.NetSectionGroup.#ctor*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: NetSectionGroup
  nameWithType: NetSectionGroup.NetSectionGroup
- uid: System.Net.Configuration.NetSectionGroup.AuthenticationModules*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: AuthenticationModules
  nameWithType: NetSectionGroup.AuthenticationModules
- uid: System.Net.Configuration.NetSectionGroup.ConnectionManagement*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: ConnectionManagement
  nameWithType: NetSectionGroup.ConnectionManagement
- uid: System.Net.Configuration.NetSectionGroup.DefaultProxy*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: DefaultProxy
  nameWithType: NetSectionGroup.DefaultProxy
- uid: System.Net.Configuration.NetSectionGroup.GetSectionGroup*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: GetSectionGroup
  nameWithType: NetSectionGroup.GetSectionGroup
- uid: System.Net.Configuration.NetSectionGroup.MailSettings*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: MailSettings
  nameWithType: NetSectionGroup.MailSettings
- uid: System.Net.Configuration.NetSectionGroup.RequestCaching*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: RequestCaching
  nameWithType: NetSectionGroup.RequestCaching
- uid: System.Net.Configuration.NetSectionGroup.Settings*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: Settings
  nameWithType: NetSectionGroup.Settings
- uid: System.Net.Configuration.NetSectionGroup.WebRequestModules*
  parent: System.Net.Configuration.NetSectionGroup
  isExternal: false
  name: WebRequestModules
  nameWithType: NetSectionGroup.WebRequestModules
