### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TrustSection
  id: TrustSection
  children:
  - System.Web.Configuration.TrustSection.#ctor
  - System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType
  - System.Web.Configuration.TrustSection.LegacyCasModel
  - System.Web.Configuration.TrustSection.Level
  - System.Web.Configuration.TrustSection.OriginUrl
  - System.Web.Configuration.TrustSection.PermissionSetName
  - System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust
  - System.Web.Configuration.TrustSection.Properties
  langs:
  - csharp
  name: TrustSection
  nameWithType: TrustSection
  fullName: System.Web.Configuration.TrustSection
  type: Class
  summary: "設定會套用至應用程式的程式碼存取安全性層級。 這個類別無法被繼承。"
  remarks: "TrustSection 類別可讓您以程式設計方式存取和修改組態檔`<trust>`> 一節。 `<trust>`區段會設定用來執行特定應用程式的程式碼存取安全性權限集。 可以在機器、 網站和應用程式層級中宣告這個區段。"
  example:
  - "This section provides two code examples. The first demonstrates how to declaratively specify values for several properties of the TrustSection class. The second demonstrates how to use the TrustSection type.  \n  \n The following configuration file example shows how to declaratively specify values for several properties of the TrustSection class.  \n  \n```  \n<system.web>  \n  <trust level=\"Full\" originUrl=\"\"/>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the TrustSection type.  \n  \n [!code-cs[System.Web.Configuration.TrustSection#1](~/add/codesnippet/csharp/t-system.web.configurati_21_1.cs)]\n [!code-vb[System.Web.Configuration.TrustSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_21_1.vb)]"
  syntax:
    content: 'public sealed class TrustSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: TrustSection()
  nameWithType: TrustSection.TrustSection()
  fullName: System.Web.Configuration.TrustSection.TrustSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.TrustSection&quot;></xref>類別使用預設設定。"
  remarks: "TrustSection 建構函式不是直接從您的程式碼使用。 它會呼叫 ASP.NET 組態系統。 取得執行個體<xref:System.Web.Configuration.TrustSection>類別使用<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.TrustSection>       下表顯示用於 TrustSection 建構函式的預設設定。      |設定 |預設值 |  |-------------|-------------------|  |<xref:System.Web.Configuration.TrustSection.Level%2A>|`Full`|  |<xref:System.Web.Configuration.TrustSection.OriginUrl%2A>|`&quot;&quot;`|</xref:System.Web.Configuration.TrustSection.OriginUrl%2A></xref:System.Web.Configuration.TrustSection.Level%2A>"
  syntax:
    content: public TrustSection ();
    parameters: []
  overload: System.Web.Configuration.TrustSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType
  id: HostSecurityPolicyResolverType
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: HostSecurityPolicyResolverType
  nameWithType: TrustSection.HostSecurityPolicyResolverType
  fullName: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定自訂的安全性原則解析的型別。"
  remarks: "HostSecurityPolicyResolverType 為空字串，如果應用程式會使用 ASP.NET 預設原則，來判斷組件的權限。 預設原則評估的權限授與完全信任的全域組件快取 (GAC) 組件和其他組件的部分信任。       此屬性無法設為`null`值。"
  syntax:
    content: public string HostSecurityPolicyResolverType { get; set; }
    return:
      type: System.String
      description: "自訂的安全性原則解析的型別。"
  overload: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.LegacyCasModel
  id: LegacyCasModel
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: LegacyCasModel
  nameWithType: TrustSection.LegacyCasModel
  fullName: System.Web.Configuration.TrustSection.LegacyCasModel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指出是否已啟用的舊版程式碼存取安全性。"
  remarks: "如果啟用舊版程式碼存取安全性時，適用下列的安全性規則:-程式碼存取安全性 (CAS) 原則建立從電腦原則和指定的 ASP.NET 部分信任原則檔案的組合。      -部分信任應用程式定義域會還原成要在應用程式網域層級的完全信任。      -CONFIG 目錄中的舊版的部分信任檔案[!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)]安裝目錄可用而不是新的部分信任設定檔案位於相同的目錄中。 舊版檔案包含中找不到成員資格條件[!INCLUDE[net_v11_long](~/add/includes/net-v11-long-md.md)]或[!INCLUDE[net_v20SP1_short](~/add/includes/net-v20sp1-short-md.md)]版本[!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)]。      的要評估的權限其他成員資格條件會套用，ASP.NET 部分信任的檔案中所定義。 隨附的組態目錄[!INCLUDE[net_v40_short](~/add/includes/net-v40-short-md.md)]版本包含舊版的部分信任原則檔案。 這些檔案的名稱包含字串 「 傳統 」，並且包含[!INCLUDE[net_v20SP1_short](~/add/includes/net-v20sp1-short-md.md)]區段。 下列各節包含評估 CAS 原則，針對組件所需的非空白成員資格條件。      -如果其中一個預設部分信任的組態檔，ASP.NET 應用程式正在執行部分信任和信任層級對應的安全性原則檔中，ASP.NET 會自動選擇對應舊版的設定檔。 例如，如果安全性原則通常會從 Web_mediumtrust.config 載入，然後在舊版模式下 ASP.NET 會改為安全性原則從載入 Legacy.web_mediumtrust.config。"
  syntax:
    content: public bool LegacyCasModel { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果已啟用舊版的程式碼存取安全性。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 預設值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.TrustSection.LegacyCasModel*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.Level
  id: Level
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: Level
  nameWithType: TrustSection.Level
  fullName: System.Web.Configuration.TrustSection.Level
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定應用程式執行所在的安全性層級的名稱。"
  remarks: "層級的屬性會指定在其下的應用程式將會執行的安全性層級。 預設值是`&quot;Full&quot;`。       有五個可用的信任層級:-完整-高-媒體-低-最小具名層級對應中所定義的安全性層級`<trustLevel>`元素`<securityPolicy>`。"
  example:
  - "The following code example demonstrates how to use the Level property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustSection> class.  \n  \n [!code-cs[System.Web.Configuration.TrustSection#2](~/add/codesnippet/csharp/p-system.web.configurati_147_1.cs)]\n [!code-vb[System.Web.Configuration.TrustSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_147_1.vb)]"
  syntax:
    content: public string Level { get; set; }
    return:
      type: System.String
      description: "信任層級的名稱。 預設值是<xref uid=&quot;langword_csharp_&quot;Full&quot;&quot; name=&quot;&quot;Full&quot;&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.TrustSection.Level*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.OriginUrl
  id: OriginUrl
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: OriginUrl
  nameWithType: TrustSection.OriginUrl
  fullName: System.Web.Configuration.TrustSection.OriginUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定的來源應用程式的 URL。"
  remarks: "OriginUrl 屬性指定的來源應用程式的 URL。 如果有的話，這可用於某些權限，例如，關聯的<xref:System.Net.WebRequest>類別。</xref:System.Net.WebRequest> 這可讓您用來建立權限，透過將單一 URL 指定<xref:System.Net.WebPermission>執行個體。</xref:System.Net.WebPermission> 然後此權限授與部分信任的 ASP.NET 程式碼進行 HTTP 呼叫 （例如，Web 服務呼叫） 至該 URL 的權限。 值必須是語式正確的 HTTP URL。"
  example:
  - "The following code example demonstrates how to use the OriginUrl property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.TrustSection> class.  \n  \n [!code-cs[System.Web.Configuration.TrustSection#3](~/add/codesnippet/csharp/p-system.web.configurati_332_1.cs)]\n [!code-vb[System.Web.Configuration.TrustSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_332_1.vb)]"
  syntax:
    content: public string OriginUrl { get; set; }
    return:
      type: System.String
      description: "格式正確的 HTTP URL 或空字串 (&quot;&quot;)。 預設為空字串。"
  overload: System.Web.Configuration.TrustSection.OriginUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.PermissionSetName
  id: PermissionSetName
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: PermissionSetName
  nameWithType: TrustSection.PermissionSetName
  fullName: System.Web.Configuration.TrustSection.PermissionSetName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定權限集的名稱。"
  remarks: "PermissionSetName 屬性可讓您在部分信任的組態檔中定義的應用程式定義域初始化期間使用的具名的使用權限。       根據預設，PermissionSetName 屬性是 「 ASP.Net 「 這是用來初始化應用程式定義域的權限集合的名稱。       此屬性無法設為空字串或`null`值。"
  syntax:
    content: public string PermissionSetName { get; set; }
    return:
      type: System.String
      description: "權限集的名稱。"
  overload: System.Web.Configuration.TrustSection.PermissionSetName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust
  id: ProcessRequestInApplicationTrust
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: ProcessRequestInApplicationTrust
  nameWithType: TrustSection.ProcessRequestInApplicationTrust
  fullName: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定值，指出頁面是否要求會自動限制為套用到 ASP.NET 應用程式的信任原則檔案中所設定的權限。"
  syntax:
    content: public bool ProcessRequestInApplicationTrust { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果要求會自動限制為信任原則檔案中設定的權限否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TrustSection.Properties
  id: Properties
  parent: System.Web.Configuration.TrustSection
  langs:
  - csharp
  name: Properties
  nameWithType: TrustSection.Properties
  fullName: System.Web.Configuration.TrustSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.TrustSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.TrustSection.#ctor
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: TrustSection()
  nameWithType: TrustSection.TrustSection()
  fullName: System.Web.Configuration.TrustSection.TrustSection()
- uid: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: HostSecurityPolicyResolverType
  nameWithType: TrustSection.HostSecurityPolicyResolverType
  fullName: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TrustSection.LegacyCasModel
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: LegacyCasModel
  nameWithType: TrustSection.LegacyCasModel
  fullName: System.Web.Configuration.TrustSection.LegacyCasModel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.TrustSection.Level
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: Level
  nameWithType: TrustSection.Level
  fullName: System.Web.Configuration.TrustSection.Level
- uid: System.Web.Configuration.TrustSection.OriginUrl
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: OriginUrl
  nameWithType: TrustSection.OriginUrl
  fullName: System.Web.Configuration.TrustSection.OriginUrl
- uid: System.Web.Configuration.TrustSection.PermissionSetName
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: PermissionSetName
  nameWithType: TrustSection.PermissionSetName
  fullName: System.Web.Configuration.TrustSection.PermissionSetName
- uid: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: ProcessRequestInApplicationTrust
  nameWithType: TrustSection.ProcessRequestInApplicationTrust
  fullName: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust
- uid: System.Web.Configuration.TrustSection.Properties
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: Properties
  nameWithType: TrustSection.Properties
  fullName: System.Web.Configuration.TrustSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TrustSection.#ctor*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: TrustSection
  nameWithType: TrustSection.TrustSection
- uid: System.Web.Configuration.TrustSection.HostSecurityPolicyResolverType*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: HostSecurityPolicyResolverType
  nameWithType: TrustSection.HostSecurityPolicyResolverType
- uid: System.Web.Configuration.TrustSection.LegacyCasModel*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: LegacyCasModel
  nameWithType: TrustSection.LegacyCasModel
- uid: System.Web.Configuration.TrustSection.Level*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: Level
  nameWithType: TrustSection.Level
- uid: System.Web.Configuration.TrustSection.OriginUrl*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: OriginUrl
  nameWithType: TrustSection.OriginUrl
- uid: System.Web.Configuration.TrustSection.PermissionSetName*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: PermissionSetName
  nameWithType: TrustSection.PermissionSetName
- uid: System.Web.Configuration.TrustSection.ProcessRequestInApplicationTrust*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: ProcessRequestInApplicationTrust
  nameWithType: TrustSection.ProcessRequestInApplicationTrust
- uid: System.Web.Configuration.TrustSection.Properties*
  parent: System.Web.Configuration.TrustSection
  isExternal: false
  name: Properties
  nameWithType: TrustSection.Properties
