### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.ImeConversionModeValues
  id: ImeConversionModeValues
  children:
  - System.Windows.Input.ImeConversionModeValues.Alphanumeric
  - System.Windows.Input.ImeConversionModeValues.CharCode
  - System.Windows.Input.ImeConversionModeValues.DoNotCare
  - System.Windows.Input.ImeConversionModeValues.Eudc
  - System.Windows.Input.ImeConversionModeValues.Fixed
  - System.Windows.Input.ImeConversionModeValues.FullShape
  - System.Windows.Input.ImeConversionModeValues.Katakana
  - System.Windows.Input.ImeConversionModeValues.Native
  - System.Windows.Input.ImeConversionModeValues.NoConversion
  - System.Windows.Input.ImeConversionModeValues.Roman
  - System.Windows.Input.ImeConversionModeValues.Symbol
  langs:
  - csharp
  name: ImeConversionModeValues
  nameWithType: ImeConversionModeValues
  fullName: System.Windows.Input.ImeConversionModeValues
  type: Enum
  summary: "描述輸入轉換的輸入方法所執行的模式。"
  syntax:
    content: >-
      [System.Flags]

      public enum ImeConversionModeValues
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Alphanumeric
  id: Alphanumeric
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Alphanumeric
  nameWithType: ImeConversionModeValues.Alphanumeric
  fullName: System.Windows.Input.ImeConversionModeValues.Alphanumeric
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的法使用英數字元的轉換模式。"
  syntax:
    content: Alphanumeric
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.CharCode
  id: CharCode
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: CharCode
  nameWithType: ImeConversionModeValues.CharCode
  fullName: System.Windows.Input.ImeConversionModeValues.CharCode
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用字元碼轉換模式。"
  syntax:
    content: CharCode
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.DoNotCare
  id: DoNotCare
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: DoNotCare
  nameWithType: ImeConversionModeValues.DoNotCare
  fullName: System.Windows.Input.ImeConversionModeValues.DoNotCare
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的法不在意哪些輸入的轉換方法用;實際的轉換方法皆不明確。"
  syntax:
    content: DoNotCare
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Eudc
  id: Eudc
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Eudc
  nameWithType: ImeConversionModeValues.Eudc
  fullName: System.Windows.Input.ImeConversionModeValues.Eudc
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的法使用 EUDC （使用者定義字元） 轉換模式。"
  syntax:
    content: Eudc
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Fixed
  id: Fixed
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Fixed
  nameWithType: ImeConversionModeValues.Fixed
  fullName: System.Windows.Input.ImeConversionModeValues.Fixed
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用固定的轉換模式。"
  syntax:
    content: Fixed
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.FullShape
  id: FullShape
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: FullShape
  nameWithType: ImeConversionModeValues.FullShape
  fullName: System.Windows.Input.ImeConversionModeValues.FullShape
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用完整圖形轉換模式。"
  syntax:
    content: FullShape
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Katakana
  id: Katakana
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Katakana
  nameWithType: ImeConversionModeValues.Katakana
  fullName: System.Windows.Input.ImeConversionModeValues.Katakana
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的法使用片假名轉換模式。"
  syntax:
    content: Katakana
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Native
  id: Native
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Native
  nameWithType: ImeConversionModeValues.Native
  fullName: System.Windows.Input.ImeConversionModeValues.Native
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用原生字元集 （平假名、 韓文、 中文） 轉換模式。"
  syntax:
    content: Native
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.NoConversion
  id: NoConversion
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: NoConversion
  nameWithType: ImeConversionModeValues.NoConversion
  fullName: System.Windows.Input.ImeConversionModeValues.NoConversion
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法不會執行任何輸入的轉換。"
  syntax:
    content: NoConversion
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Roman
  id: Roman
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Roman
  nameWithType: ImeConversionModeValues.Roman
  fullName: System.Windows.Input.ImeConversionModeValues.Roman
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用羅馬字元轉換模式。"
  syntax:
    content: Roman
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.ImeConversionModeValues.Symbol
  id: Symbol
  parent: System.Windows.Input.ImeConversionModeValues
  langs:
  - csharp
  name: Symbol
  nameWithType: ImeConversionModeValues.Symbol
  fullName: System.Windows.Input.ImeConversionModeValues.Symbol
  type: Field
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "輸入的方法會使用符號的轉換模式。"
  syntax:
    content: Symbol
    return:
      type: System.Windows.Input.ImeConversionModeValues
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.Input.ImeConversionModeValues.Alphanumeric
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Alphanumeric
  nameWithType: ImeConversionModeValues.Alphanumeric
  fullName: System.Windows.Input.ImeConversionModeValues.Alphanumeric
- uid: System.Windows.Input.ImeConversionModeValues
  parent: System.Windows.Input
  isExternal: false
  name: ImeConversionModeValues
  nameWithType: ImeConversionModeValues
  fullName: System.Windows.Input.ImeConversionModeValues
- uid: System.Windows.Input.ImeConversionModeValues.CharCode
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: CharCode
  nameWithType: ImeConversionModeValues.CharCode
  fullName: System.Windows.Input.ImeConversionModeValues.CharCode
- uid: System.Windows.Input.ImeConversionModeValues.DoNotCare
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: DoNotCare
  nameWithType: ImeConversionModeValues.DoNotCare
  fullName: System.Windows.Input.ImeConversionModeValues.DoNotCare
- uid: System.Windows.Input.ImeConversionModeValues.Eudc
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Eudc
  nameWithType: ImeConversionModeValues.Eudc
  fullName: System.Windows.Input.ImeConversionModeValues.Eudc
- uid: System.Windows.Input.ImeConversionModeValues.Fixed
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Fixed
  nameWithType: ImeConversionModeValues.Fixed
  fullName: System.Windows.Input.ImeConversionModeValues.Fixed
- uid: System.Windows.Input.ImeConversionModeValues.FullShape
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: FullShape
  nameWithType: ImeConversionModeValues.FullShape
  fullName: System.Windows.Input.ImeConversionModeValues.FullShape
- uid: System.Windows.Input.ImeConversionModeValues.Katakana
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Katakana
  nameWithType: ImeConversionModeValues.Katakana
  fullName: System.Windows.Input.ImeConversionModeValues.Katakana
- uid: System.Windows.Input.ImeConversionModeValues.Native
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Native
  nameWithType: ImeConversionModeValues.Native
  fullName: System.Windows.Input.ImeConversionModeValues.Native
- uid: System.Windows.Input.ImeConversionModeValues.NoConversion
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: NoConversion
  nameWithType: ImeConversionModeValues.NoConversion
  fullName: System.Windows.Input.ImeConversionModeValues.NoConversion
- uid: System.Windows.Input.ImeConversionModeValues.Roman
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Roman
  nameWithType: ImeConversionModeValues.Roman
  fullName: System.Windows.Input.ImeConversionModeValues.Roman
- uid: System.Windows.Input.ImeConversionModeValues.Symbol
  parent: System.Windows.Input.ImeConversionModeValues
  isExternal: false
  name: Symbol
  nameWithType: ImeConversionModeValues.Symbol
  fullName: System.Windows.Input.ImeConversionModeValues.Symbol
