### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  id: MemoryCacheSection
  children:
  - System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  - System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  - System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  langs:
  - csharp
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
  type: Class
  summary: "定義組態區段，根據快取<xref href=&quot;System.Runtime.Caching.MemoryCache&quot;></xref>類別。 這個類別無法被繼承。"
  remarks: "The MemoryCacheSection class defines the settings that are available in the `memoryCache` section of a configuration file. In this section, the `namedCaches` element is used to configure a default instance of the cache and to configure any additional named instances.  \n  \n For more information, see [\\&lt;memoryCache\\&gt; Element (Cache Settings)](../Topic/%3CmemoryCache%3E%20Element%20\\(Cache%20Settings\\).md)."
  syntax:
    content: 'public sealed class MemoryCacheSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: MemoryCacheSection()
  nameWithType: MemoryCacheSection.MemoryCacheSection()
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.MemoryCacheSection()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Runtime.Caching.Configuration.MemoryCacheSection&quot;></xref>類別。"
  syntax:
    content: public MemoryCacheSection ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  id: NamedCaches
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "取得集合的組態設定具名<xref href=&quot;System.Runtime.Caching.MemoryCache&quot;></xref>執行個體。"
  remarks: "NamedCaches 屬性參考的組態設定集合從一或多個`namedCaches`的組態檔項目。 如需有關這個屬性與相關的組態選項的詳細資訊，請參閱[ \\&lt; namedCaches\\&gt;項目 （快取設定）](../Topic/%3CnamedCaches%3E%20Element%20\\(Cache%20Settings\\).md)。"
  syntax:
    content: public System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection NamedCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
      description: "設定每個集合名為快取。"
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  id: Properties
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  langs:
  - csharp
  name: Properties
  nameWithType: MemoryCacheSection.Properties
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: MemoryCacheSection()
  nameWithType: MemoryCacheSection.MemoryCacheSection()
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.MemoryCacheSection()
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSettingsCollection
  nameWithType: MemoryCacheSettingsCollection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSettingsCollection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: Properties
  nameWithType: MemoryCacheSection.Properties
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.#ctor*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.NamedCaches*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: NamedCaches
  nameWithType: MemoryCacheSection.NamedCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection.Properties*
  parent: System.Runtime.Caching.Configuration.MemoryCacheSection
  isExternal: false
  name: Properties
  nameWithType: MemoryCacheSection.Properties
