### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  id: BrowserCapabilitiesFactoryBase
  children:
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  - System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  type: Class
  summary: "BrowserCapabilitiesFactoryBase 類別是基底類別，從其中<xref href=&quot;System.Web.Configuration.BrowserCapabilitiesFactory&quot;></xref>衍生。 它供內部執行階段組態系統建立的要求特定執行個體<xref href=&quot;System.Web.Configuration.HttpCapabilitiesBase&quot;></xref>類別，可公開存取透過 ASP.NET 內建<xref uid=&quot;langword_csharp_Request.Browser&quot; name=&quot;Request.Browser&quot; href=&quot;&quot;></xref>屬性。"
  remarks: "您可以定義瀏覽器功能.browser 檔案中。 您可以使用.browser 檔案中的預設階層，或建立自訂的階層，以定義的瀏覽器功能。"
  syntax:
    content: public class BrowserCapabilitiesFactoryBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統在內部使用，若要建立這個類別的新執行個體。"
  syntax:
    content: public BrowserCapabilitiesFactoryBase ();
    parameters: []
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  id: BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統內部使用，以代表不同的瀏覽器功能的相關資訊的集合。"
  syntax:
    content: protected System.Collections.IDictionary BrowserElements { get; }
    return:
      type: System.Collections.IDictionary
      description: "瀏覽器功能的字典。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在執行階段在內部用來設定<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;></xref>物件。"
  syntax:
    content: public virtual void ConfigureBrowserCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "要求標頭的集合。"
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref>物件。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  id: ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在執行階段於內部使用，若要設定自訂的瀏覽器功能的階層。"
  remarks: "您可以定義瀏覽器功能.browser 檔案中。 您可以使用.browser 檔案中的預設階層，或建立自訂的階層，以定義的瀏覽器功能。 ConfigureCustomCapabilities 方法以處理自訂的階層。 自訂的階層都必須包含`parentID`值`browser`項目。"
  syntax:
    content: public virtual void ConfigureCustomCapabilities (System.Collections.Specialized.NameValueCollection headers, System.Web.HttpBrowserCapabilities browserCaps);
    parameters:
    - id: headers
      type: System.Collections.Specialized.NameValueCollection
      description: "要求標頭的集合。"
    - id: browserCaps
      type: System.Web.HttpBrowserCapabilities
      description: "物件，指定之瀏覽器的功能。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  id: IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統在內部用來判斷瀏覽器是否由指定<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;></xref>物件沒有可用的配接器。"
  syntax:
    content: protected bool IsBrowserUnknown (System.Web.Configuration.HttpCapabilitiesBase browserCaps);
    parameters:
    - id: browserCaps
      type: System.Web.Configuration.HttpCapabilitiesBase
      description: "<xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref>物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果沒有可用的配接器; 表示瀏覽器。否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  id: MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統內部使用，來代表要求標頭值的集合。"
  syntax:
    content: protected System.Collections.IDictionary MatchedHeaders { get; }
    return:
      type: System.Collections.IDictionary
      description: "要求標頭的集合。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  id: PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統內部使用，以填入瀏覽器功能支援的瀏覽器為基礎的集合。"
  syntax:
    content: protected virtual void PopulateBrowserElements (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "表示瀏覽器功能的索引鍵/值組的集合。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  id: PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  langs:
  - csharp
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "由組態系統內部使用，以填入根據支援的瀏覽器的要求標頭的集合。"
  syntax:
    content: protected virtual void PopulateMatchedHeaders (System.Collections.IDictionary dictionary);
    parameters:
    - id: dictionary
      type: System.Collections.IDictionary
      description: "表示瀏覽器功能的索引鍵/值組的集合。"
  overload: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase()
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase()
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Collections.IDictionary
  parent: System.Collections
  isExternal: true
  name: IDictionary
  nameWithType: IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(System.Collections.Specialized.NameValueCollection,System.Web.HttpBrowserCapabilities)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities(NameValueCollection,HttpBrowserCapabilities)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(System.Web.Configuration.HttpCapabilitiesBase)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown(HttpCapabilitiesBase)
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown(HttpCapabilitiesBase)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpCapabilitiesBase
  parent: System.Web.Configuration
  isExternal: false
  name: HttpCapabilitiesBase
  nameWithType: HttpCapabilitiesBase
  fullName: System.Web.Configuration.HttpCapabilitiesBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(System.Collections.IDictionary)
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders(IDictionary)
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
  fullName: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders(IDictionary)
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.#ctor*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserCapabilitiesFactoryBase
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserCapabilitiesFactoryBase
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.BrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: BrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.BrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureBrowserCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureBrowserCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: ConfigureCustomCapabilities
  nameWithType: BrowserCapabilitiesFactoryBase.ConfigureCustomCapabilities
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.IsBrowserUnknown*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: IsBrowserUnknown
  nameWithType: BrowserCapabilitiesFactoryBase.IsBrowserUnknown
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.MatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: MatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.MatchedHeaders
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateBrowserElements*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateBrowserElements
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateBrowserElements
- uid: System.Web.Configuration.BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders*
  parent: System.Web.Configuration.BrowserCapabilitiesFactoryBase
  isExternal: false
  name: PopulateMatchedHeaders
  nameWithType: BrowserCapabilitiesFactoryBase.PopulateMatchedHeaders
