### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  id: WorkflowRuntimeServiceElement
  children:
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  - System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  type: Class
  summary: "表示要加入至工作流程執行階段引擎服務的組態項目。"
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]WorkflowRuntimeServiceElement 中指定的主機服務，應該加以初始化和啟動工作流程執行階段引擎。 它會對應至主機服務中指定`Services`> 組態檔中的項目。 由於 WorkflowRuntimeServiceElement 中指定的服務將由工作流程執行階段引擎初始化它必須有至少一個建構函式符合下列四個簽章 （工作流程執行階段引擎會嘗試比對這些簽章顯示的順序） 的其中一個︰ Service(WorkflowRuntime runtime, NameValueCollection parameters) Service(WorkflowRuntime runtime) Service(NameValueCollection parameters) Service()"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowRuntimeServiceElement : System.Configuration.ConfigurationElement
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  id: '#ctor'
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  type: Constructor
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;></xref>類別。"
  remarks: "如果您使用這個建構函式，您必須明確設定<xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type%2A>.</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type%2A>"
  syntax:
    content: public WorkflowRuntimeServiceElement ();
    parameters: []
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "當還原序列化時遇到未知的屬性時呼叫<xref href=&quot;System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement&quot;> </xref>。"
  remarks: "依名稱和值指定的名稱 / 值組加入至<xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>集合。</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A> 以外的任何屬性`type`中指定`add`> 項目`Services`> 組態檔中的元素會新增為名稱 / 值組<xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>集合。</xref:System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters%2A>"
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "無法辨識的屬性名稱。"
    - id: value
      type: System.String
      description: "無法辨識的屬性值。"
    return:
      type: System.Boolean
      description: "一律傳回 OnDeserializeUnrecognizedAttribute <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  id: Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "取得此服務的參數。"
  syntax:
    content: public System.Collections.Specialized.NameValueCollection Parameters { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> ，指定服務的參數。"
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  id: Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  langs:
  - csharp
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime.Configuration
  summary: "取得或設定服務的組件限定類型名稱。"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "服務的組件限定類型名稱。"
  overload: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "已嘗試將類型設定為 null 參考。"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement()
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement()
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
  fullName: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.#ctor*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: WorkflowRuntimeServiceElement
  nameWithType: WorkflowRuntimeServiceElement.WorkflowRuntimeServiceElement
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: WorkflowRuntimeServiceElement.OnDeserializeUnrecognizedAttribute
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Parameters*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Parameters
  nameWithType: WorkflowRuntimeServiceElement.Parameters
- uid: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement.Type*
  parent: System.Workflow.Runtime.Configuration.WorkflowRuntimeServiceElement
  isExternal: false
  name: Type
  nameWithType: WorkflowRuntimeServiceElement.Type
