### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement
  id: BasicHttpsBindingElement
  children:
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor(System.String)
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties
  - System.ServiceModel.Configuration.BasicHttpsBindingElement.Security
  langs:
  - csharp
  name: BasicHttpsBindingElement
  nameWithType: BasicHttpsBindingElement
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement
  type: Class
  summary: "指定設定基本的 https 繫結項目。"
  syntax:
    content: 'public class BasicHttpsBindingElement : System.ServiceModel.Configuration.HttpBindingBaseElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.StandardBindingElement
  - System.ServiceModel.Configuration.HttpBindingBaseElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.HttpBindingBaseElement.AllowCookies
  - System.ServiceModel.Configuration.HttpBindingBaseElement.BypassProxyOnLocal
  - System.ServiceModel.Configuration.HttpBindingBaseElement.HostNameComparisonMode
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxBufferPoolSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxBufferSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.MaxReceivedMessageSize
  - System.ServiceModel.Configuration.HttpBindingBaseElement.ProxyAddress
  - System.ServiceModel.Configuration.HttpBindingBaseElement.ReaderQuotas
  - System.ServiceModel.Configuration.HttpBindingBaseElement.TextEncoding
  - System.ServiceModel.Configuration.HttpBindingBaseElement.TransferMode
  - System.ServiceModel.Configuration.HttpBindingBaseElement.UseDefaultWebProxy
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.StandardBindingElement.ApplyConfiguration(System.ServiceModel.Channels.Binding)
  - System.ServiceModel.Configuration.StandardBindingElement.CloseTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Name
  - System.ServiceModel.Configuration.StandardBindingElement.OpenTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.ReceiveTimeout
  - System.ServiceModel.Configuration.StandardBindingElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.StandardBindingElement.SendTimeout
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: BasicHttpsBindingElement()
  nameWithType: BasicHttpsBindingElement.BasicHttpsBindingElement()
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BasicHttpsBindingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.BasicHttpsBindingElement&quot;></xref>類別。"
  syntax:
    content: public BasicHttpsBindingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: BasicHttpsBindingElement(String)
  nameWithType: BasicHttpsBindingElement.BasicHttpsBindingElement(String)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BasicHttpsBindingElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.BasicHttpsBindingElement&quot;></xref>具有指定名稱的類別。"
  syntax:
    content: public BasicHttpsBindingElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "名稱。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: BasicHttpsBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得繫結項目的型別。"
  syntax:
    content: protected override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "繫結項目的類型。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  id: InitializeFrom(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: InitializeFrom(Binding)
  nameWithType: BasicHttpsBindingElement.InitializeFrom(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化使用指定的繫結的繫結項目。"
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "繫結。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding
  id: MessageEncoding
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: MessageEncoding
  nameWithType: BasicHttpsBindingElement.MessageEncoding
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得或設定繫結項目訊息編碼。"
  syntax:
    content: public System.ServiceModel.WSMessageEncoding MessageEncoding { get; set; }
    return:
      type: System.ServiceModel.WSMessageEncoding
      description: "繫結項目訊息編碼方式。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  id: OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: OnApplyConfiguration(Binding)
  nameWithType: BasicHttpsBindingElement.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration(Binding)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "引發套用組態的事件。"
  syntax:
    content: protected override void OnApplyConfiguration (System.ServiceModel.Channels.Binding binding);
    parameters:
    - id: binding
      type: System.ServiceModel.Channels.Binding
      description: "繫結。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: Properties
  nameWithType: BasicHttpsBindingElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得繫結項目屬性的集合。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "繫結項目屬性的集合。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security
  id: Security
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  langs:
  - csharp
  name: Security
  nameWithType: BasicHttpsBindingElement.Security
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得繫結項目安全性。"
  syntax:
    content: public System.ServiceModel.Configuration.BasicHttpsSecurityElement Security { get; }
    return:
      type: System.ServiceModel.Configuration.BasicHttpsSecurityElement
      description: "繫結項目安全性。"
  overload: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.HttpBindingBaseElement
  isExternal: false
  name: System.ServiceModel.Configuration.HttpBindingBaseElement
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: BasicHttpsBindingElement()
  nameWithType: BasicHttpsBindingElement.BasicHttpsBindingElement()
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BasicHttpsBindingElement()
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: BasicHttpsBindingElement(String)
  nameWithType: BasicHttpsBindingElement.BasicHttpsBindingElement(String)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BasicHttpsBindingElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: BasicHttpsBindingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: InitializeFrom(Binding)
  nameWithType: BasicHttpsBindingElement.InitializeFrom(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom(Binding)
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: MessageEncoding
  nameWithType: BasicHttpsBindingElement.MessageEncoding
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding
- uid: System.ServiceModel.WSMessageEncoding
  parent: System.ServiceModel
  isExternal: false
  name: WSMessageEncoding
  nameWithType: WSMessageEncoding
  fullName: System.ServiceModel.WSMessageEncoding
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration(System.ServiceModel.Channels.Binding)
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: OnApplyConfiguration(Binding)
  nameWithType: BasicHttpsBindingElement.OnApplyConfiguration(Binding)
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration(Binding)
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpsBindingElement.Properties
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: Security
  nameWithType: BasicHttpsBindingElement.Security
  fullName: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security
- uid: System.ServiceModel.Configuration.BasicHttpsSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: BasicHttpsSecurityElement
  nameWithType: BasicHttpsSecurityElement
  fullName: System.ServiceModel.Configuration.BasicHttpsSecurityElement
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.#ctor*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: BasicHttpsBindingElement
  nameWithType: BasicHttpsBindingElement.BasicHttpsBindingElement
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.BindingElementType*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: BindingElementType
  nameWithType: BasicHttpsBindingElement.BindingElementType
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: InitializeFrom
  nameWithType: BasicHttpsBindingElement.InitializeFrom
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.MessageEncoding*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: MessageEncoding
  nameWithType: BasicHttpsBindingElement.MessageEncoding
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.OnApplyConfiguration*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: OnApplyConfiguration
  nameWithType: BasicHttpsBindingElement.OnApplyConfiguration
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Properties*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: Properties
  nameWithType: BasicHttpsBindingElement.Properties
- uid: System.ServiceModel.Configuration.BasicHttpsBindingElement.Security*
  parent: System.ServiceModel.Configuration.BasicHttpsBindingElement
  isExternal: false
  name: Security
  nameWithType: BasicHttpsBindingElement.Security
