### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TransformerInfo
  id: TransformerInfo
  children:
  - System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  - System.Web.Configuration.TransformerInfo.Equals(System.Object)
  - System.Web.Configuration.TransformerInfo.GetHashCode
  - System.Web.Configuration.TransformerInfo.Name
  - System.Web.Configuration.TransformerInfo.Properties
  - System.Web.Configuration.TransformerInfo.Type
  langs:
  - csharp
  name: TransformerInfo
  nameWithType: TransformerInfo
  fullName: System.Web.Configuration.TransformerInfo
  type: Class
  summary: "指定擴充的自訂類別<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;> </xref> Web 組件連接所使用的類別。"
  remarks: "TransformerInfo 物件指定自訂擴充類別的<xref:System.Web.UI.WebControls.WebParts.WebPartTransformer>類別。</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer> 這些自訂的轉換程式類別做為 Web 組件，具有不相容的連接點的 Web 組件之間轉譯資料之間的橋樑。"
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for several properties of the TransformerInfo class.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <transformers>  \n      <add name=\"RowToFieldTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFieldTransformer\" />  \n      <add name=\"RowToFilterTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToFilterTransformer\" />  \n      <add name=\"RowToParametersTransformer\"  \n        type=\"System.Web.UI.WebControls.WebParts.RowToParametersTransformer\" />  \n    </transformers>  \n  </webParts>   \n</system.web>  \n```  \n  \n The following code example shows how to use the TransformerInfo class. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/csharp/t-system.web.configurati_58_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#2](~/add/codesnippet/visualbasic/t-system.web.configurati_58_1.vb)]"
  syntax:
    content: 'public sealed class TransformerInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: TransformerInfo(String,String)
  nameWithType: TransformerInfo.TransformerInfo(String,String)
  fullName: System.Web.Configuration.TransformerInfo.TransformerInfo(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Web.Configuration.TransformerInfo&quot;></xref>類別具有指定之名稱和類型參考。"
  remarks: "組態系統不會驗證指定的型別，以確保使用有效的類型名稱。"
  example:
  - "The following code example shows how to use the TransformerInfo constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#5](~/add/codesnippet/csharp/8552e432-1ac7-4c16-b8d4-_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#5](~/add/codesnippet/visualbasic/8552e432-1ac7-4c16-b8d4-_1.vb)]"
  syntax:
    content: public TransformerInfo (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "此轉換程式型別名稱。"
    - id: type
      type: System.String
      description: "擴充轉換程式型別的參考<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;></xref>類別。"
  overload: System.Web.Configuration.TransformerInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: TransformerInfo.Equals(Object)
  fullName: System.Web.Configuration.TransformerInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "比較目前<xref href=&quot;System.Web.Configuration.TransformerInfo&quot;></xref>物件與其他<xref href=&quot;System.Web.Configuration.TransformerInfo&quot;></xref>物件。"
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: "要與目前物件比較的物件。"
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果傳遞的物件是否等於目前的物件;否則， <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.TransformerInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: TransformerInfo.GetHashCode()
  fullName: System.Web.Configuration.TransformerInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "會產生集合的雜湊碼。"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "目前物件的唯一整數雜湊碼。"
  overload: System.Web.Configuration.TransformerInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Name
  id: Name
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Name
  nameWithType: TransformerInfo.Name
  fullName: System.Web.Configuration.TransformerInfo.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定類型的易記名稱的擴充<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;></xref>類別。"
  remarks: ''
  example:
  - "The following code example shows how to use the Name property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "延伸類型的易記名稱<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;></xref>類別。"
  overload: System.Web.Configuration.TransformerInfo.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Properties
  id: Properties
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Properties
  nameWithType: TransformerInfo.Properties
  fullName: System.Web.Configuration.TransformerInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "即將加入。"
  overload: System.Web.Configuration.TransformerInfo.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TransformerInfo.Type
  id: Type
  parent: System.Web.Configuration.TransformerInfo
  langs:
  - csharp
  name: Type
  nameWithType: TransformerInfo.Type
  fullName: System.Web.Configuration.TransformerInfo.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "取得或設定擴充之類別的型別參考<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;></xref>類別。"
  remarks: "組態系統不會驗證指定的型別，以確保使用有效的類型名稱。 不過，無效的型別在載入網頁時，將導致例外狀況。"
  example:
  - "The following code example shows how to use the Type property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> type.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "擴充之類別的型別參考<xref href=&quot;System.Web.UI.WebControls.WebParts.WebPartTransformer&quot;></xref>類別。"
  overload: System.Web.Configuration.TransformerInfo.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TransformerInfo.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: TransformerInfo(String,String)
  nameWithType: TransformerInfo.TransformerInfo(String,String)
  fullName: System.Web.Configuration.TransformerInfo.TransformerInfo(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TransformerInfo.Equals(System.Object)
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: TransformerInfo.Equals(Object)
  fullName: System.Web.Configuration.TransformerInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.TransformerInfo.GetHashCode
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: TransformerInfo.GetHashCode()
  fullName: System.Web.Configuration.TransformerInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.TransformerInfo.Name
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Name
  nameWithType: TransformerInfo.Name
  fullName: System.Web.Configuration.TransformerInfo.Name
- uid: System.Web.Configuration.TransformerInfo.Properties
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Properties
  nameWithType: TransformerInfo.Properties
  fullName: System.Web.Configuration.TransformerInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TransformerInfo.Type
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Type
  nameWithType: TransformerInfo.Type
  fullName: System.Web.Configuration.TransformerInfo.Type
- uid: System.Web.Configuration.TransformerInfo.#ctor*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: TransformerInfo
  nameWithType: TransformerInfo.TransformerInfo
- uid: System.Web.Configuration.TransformerInfo.Equals*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Equals
  nameWithType: TransformerInfo.Equals
- uid: System.Web.Configuration.TransformerInfo.GetHashCode*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: GetHashCode
  nameWithType: TransformerInfo.GetHashCode
- uid: System.Web.Configuration.TransformerInfo.Name*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Name
  nameWithType: TransformerInfo.Name
- uid: System.Web.Configuration.TransformerInfo.Properties*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Properties
  nameWithType: TransformerInfo.Properties
- uid: System.Web.Configuration.TransformerInfo.Type*
  parent: System.Web.Configuration.TransformerInfo
  isExternal: false
  name: Type
  nameWithType: TransformerInfo.Type
