### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "代表將處理的方法<xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;></xref>事件。"
  remarks: "<xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>前一群應用程式設定會保存，通常<xref:System.Configuration.ApplicationSettingsBase.Save%2A>衍生自<xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase>包裝函式類別的方法</xref:System.Configuration.ApplicationSettingsBase.Save%2A>執行期間發生的事件</xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
