### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceMode
  id: XhtmlConformanceMode
  children:
  - System.Web.Configuration.XhtmlConformanceMode.Legacy
  - System.Web.Configuration.XhtmlConformanceMode.Strict
  - System.Web.Configuration.XhtmlConformanceMode.Transitional
  langs:
  - csharp
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
  type: Enum
  summary: "指定要在 Web 應用程式中使用的驗證模式。"
  remarks: "適用於 XhtmlConformanceMode 列舉`mode`屬性`xhtmlConformance`標記。 它會指定 XHTML 轉譯型態，ASP.NET 應用程式。 模式可採用下列其中一個列在下一個值。 預設值是`Transitional`(XHTML 1.0 Transitional)。"
  syntax:
    content: public enum XhtmlConformanceMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  id: Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 Transitional"
  syntax:
    content: Legacy
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  id: Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 Strict 一致性"
  syntax:
    content: Strict
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  id: Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "還原的數字呈現為符合 v1.1 轉譯行為變更。"
  syntax:
    content: Transitional
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "即將加入。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
