### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  summary: "表示應用程式沒有信任，才能在本機電腦上執行的適當層級。"
  remarks: "根據預設，[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]應用程式會提供用戶端電腦上避免從事惡意活動，例如從硬碟中刪除資料或存取網路的信任層級。 A[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]應用程式可用權限提升或受信任的應用程式部署來要求更高的信任層級:-權限提高詢問使用者是否要授與應用程式較高的安全性等級。      -信任的應用程式部署符合的數位簽章[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]應用程式針對本機電腦上的受信任發行者清單。       TrustNotGrantedException 會擲回:-應用程式使用提高權限和使用者，拒絕的要求更高的信任。應用程式使用信任的應用程式部署或用來簽署應用程式的數位憑證未列示為本機電腦上受信任的發行者。如果您已將更新部署至應用程式，而更新使用較舊版本中，使用權限和[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]a TrustNotGrantedException 會擲回，無法安裝新版本。"
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新執行個體<xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;></xref>以系統提供的訊息描述錯誤的類別。"
  remarks: "這個建構函式初始化<xref:System.Exception.Message%2A>屬性的新執行個體的系統提供的訊息描述錯誤，例如&quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot;這個訊息會考量目前系統文化特性。</xref:System.Exception.Message%2A>       下表顯示<xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>的執行個體的初始屬性值      |屬性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|當地語系化的錯誤訊息字串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新執行個體<xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;></xref>具有指定的訊息描述錯誤的類別。"
  remarks: "下表顯示<xref:System.Deployment.Application.TrustNotGrantedException>.</xref:System.Deployment.Application.TrustNotGrantedException>的執行個體的初始屬性值      |屬性 |值 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|錯誤訊息字串中指定`message`。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述例外狀況訊息。 這個建構函式的呼叫端，才能確保這個字串已經被當地語系化為目前的系統文化特性。"
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新執行個體<xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;></xref>使用序列化資料的類別。"
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "保存序列化的物件資料的物件。"
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "關於來源或目的端內容資訊。"
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新執行個體<xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;></xref>類別指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考。"
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "描述例外狀況訊息。 這個建構函式的呼叫端，才能確保這個字串已經被當地語系化為目前的系統文化特性。"
    - id: innerException
      type: System.Exception
      description: "造成目前例外狀況的例外狀況。 如果`innerException`參數不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引發目前的例外狀況<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>處理內部例外狀況區塊。"
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor*
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException.TrustNotGrantedException
