### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: "指定用來提供存放裝置目前的應用程式設定類別或屬性的設定提供者。 這個類別無法被繼承。"
  remarks: "每個應用程式設定類別定義一組應用程式設定屬性表示應用程式的執行之間保存的資訊。 不過，並設定提供者 — 的類別衍生自<xref:System.Configuration.SettingsProvider>— 實際上提供儲存機制。</xref:System.Configuration.SettingsProvider>       SettingsProviderAttribute 指定用來提供應用程式設定屬性存放區的設定提供者。 這個屬性可以套用至整個應用程式設定類別或個別的應用程式設定屬性。 SettingsProviderAttribute，在屬性層級設定會覆寫類別層級屬性。 如果沒有明確指定設定提供者，則會使用預設提供者。 用戶端應用程式，預設的提供者為<xref:System.Configuration.LocalFileSettingsProvider>。</xref:System.Configuration.LocalFileSettingsProvider>       設定提供者無法在執行階段決定。 儲存方法的任何執行階段判斷必須編碼成設定提供者類別本身。      > [!CAUTION] > 使用任意協力廠商的自訂設定提供者是原本就不安全，因為這些提供者擁有完整讀取/寫入存取您的應用程式組態資訊。 一般用途之前應該徹底驗證設定提供者。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的執行個體<xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;></xref>類別。"
  remarks: "型別名稱是衍生自的類別名稱<xref:System.Configuration.SettingsProvider>，也就是指定為設定提供者。</xref:System.Configuration.SettingsProvider>      > [!CAUTION] > 使用任意協力廠商的自訂設定提供者是原本就不安全，因為這些提供者擁有完整讀取/寫入存取您的應用程式組態資訊。 一般用途之前應該徹底驗證設定提供者。"
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: "A<xref:System.String>包含設定提供者的名稱。</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;></xref>類別。"
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: "A<xref:System.Type>包含設定提供者類型。</xref:System.Type>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "取得設定提供者的型別名稱。"
  remarks: "ProviderTypeName 屬性是設定<xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>為類別。</xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>"
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: "A<xref:System.String>包含設定提供者的名稱。</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
