### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlWriterSettings
  id: XamlWriterSettings
  children:
  - System.Xaml.XamlWriterSettings.#ctor
  - System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  langs:
  - csharp
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
  type: Class
  summary: "提供初始化設定<xref href=&quot;System.Xaml.XamlWriter&quot;></xref>實作。"
  remarks: "XamlWriterSettings 是所使用的設定需類別<xref:System.Xaml.XamlWriter>; 不過，XamlWriterSettings 不包含任何特定的設定。</xref:System.Xaml.XamlWriter> <xref:System.Xaml.XamlWriter>建構函式不會使用此設定類別，做為引數，也不會任何其他<xref:System.Xaml.XamlWriter>成員使用它。</xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlWriter> 相反地，<xref:System.Xaml.XamlXmlWriter>和<xref:System.Xaml.XamlObjectWriter>類別包括他們自己的設定類別做為建構引數; 這兩個類別加入實際的設定，並根據 XamlWriterSettings。</xref:System.Xaml.XamlObjectWriter> </xref:System.Xaml.XamlXmlWriter>"
  syntax:
    content: public class XamlWriterSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新執行個體<xref href=&quot;System.Xaml.XamlWriterSettings&quot;></xref>類別。"
  syntax:
    content: public XamlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  id: '#ctor(System.Xaml.XamlWriterSettings)'
  parent: System.Xaml.XamlWriterSettings
  langs:
  - csharp
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "初始化的新執行個體<xref href=&quot;System.Xaml.XamlWriterSettings&quot;></xref>類別使用另一個現有的設定執行個體。"
  remarks: "這個建構函式可讓您支援的設定，其中的其他設定可以來自編寫器程序中的其他參與者或設定類別，該覆寫<xref:System.Xaml.XamlWriterSettings>.</xref:System.Xaml.XamlWriterSettings>特製化寫入合併"
  syntax:
    content: public XamlWriterSettings (System.Xaml.XamlWriterSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlWriterSettings
      description: "現有<xref href=&quot;System.Xaml.XamlWriterSettings&quot;></xref>物件。"
  overload: System.Xaml.XamlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlWriterSettings.#ctor
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings()
  nameWithType: XamlWriterSettings.XamlWriterSettings()
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings()
- uid: System.Xaml.XamlWriterSettings.#ctor(System.Xaml.XamlWriterSettings)
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings(XamlWriterSettings)
  nameWithType: XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
  fullName: System.Xaml.XamlWriterSettings.XamlWriterSettings(XamlWriterSettings)
- uid: System.Xaml.XamlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings
  fullName: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlWriterSettings.#ctor*
  parent: System.Xaml.XamlWriterSettings
  isExternal: false
  name: XamlWriterSettings
  nameWithType: XamlWriterSettings.XamlWriterSettings
