### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionsSection
  id: ExtensionsSection
  children:
  - System.ServiceModel.Configuration.ExtensionsSection.#ctor
  - System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  - System.ServiceModel.Configuration.ExtensionsSection.Properties
  langs:
  - csharp
  name: ExtensionsSection
  nameWithType: ExtensionsSection
  fullName: System.ServiceModel.Configuration.ExtensionsSection
  type: Class
  summary: "表示包含所有延伸定義組態區段。"
  syntax:
    content: 'public class ExtensionsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新執行個體<xref href=&quot;System.ServiceModel.Configuration.ExtensionsSection&quot;></xref>類別。"
  syntax:
    content: public ExtensionsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  id: BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得區段中所定義的所有行為延伸。"
  remarks: "行為延伸可讓使用者建立使用者定義的行為項目。 這些項目可以用於標準連同[!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)]行為項目。"
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BehaviorExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "行為延伸的集合。"
  overload: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  id: BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得區段中所定義的所有繫結項目延伸。"
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingElementExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "繫結項目延伸的集合。"
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  id: BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得區段中所定義的所有繫結延伸。"
  remarks: "繫結延伸可讓使用者建立使用者定義的繫結項目，使用自訂繫結的一部分。 以程式設計的方式，為繫結延伸是實作抽象類別 BindingElement 的型別。"
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "繫結延伸模組的集合。"
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  id: EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得<xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;></xref>包含指定的端點延伸的物件。"
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection EndpointExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "端點延伸的集合。"
  overload: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化一組預設的值，這個組態區段。"
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "取得<xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref>包含集合的執行個體<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>可能是屬性的物件或<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>這個組態項目的物件。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref>包含集合的執行個體<xref href=&quot;System.Configuration.ConfigurationProperty&quot;></xref>可能是屬性的物件或<xref href=&quot;System.Configuration.ConfigurationElement&quot;></xref>這個組態項目的物件。"
  overload: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection
  nameWithType: ExtensionsSection.ExtensionsSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault
  nameWithType: ExtensionsSection.InitializeDefault
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
