### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: InstallEventHandler
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: "Represents the method that will handle the <xref href=&quot;System.Configuration.Install.Installer.BeforeInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committing&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committed&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeUninstall&quot;></xref>, or <xref href=&quot;System.Configuration.Install.Installer.AfterUninstall&quot;></xref> event of an <xref href=&quot;System.Configuration.Install.Installer&quot;></xref>."
  remarks: "當您建立 InstallEventHandler 委派時，您可以識別即將處理此事件的方法。 若要將事件與事件處理常式產生關聯，將委派的執行個體加入事件。 除非您移除委派，否則每當事件發生時，會呼叫事件處理常式。 如需事件處理常式委派的詳細資訊，請參閱[事件](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
