### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  id: ManifestReader
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  langs:
  - csharp
  name: ManifestReader
  nameWithType: ManifestReader
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  type: Class
  summary: "XML 資訊清單檔案讀入物件表示。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class ManifestReader
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  id: ReadManifest(System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(Stream,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "讀取指定的資訊清單 XML 並傳回的物件表示。"
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (System.IO.Stream input, bool preserveStream);
    parameters:
    - id: input
      type: System.IO.Stream
      description: "指定的輸入資料流。"
    - id: preserveStream
      type: System.Boolean
      description: "指定是否要保留在輸入資料流<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*>產生資訊清單的物件屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*> 使用<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter&quot;></xref>以便重新構成經由輸入，其中不會出現在此物件表示。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "A <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest&quot;> </xref>物件的資訊清單的表示法。 可以轉換成<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest&quot;> </xref>， <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationManifest&quot;> </xref>，或<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.DeployManifest&quot;></xref>存取更加特定的功能。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  id: ReadManifest(System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "讀取指定的資訊清單 XML 並傳回的物件表示。"
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string path, bool preserveStream);
    parameters:
    - id: path
      type: System.String
      description: "輸入檔案的完整的路徑名稱。 例如，完整路徑可能 c:\\directory\\folder\\filename.manifest。"
    - id: preserveStream
      type: System.Boolean
      description: "指定是否要保留在輸入資料流<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*>產生資訊清單的物件屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*> 使用<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter&quot;></xref>以便重新構成經由輸入，其中不會出現在此物件表示。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "A <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest&quot;> </xref>物件的資訊清單的表示法。 可以轉換成<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest&quot;> </xref>， <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationManifest&quot;> </xref>，或<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.DeployManifest&quot;></xref>存取更加特定的功能。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  id: ReadManifest(System.String,System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Stream,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "讀取指定的資訊清單 XML 並傳回的物件表示。"
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string manifestType, System.IO.Stream input, bool preserveStream);
    parameters:
    - id: manifestType
      type: System.String
      description: "指定資訊清單的預期型別。 Valid values are <xref uid=&quot;langword_csharp_AssemblyManifest&quot; name=&quot;AssemblyManifest&quot; href=&quot;&quot;></xref>, <xref uid=&quot;langword_csharp_ApplicationManifest&quot; name=&quot;ApplicationManifest&quot; href=&quot;&quot;></xref>, or <xref uid=&quot;langword_csharp_DeployManifest&quot; name=&quot;DeployManifest&quot; href=&quot;&quot;></xref>."
    - id: input
      type: System.IO.Stream
      description: "指定的輸入資料流。"
    - id: preserveStream
      type: System.Boolean
      description: "指定是否要保留在輸入資料流<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*>產生資訊清單的物件屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*> 使用<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter&quot;></xref>以便重新構成經由輸入，其中不會出現在此物件表示。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "A <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest&quot;> </xref>物件的資訊清單的表示法。 可以轉換成<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest&quot;> </xref>， <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationManifest&quot;> </xref>，或<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.DeployManifest&quot;></xref>存取更加特定的功能。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  id: ReadManifest(System.String,System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  langs:
  - csharp
  name: ReadManifest(String,String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,String,Boolean)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "讀取指定的資訊清單 XML 並傳回的物件表示。"
  syntax:
    content: public static Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest ReadManifest (string manifestType, string path, bool preserveStream);
    parameters:
    - id: manifestType
      type: System.String
      description: "指定資訊清單的預期型別。 Valid values are <xref uid=&quot;langword_csharp_AssemblyManifest&quot; name=&quot;AssemblyManifest&quot; href=&quot;&quot;></xref>, <xref uid=&quot;langword_csharp_ApplicationManifest&quot; name=&quot;ApplicationManifest&quot; href=&quot;&quot;></xref>, or <xref uid=&quot;langword_csharp_DeployManifest&quot; name=&quot;DeployManifest&quot; href=&quot;&quot;></xref>."
    - id: path
      type: System.String
      description: "輸入檔案的路徑名稱。"
    - id: preserveStream
      type: System.Boolean
      description: "指定是否要保留在輸入資料流<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*>產生資訊清單的物件屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.InputStream*> 使用<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestWriter&quot;></xref>以便重新構成經由輸入，其中不會出現在此物件表示。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
      description: "A <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest&quot;> </xref>物件的資訊清單的表示法。 可以轉換成<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyManifest&quot;> </xref>， <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.ApplicationManifest&quot;> </xref>，或<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.DeployManifest&quot;></xref>存取更加特定的功能。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(Stream,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: Manifest
  nameWithType: Manifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest
- uid: System.IO.Stream
  parent: System.IO
  isExternal: true
  name: Stream
  nameWithType: Stream
  fullName: System.IO.Stream
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.IO.Stream,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,Stream,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,Stream,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,Stream,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(System.String,System.String,System.Boolean)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest(String,String,Boolean)
  nameWithType: ManifestReader.ReadManifest(String,String,Boolean)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest(String,String,Boolean)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader.ReadManifest*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.ManifestReader
  isExternal: false
  name: ReadManifest
  nameWithType: ManifestReader.ReadManifest
