### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  id: AssemblyReference
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  langs:
  - csharp
  name: AssemblyReference
  nameWithType: AssemblyReference
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  type: Class
  summary: "描述的資訊清單的組件參考。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class AssemblyReference : Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  inheritance:
  - System.Object
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  implements: []
  inheritedMembers:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Group
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Hash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.IsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.ResolvedPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.Size
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.SourcePath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.TargetPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlGroup
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHash
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlHashAlgorithm
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlIsOptional
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlPath
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference.XmlSize
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyReference()
  nameWithType: AssemblyReference.AssemblyReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference&quot;></xref>類別。"
  syntax:
    content: public AssemblyReference ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyReference(String)
  nameWithType: AssemblyReference.AssemblyReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference(String)
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "初始化的新執行個體<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference&quot;></xref>類別。"
  syntax:
    content: public AssemblyReference (string path);
    parameters:
    - id: path
      type: System.String
      description: "指定的來源檔案的路徑。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  id: AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: AssemblyIdentity
  nameWithType: AssemblyReference.AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "指定組件參考的身分識別。"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity AssemblyIdentity { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity&quot;> </xref>物件，代表組件參考的識別。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  id: IsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: IsPrerequisite
  nameWithType: AssemblyReference.IsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "指定組件參考或不是必要條件。"
  syntax:
    content: public bool IsPrerequisite { get; set; }
    return:
      type: System.Boolean
      description: "布林值，指出組件參考是否為必要條件 (<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>) 與否 (<xref uid=&quot;langword_csharp_False&quot; name=&quot;False&quot; href=&quot;&quot;></xref>)。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  id: ReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: ReferenceType
  nameWithType: AssemblyReference.ReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "指定組件參考的型別。"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType ReferenceType { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "<xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType&quot;> </xref>物件，代表組件參考的型別。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  id: SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: SortName
  nameWithType: AssemblyReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  syntax:
    content: protected override string SortName { get; }
    return:
      type: System.String
      description: "要加入。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  id: ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: ToString()
  nameWithType: AssemblyReference.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "傳回完整的 ClickOnce 組件參考。"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "字串，包含 ClickOnce 組件參考。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  id: XmlAssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlAssemblyIdentity
  nameWithType: AssemblyReference.XmlAssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得或設定此屬性，用來序列化<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*>至 XML 檔案的屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*>"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity XmlAssemblyIdentity { get; set; }
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
      description: "值<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*>屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  id: XmlIsNative
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlIsNative
  nameWithType: AssemblyReference.XmlIsNative
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得或設定值，指出是否為原生參考。"
  syntax:
    content: public string XmlIsNative { get; set; }
    return:
      type: System.String
      description: "值，指出是否為原生參考。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  id: XmlIsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  langs:
  - csharp
  name: XmlIsPrerequisite
  nameWithType: AssemblyReference.XmlIsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "取得或設定此屬性，用來序列化<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*>至 XML 檔案的屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*>"
  syntax:
    content: public string XmlIsPrerequisite { get; set; }
    return:
      type: System.String
      description: "值<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*>屬性。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
  isExternal: false
  name: Microsoft.Build.Tasks.Deployment.ManifestUtilities.BaseReference
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyReference()
  nameWithType: AssemblyReference.AssemblyReference()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyReference(String)
  nameWithType: AssemblyReference.AssemblyReference(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyReference(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyReference.AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: IsPrerequisite
  nameWithType: AssemblyReference.IsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ReferenceType
  nameWithType: AssemblyReference.ReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: SortName
  nameWithType: AssemblyReference.SortName
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ToString()
  nameWithType: AssemblyReference.ToString()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlAssemblyIdentity
  nameWithType: AssemblyReference.XmlAssemblyIdentity
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsNative
  nameWithType: AssemblyReference.XmlIsNative
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsPrerequisite
  nameWithType: AssemblyReference.XmlIsPrerequisite
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyReference
  nameWithType: AssemblyReference.AssemblyReference
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.AssemblyIdentity*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: AssemblyIdentity
  nameWithType: AssemblyReference.AssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.IsPrerequisite*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: IsPrerequisite
  nameWithType: AssemblyReference.IsPrerequisite
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ReferenceType*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ReferenceType
  nameWithType: AssemblyReference.ReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.SortName*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: SortName
  nameWithType: AssemblyReference.SortName
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.ToString*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: ToString
  nameWithType: AssemblyReference.ToString
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlAssemblyIdentity*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlAssemblyIdentity
  nameWithType: AssemblyReference.XmlAssemblyIdentity
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsNative*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsNative
  nameWithType: AssemblyReference.XmlIsNative
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference.XmlIsPrerequisite*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReference
  isExternal: false
  name: XmlIsPrerequisite
  nameWithType: AssemblyReference.XmlIsPrerequisite
